// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: astraflow/v1/analytics.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAnalyticsServiceCollectEvents = "/astraflow.v1.AnalyticsService/CollectEvents"
const OperationAnalyticsServiceGetOverview = "/astraflow.v1.AnalyticsService/GetOverview"

type AnalyticsServiceHTTPServer interface {
	CollectEvents(context.Context, *CollectAnalyticsEventsRequest) (*CollectAnalyticsEventsResponse, error)
	GetOverview(context.Context, *GetAnalyticsOverviewRequest) (*AnalyticsOverview, error)
}

func RegisterAnalyticsServiceHTTPServer(s *http.Server, srv AnalyticsServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/analytics/events:batch", _AnalyticsService_CollectEvents0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/analytics/overview", _AnalyticsService_GetOverview0_HTTP_Handler(srv))
}

func _AnalyticsService_CollectEvents0_HTTP_Handler(srv AnalyticsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CollectAnalyticsEventsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalyticsServiceCollectEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CollectEvents(ctx, req.(*CollectAnalyticsEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CollectAnalyticsEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _AnalyticsService_GetOverview0_HTTP_Handler(srv AnalyticsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAnalyticsOverviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalyticsServiceGetOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOverview(ctx, req.(*GetAnalyticsOverviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AnalyticsOverview)
		return ctx.Result(200, reply)
	}
}

type AnalyticsServiceHTTPClient interface {
	CollectEvents(ctx context.Context, req *CollectAnalyticsEventsRequest, opts ...http.CallOption) (rsp *CollectAnalyticsEventsResponse, err error)
	GetOverview(ctx context.Context, req *GetAnalyticsOverviewRequest, opts ...http.CallOption) (rsp *AnalyticsOverview, err error)
}

type AnalyticsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAnalyticsServiceHTTPClient(client *http.Client) AnalyticsServiceHTTPClient {
	return &AnalyticsServiceHTTPClientImpl{client}
}

func (c *AnalyticsServiceHTTPClientImpl) CollectEvents(ctx context.Context, in *CollectAnalyticsEventsRequest, opts ...http.CallOption) (*CollectAnalyticsEventsResponse, error) {
	var out CollectAnalyticsEventsResponse
	pattern := "/v1/analytics/events:batch"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAnalyticsServiceCollectEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalyticsServiceHTTPClientImpl) GetOverview(ctx context.Context, in *GetAnalyticsOverviewRequest, opts ...http.CallOption) (*AnalyticsOverview, error) {
	var out AnalyticsOverview
	pattern := "/v1/admin/analytics/overview"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAnalyticsServiceGetOverview),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
