// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astraflow/v1/analytics.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AnonymousId   string                 `protobuf:"bytes,3,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	UserIdHash    string                 `protobuf:"bytes,4,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	EventName     string                 `protobuf:"bytes,5,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	TargetType    string                 `protobuf:"bytes,8,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,9,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetLabel   string                 `protobuf:"bytes,10,opt,name=target_label,json=targetLabel,proto3" json:"target_label,omitempty"`
	ChannelSlug   string                 `protobuf:"bytes,11,opt,name=channel_slug,json=channelSlug,proto3" json:"channel_slug,omitempty"`
	ClientVersion string                 `protobuf:"bytes,12,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Platform      string                 `protobuf:"bytes,13,opt,name=platform,proto3" json:"platform,omitempty"`
	Locale        string                 `protobuf:"bytes,14,opt,name=locale,proto3" json:"locale,omitempty"`
	ScreenWidth   int32                  `protobuf:"varint,15,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight  int32                  `protobuf:"varint,16,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsEvent) Reset() {
	*x = AnalyticsEvent{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsEvent) ProtoMessage() {}

func (x *AnalyticsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsEvent.ProtoReflect.Descriptor instead.
func (*AnalyticsEvent) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AnalyticsEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalyticsEvent) GetAnonymousId() string {
	if x != nil {
		return x.AnonymousId
	}
	return ""
}

func (x *AnalyticsEvent) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *AnalyticsEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *AnalyticsEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AnalyticsEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AnalyticsEvent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AnalyticsEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AnalyticsEvent) GetTargetLabel() string {
	if x != nil {
		return x.TargetLabel
	}
	return ""
}

func (x *AnalyticsEvent) GetChannelSlug() string {
	if x != nil {
		return x.ChannelSlug
	}
	return ""
}

func (x *AnalyticsEvent) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AnalyticsEvent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsEvent) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *AnalyticsEvent) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *AnalyticsEvent) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *AnalyticsEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type CollectAnalyticsEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AnalyticsEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectAnalyticsEventsRequest) Reset() {
	*x = CollectAnalyticsEventsRequest{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectAnalyticsEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectAnalyticsEventsRequest) ProtoMessage() {}

func (x *CollectAnalyticsEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectAnalyticsEventsRequest.ProtoReflect.Descriptor instead.
func (*CollectAnalyticsEventsRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CollectAnalyticsEventsRequest) GetEvents() []*AnalyticsEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CollectAnalyticsEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectAnalyticsEventsResponse) Reset() {
	*x = CollectAnalyticsEventsResponse{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectAnalyticsEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectAnalyticsEventsResponse) ProtoMessage() {}

func (x *CollectAnalyticsEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectAnalyticsEventsResponse.ProtoReflect.Descriptor instead.
func (*CollectAnalyticsEventsResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *CollectAnalyticsEventsResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

type GetAnalyticsOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	ChannelSlug   string                 `protobuf:"bytes,2,opt,name=channel_slug,json=channelSlug,proto3" json:"channel_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsOverviewRequest) Reset() {
	*x = GetAnalyticsOverviewRequest{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsOverviewRequest) ProtoMessage() {}

func (x *GetAnalyticsOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsOverviewRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnalyticsOverviewRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *GetAnalyticsOverviewRequest) GetChannelSlug() string {
	if x != nil {
		return x.ChannelSlug
	}
	return ""
}

type AnalyticsTrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	EventCount    int64                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,3,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsTrendPoint) Reset() {
	*x = AnalyticsTrendPoint{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsTrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsTrendPoint) ProtoMessage() {}

func (x *AnalyticsTrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsTrendPoint.ProtoReflect.Descriptor instead.
func (*AnalyticsTrendPoint) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyticsTrendPoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *AnalyticsTrendPoint) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *AnalyticsTrendPoint) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

type AnalyticsRankedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	EventCount    int64                  `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,4,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRankedItem) Reset() {
	*x = AnalyticsRankedItem{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRankedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRankedItem) ProtoMessage() {}

func (x *AnalyticsRankedItem) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRankedItem.ProtoReflect.Descriptor instead.
func (*AnalyticsRankedItem) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyticsRankedItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AnalyticsRankedItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AnalyticsRankedItem) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *AnalyticsRankedItem) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

type AnalyticsRecentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	TargetLabel   string                 `protobuf:"bytes,2,opt,name=target_label,json=targetLabel,proto3" json:"target_label,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	ChannelSlug   string                 `protobuf:"bytes,4,opt,name=channel_slug,json=channelSlug,proto3" json:"channel_slug,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRecentEvent) Reset() {
	*x = AnalyticsRecentEvent{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRecentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRecentEvent) ProtoMessage() {}

func (x *AnalyticsRecentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRecentEvent.ProtoReflect.Descriptor instead.
func (*AnalyticsRecentEvent) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyticsRecentEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *AnalyticsRecentEvent) GetTargetLabel() string {
	if x != nil {
		return x.TargetLabel
	}
	return ""
}

func (x *AnalyticsRecentEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AnalyticsRecentEvent) GetChannelSlug() string {
	if x != nil {
		return x.ChannelSlug
	}
	return ""
}

func (x *AnalyticsRecentEvent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsRecentEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type AnalyticsOverview struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	PeriodDays     int32                   `protobuf:"varint,1,opt,name=period_days,json=periodDays,proto3" json:"period_days,omitempty"`
	StartAt        *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt          *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	TotalEvents    int64                   `protobuf:"varint,4,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	UniqueUsers    int64                   `protobuf:"varint,5,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	UniqueSessions int64                   `protobuf:"varint,6,opt,name=unique_sessions,json=uniqueSessions,proto3" json:"unique_sessions,omitempty"`
	TodayEvents    int64                   `protobuf:"varint,7,opt,name=today_events,json=todayEvents,proto3" json:"today_events,omitempty"`
	Trend          []*AnalyticsTrendPoint  `protobuf:"bytes,8,rep,name=trend,proto3" json:"trend,omitempty"`
	TopEvents      []*AnalyticsRankedItem  `protobuf:"bytes,9,rep,name=top_events,json=topEvents,proto3" json:"top_events,omitempty"`
	TopPages       []*AnalyticsRankedItem  `protobuf:"bytes,10,rep,name=top_pages,json=topPages,proto3" json:"top_pages,omitempty"`
	Channels       []*AnalyticsRankedItem  `protobuf:"bytes,11,rep,name=channels,proto3" json:"channels,omitempty"`
	RecentEvents   []*AnalyticsRecentEvent `protobuf:"bytes,12,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyticsOverview) Reset() {
	*x = AnalyticsOverview{}
	mi := &file_astraflow_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsOverview) ProtoMessage() {}

func (x *AnalyticsOverview) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsOverview.ProtoReflect.Descriptor instead.
func (*AnalyticsOverview) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyticsOverview) GetPeriodDays() int32 {
	if x != nil {
		return x.PeriodDays
	}
	return 0
}

func (x *AnalyticsOverview) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *AnalyticsOverview) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *AnalyticsOverview) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *AnalyticsOverview) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *AnalyticsOverview) GetUniqueSessions() int64 {
	if x != nil {
		return x.UniqueSessions
	}
	return 0
}

func (x *AnalyticsOverview) GetTodayEvents() int64 {
	if x != nil {
		return x.TodayEvents
	}
	return 0
}

func (x *AnalyticsOverview) GetTrend() []*AnalyticsTrendPoint {
	if x != nil {
		return x.Trend
	}
	return nil
}

func (x *AnalyticsOverview) GetTopEvents() []*AnalyticsRankedItem {
	if x != nil {
		return x.TopEvents
	}
	return nil
}

func (x *AnalyticsOverview) GetTopPages() []*AnalyticsRankedItem {
	if x != nil {
		return x.TopPages
	}
	return nil
}

func (x *AnalyticsOverview) GetChannels() []*AnalyticsRankedItem {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *AnalyticsOverview) GetRecentEvents() []*AnalyticsRecentEvent {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

var File_astraflow_v1_analytics_proto protoreflect.FileDescriptor

const file_astraflow_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1castraflow/v1/analytics.proto\x12\fastraflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x04\n" +
	"\x0eAnalyticsEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fanonymous_id\x18\x03 \x01(\tR\vanonymousId\x12 \n" +
	"\fuser_id_hash\x18\x04 \x01(\tR\n" +
	"userIdHash\x12\x1d\n" +
	"\n" +
	"event_name\x18\x05 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1f\n" +
	"\vtarget_type\x18\b \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\t \x01(\tR\btargetId\x12!\n" +
	"\ftarget_label\x18\n" +
	" \x01(\tR\vtargetLabel\x12!\n" +
	"\fchannel_slug\x18\v \x01(\tR\vchannelSlug\x12%\n" +
	"\x0eclient_version\x18\f \x01(\tR\rclientVersion\x12\x1a\n" +
	"\bplatform\x18\r \x01(\tR\bplatform\x12\x16\n" +
	"\x06locale\x18\x0e \x01(\tR\x06locale\x12!\n" +
	"\fscreen_width\x18\x0f \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\x10 \x01(\x05R\fscreenHeight\x12;\n" +
	"\voccurred_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"U\n" +
	"\x1dCollectAnalyticsEventsRequest\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.astraflow.v1.AnalyticsEventR\x06events\"G\n" +
	"\x1eCollectAnalyticsEventsResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\"T\n" +
	"\x1bGetAnalyticsOverviewRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\x12!\n" +
	"\fchannel_slug\x18\x02 \x01(\tR\vchannelSlug\"\x89\x01\n" +
	"\x13AnalyticsTrendPoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x03R\n" +
	"eventCount\x12!\n" +
	"\funique_users\x18\x03 \x01(\x03R\vuniqueUsers\"\x81\x01\n" +
	"\x13AnalyticsRankedItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\x03R\n" +
	"eventCount\x12!\n" +
	"\funique_users\x18\x04 \x01(\x03R\vuniqueUsers\"\xe8\x01\n" +
	"\x14AnalyticsRecentEvent\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12!\n" +
	"\ftarget_label\x18\x02 \x01(\tR\vtargetLabel\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\fchannel_slug\x18\x04 \x01(\tR\vchannelSlug\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xf3\x04\n" +
	"\x11AnalyticsOverview\x12\x1f\n" +
	"\vperiod_days\x18\x01 \x01(\x05R\n" +
	"periodDays\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12!\n" +
	"\ftotal_events\x18\x04 \x01(\x03R\vtotalEvents\x12!\n" +
	"\funique_users\x18\x05 \x01(\x03R\vuniqueUsers\x12'\n" +
	"\x0funique_sessions\x18\x06 \x01(\x03R\x0euniqueSessions\x12!\n" +
	"\ftoday_events\x18\a \x01(\x03R\vtodayEvents\x127\n" +
	"\x05trend\x18\b \x03(\v2!.astraflow.v1.AnalyticsTrendPointR\x05trend\x12@\n" +
	"\n" +
	"top_events\x18\t \x03(\v2!.astraflow.v1.AnalyticsRankedItemR\ttopEvents\x12>\n" +
	"\ttop_pages\x18\n" +
	" \x03(\v2!.astraflow.v1.AnalyticsRankedItemR\btopPages\x12=\n" +
	"\bchannels\x18\v \x03(\v2!.astraflow.v1.AnalyticsRankedItemR\bchannels\x12G\n" +
	"\rrecent_events\x18\f \x03(\v2\".astraflow.v1.AnalyticsRecentEventR\frecentEvents2\xa7\x02\n" +
	"\x10AnalyticsService\x12\x91\x01\n" +
	"\rCollectEvents\x12+.astraflow.v1.CollectAnalyticsEventsRequest\x1a,.astraflow.v1.CollectAnalyticsEventsResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/analytics/events:batch\x12\x7f\n" +
	"\vGetOverview\x12).astraflow.v1.GetAnalyticsOverviewRequest\x1a\x1f.astraflow.v1.AnalyticsOverview\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/admin/analytics/overviewBD\n" +
	"\x17com.ucloud.astraflow.v1P\x01Z!astraflow-api/api/astraflow/v1;v1\xa2\x02\x03AFAb\x06proto3"

var (
	file_astraflow_v1_analytics_proto_rawDescOnce sync.Once
	file_astraflow_v1_analytics_proto_rawDescData []byte
)

func file_astraflow_v1_analytics_proto_rawDescGZIP() []byte {
	file_astraflow_v1_analytics_proto_rawDescOnce.Do(func() {
		file_astraflow_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraflow_v1_analytics_proto_rawDesc), len(file_astraflow_v1_analytics_proto_rawDesc)))
	})
	return file_astraflow_v1_analytics_proto_rawDescData
}

var file_astraflow_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_astraflow_v1_analytics_proto_goTypes = []any{
	(*AnalyticsEvent)(nil),                 // 0: astraflow.v1.AnalyticsEvent
	(*CollectAnalyticsEventsRequest)(nil),  // 1: astraflow.v1.CollectAnalyticsEventsRequest
	(*CollectAnalyticsEventsResponse)(nil), // 2: astraflow.v1.CollectAnalyticsEventsResponse
	(*GetAnalyticsOverviewRequest)(nil),    // 3: astraflow.v1.GetAnalyticsOverviewRequest
	(*AnalyticsTrendPoint)(nil),            // 4: astraflow.v1.AnalyticsTrendPoint
	(*AnalyticsRankedItem)(nil),            // 5: astraflow.v1.AnalyticsRankedItem
	(*AnalyticsRecentEvent)(nil),           // 6: astraflow.v1.AnalyticsRecentEvent
	(*AnalyticsOverview)(nil),              // 7: astraflow.v1.AnalyticsOverview
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_astraflow_v1_analytics_proto_depIdxs = []int32{
	8,  // 0: astraflow.v1.AnalyticsEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 1: astraflow.v1.CollectAnalyticsEventsRequest.events:type_name -> astraflow.v1.AnalyticsEvent
	8,  // 2: astraflow.v1.AnalyticsTrendPoint.date:type_name -> google.protobuf.Timestamp
	8,  // 3: astraflow.v1.AnalyticsRecentEvent.occurred_at:type_name -> google.protobuf.Timestamp
	8,  // 4: astraflow.v1.AnalyticsOverview.start_at:type_name -> google.protobuf.Timestamp
	8,  // 5: astraflow.v1.AnalyticsOverview.end_at:type_name -> google.protobuf.Timestamp
	4,  // 6: astraflow.v1.AnalyticsOverview.trend:type_name -> astraflow.v1.AnalyticsTrendPoint
	5,  // 7: astraflow.v1.AnalyticsOverview.top_events:type_name -> astraflow.v1.AnalyticsRankedItem
	5,  // 8: astraflow.v1.AnalyticsOverview.top_pages:type_name -> astraflow.v1.AnalyticsRankedItem
	5,  // 9: astraflow.v1.AnalyticsOverview.channels:type_name -> astraflow.v1.AnalyticsRankedItem
	6,  // 10: astraflow.v1.AnalyticsOverview.recent_events:type_name -> astraflow.v1.AnalyticsRecentEvent
	1,  // 11: astraflow.v1.AnalyticsService.CollectEvents:input_type -> astraflow.v1.CollectAnalyticsEventsRequest
	3,  // 12: astraflow.v1.AnalyticsService.GetOverview:input_type -> astraflow.v1.GetAnalyticsOverviewRequest
	2,  // 13: astraflow.v1.AnalyticsService.CollectEvents:output_type -> astraflow.v1.CollectAnalyticsEventsResponse
	7,  // 14: astraflow.v1.AnalyticsService.GetOverview:output_type -> astraflow.v1.AnalyticsOverview
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_astraflow_v1_analytics_proto_init() }
func file_astraflow_v1_analytics_proto_init() {
	if File_astraflow_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraflow_v1_analytics_proto_rawDesc), len(file_astraflow_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraflow_v1_analytics_proto_goTypes,
		DependencyIndexes: file_astraflow_v1_analytics_proto_depIdxs,
		MessageInfos:      file_astraflow_v1_analytics_proto_msgTypes,
	}.Build()
	File_astraflow_v1_analytics_proto = out.File
	file_astraflow_v1_analytics_proto_goTypes = nil
	file_astraflow_v1_analytics_proto_depIdxs = nil
}
