// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astraflow/v1/channel.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                        string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status                      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	OauthClientId               string                 `protobuf:"bytes,5,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`
	OauthClientSecretConfigured bool                   `protobuf:"varint,6,opt,name=oauth_client_secret_configured,json=oauthClientSecretConfigured,proto3" json:"oauth_client_secret_configured,omitempty"`
	EnabledFeatures             []string               `protobuf:"bytes,7,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	RestrictModels              bool                   `protobuf:"varint,8,opt,name=restrict_models,json=restrictModels,proto3" json:"restrict_models,omitempty"`
	AllowedModelIds             []string               `protobuf:"bytes,9,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	CreatedAt                   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Channel) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *Channel) GetOauthClientSecretConfigured() bool {
	if x != nil {
		return x.OauthClientSecretConfigured
	}
	return false
}

func (x *Channel) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

func (x *Channel) GetRestrictModels() bool {
	if x != nil {
		return x.RestrictModels
	}
	return false
}

func (x *Channel) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

func (x *Channel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Channel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChannelRuntimeConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slug            string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OauthClientId   string                 `protobuf:"bytes,3,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`
	EnabledFeatures []string               `protobuf:"bytes,4,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	RestrictModels  bool                   `protobuf:"varint,5,opt,name=restrict_models,json=restrictModels,proto3" json:"restrict_models,omitempty"`
	AllowedModelIds []string               `protobuf:"bytes,6,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	Revision        int64                  `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelRuntimeConfig) Reset() {
	*x = ChannelRuntimeConfig{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRuntimeConfig) ProtoMessage() {}

func (x *ChannelRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRuntimeConfig.ProtoReflect.Descriptor instead.
func (*ChannelRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelRuntimeConfig) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ChannelRuntimeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelRuntimeConfig) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *ChannelRuntimeConfig) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

func (x *ChannelRuntimeConfig) GetRestrictModels() bool {
	if x != nil {
		return x.RestrictModels
	}
	return false
}

func (x *ChannelRuntimeConfig) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

func (x *ChannelRuntimeConfig) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChannelsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListChannelsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListChannelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int32                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ListChannelsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListChannelsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{4}
}

func (x *GetChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type CreateChannelRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Slug              string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OauthClientId     string                 `protobuf:"bytes,4,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`
	OauthClientSecret string                 `protobuf:"bytes,5,opt,name=oauth_client_secret,json=oauthClientSecret,proto3" json:"oauth_client_secret,omitempty"`
	EnabledFeatures   []string               `protobuf:"bytes,6,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	RestrictModels    bool                   `protobuf:"varint,7,opt,name=restrict_models,json=restrictModels,proto3" json:"restrict_models,omitempty"`
	AllowedModelIds   []string               `protobuf:"bytes,8,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{5}
}

func (x *CreateChannelRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateChannelRequest) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *CreateChannelRequest) GetOauthClientSecret() string {
	if x != nil {
		return x.OauthClientSecret
	}
	return ""
}

func (x *CreateChannelRequest) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

func (x *CreateChannelRequest) GetRestrictModels() bool {
	if x != nil {
		return x.RestrictModels
	}
	return false
}

func (x *CreateChannelRequest) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

type UpdateChannelRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ChannelId              string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Slug                   string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status                 string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	OauthClientId          string                 `protobuf:"bytes,5,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`
	OauthClientSecret      string                 `protobuf:"bytes,6,opt,name=oauth_client_secret,json=oauthClientSecret,proto3" json:"oauth_client_secret,omitempty"`
	ClearOauthClientSecret bool                   `protobuf:"varint,7,opt,name=clear_oauth_client_secret,json=clearOauthClientSecret,proto3" json:"clear_oauth_client_secret,omitempty"`
	EnabledFeatures        []string               `protobuf:"bytes,8,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	RestrictModels         bool                   `protobuf:"varint,9,opt,name=restrict_models,json=restrictModels,proto3" json:"restrict_models,omitempty"`
	AllowedModelIds        []string               `protobuf:"bytes,10,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UpdateChannelRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChannelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateChannelRequest) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *UpdateChannelRequest) GetOauthClientSecret() string {
	if x != nil {
		return x.OauthClientSecret
	}
	return ""
}

func (x *UpdateChannelRequest) GetClearOauthClientSecret() bool {
	if x != nil {
		return x.ClearOauthClientSecret
	}
	return false
}

func (x *UpdateChannelRequest) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

func (x *UpdateChannelRequest) GetRestrictModels() bool {
	if x != nil {
		return x.RestrictModels
	}
	return false
}

func (x *UpdateChannelRequest) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetChannelRuntimeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRuntimeConfigRequest) Reset() {
	*x = GetChannelRuntimeConfigRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRuntimeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRuntimeConfigRequest) ProtoMessage() {}

func (x *GetChannelRuntimeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRuntimeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRuntimeConfigRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{8}
}

func (x *GetChannelRuntimeConfigRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type StartChannelOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChannelOAuthRequest) Reset() {
	*x = StartChannelOAuthRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChannelOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChannelOAuthRequest) ProtoMessage() {}

func (x *StartChannelOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChannelOAuthRequest.ProtoReflect.Descriptor instead.
func (*StartChannelOAuthRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{9}
}

func (x *StartChannelOAuthRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *StartChannelOAuthRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type StartChannelOAuthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartChannelOAuthResponse) Reset() {
	*x = StartChannelOAuthResponse{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChannelOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChannelOAuthResponse) ProtoMessage() {}

func (x *StartChannelOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChannelOAuthResponse.ProtoReflect.Descriptor instead.
func (*StartChannelOAuthResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{10}
}

func (x *StartChannelOAuthResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *StartChannelOAuthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StartChannelOAuthResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ExchangeChannelOAuthCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeChannelOAuthCodeRequest) Reset() {
	*x = ExchangeChannelOAuthCodeRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeChannelOAuthCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeChannelOAuthCodeRequest) ProtoMessage() {}

func (x *ExchangeChannelOAuthCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeChannelOAuthCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeChannelOAuthCodeRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{11}
}

func (x *ExchangeChannelOAuthCodeRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ExchangeChannelOAuthCodeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExchangeChannelOAuthCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeChannelOAuthCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type RefreshChannelOAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshChannelOAuthTokenRequest) Reset() {
	*x = RefreshChannelOAuthTokenRequest{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshChannelOAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshChannelOAuthTokenRequest) ProtoMessage() {}

func (x *RefreshChannelOAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshChannelOAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshChannelOAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshChannelOAuthTokenRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RefreshChannelOAuthTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ChannelOAuthTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	IdToken       string                 `protobuf:"bytes,5,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelOAuthTokens) Reset() {
	*x = ChannelOAuthTokens{}
	mi := &file_astraflow_v1_channel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOAuthTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOAuthTokens) ProtoMessage() {}

func (x *ChannelOAuthTokens) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_channel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOAuthTokens.ProtoReflect.Descriptor instead.
func (*ChannelOAuthTokens) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_channel_proto_rawDescGZIP(), []int{13}
}

func (x *ChannelOAuthTokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ChannelOAuthTokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ChannelOAuthTokens) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ChannelOAuthTokens) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ChannelOAuthTokens) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

var File_astraflow_v1_channel_proto protoreflect.FileDescriptor

const file_astraflow_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x1aastraflow/v1/channel.proto\x12\fastraflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x03\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0foauth_client_id\x18\x05 \x01(\tR\roauthClientId\x12C\n" +
	"\x1eoauth_client_secret_configured\x18\x06 \x01(\bR\x1boauthClientSecretConfigured\x12)\n" +
	"\x10enabled_features\x18\a \x03(\tR\x0fenabledFeatures\x12'\n" +
	"\x0frestrict_models\x18\b \x01(\bR\x0erestrictModels\x12*\n" +
	"\x11allowed_model_ids\x18\t \x03(\tR\x0fallowedModelIds\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x02\n" +
	"\x14ChannelRuntimeConfig\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0foauth_client_id\x18\x03 \x01(\tR\roauthClientId\x12)\n" +
	"\x10enabled_features\x18\x04 \x03(\tR\x0fenabledFeatures\x12'\n" +
	"\x0frestrict_models\x18\x05 \x01(\bR\x0erestrictModels\x12*\n" +
	"\x11allowed_model_ids\x18\x06 \x03(\tR\x0fallowedModelIds\x12\x1a\n" +
	"\brevision\x18\a \x01(\x03R\brevision\"\x7f\n" +
	"\x13ListChannelsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x90\x01\n" +
	"\x14ListChannelsResponse\x121\n" +
	"\bchannels\x18\x01 \x03(\v2\x15.astraflow.v1.ChannelR\bchannels\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"2\n" +
	"\x11GetChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\xae\x02\n" +
	"\x14CreateChannelRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12&\n" +
	"\x0foauth_client_id\x18\x04 \x01(\tR\roauthClientId\x12.\n" +
	"\x13oauth_client_secret\x18\x05 \x01(\tR\x11oauthClientSecret\x12)\n" +
	"\x10enabled_features\x18\x06 \x03(\tR\x0fenabledFeatures\x12'\n" +
	"\x0frestrict_models\x18\a \x01(\bR\x0erestrictModels\x12*\n" +
	"\x11allowed_model_ids\x18\b \x03(\tR\x0fallowedModelIds\"\x88\x03\n" +
	"\x14UpdateChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0foauth_client_id\x18\x05 \x01(\tR\roauthClientId\x12.\n" +
	"\x13oauth_client_secret\x18\x06 \x01(\tR\x11oauthClientSecret\x129\n" +
	"\x19clear_oauth_client_secret\x18\a \x01(\bR\x16clearOauthClientSecret\x12)\n" +
	"\x10enabled_features\x18\b \x03(\tR\x0fenabledFeatures\x12'\n" +
	"\x0frestrict_models\x18\t \x01(\bR\x0erestrictModels\x12*\n" +
	"\x11allowed_model_ids\x18\n" +
	" \x03(\tR\x0fallowedModelIds\"5\n" +
	"\x14DeleteChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"4\n" +
	"\x1eGetChannelRuntimeConfigRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"Q\n" +
	"\x18StartChannelOAuthRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\"\x99\x01\n" +
	"\x19StartChannelOAuthResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x82\x01\n" +
	"\x1fExchangeChannelOAuthCodeRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\"Z\n" +
	"\x1fRefreshChannelOAuthTokenRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\xb5\x01\n" +
	"\x12ChannelOAuthTokens\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12\x19\n" +
	"\bid_token\x18\x05 \x01(\tR\aidToken2\xa9\t\n" +
	"\x0eChannelService\x12\x8f\x01\n" +
	"\x17GetChannelRuntimeConfig\x12,.astraflow.v1.GetChannelRuntimeConfigRequest\x1a\".astraflow.v1.ChannelRuntimeConfig\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/channels/{slug}/config\x12\x90\x01\n" +
	"\x11StartChannelOAuth\x12&.astraflow.v1.StartChannelOAuthRequest\x1a'.astraflow.v1.StartChannelOAuthResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/channels/{slug}/oauth/start\x12\x9a\x01\n" +
	"\x18ExchangeChannelOAuthCode\x12-.astraflow.v1.ExchangeChannelOAuthCodeRequest\x1a .astraflow.v1.ChannelOAuthTokens\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/channels/{slug}/oauth/exchange\x12\x99\x01\n" +
	"\x18RefreshChannelOAuthToken\x12-.astraflow.v1.RefreshChannelOAuthTokenRequest\x1a .astraflow.v1.ChannelOAuthTokens\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/channels/{slug}/oauth/refresh\x12q\n" +
	"\fListChannels\x12!.astraflow.v1.ListChannelsRequest\x1a\".astraflow.v1.ListChannelsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/admin/channels\x12m\n" +
	"\n" +
	"GetChannel\x12\x1f.astraflow.v1.GetChannelRequest\x1a\x15.astraflow.v1.Channel\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/admin/channels/{channel_id}\x12i\n" +
	"\rCreateChannel\x12\".astraflow.v1.CreateChannelRequest\x1a\x15.astraflow.v1.Channel\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/admin/channels\x12v\n" +
	"\rUpdateChannel\x12\".astraflow.v1.UpdateChannelRequest\x1a\x15.astraflow.v1.Channel\"*\x82\xd3\xe4\x93\x02$:\x01*2\x1f/v1/admin/channels/{channel_id}\x12t\n" +
	"\rDeleteChannel\x12\".astraflow.v1.DeleteChannelRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/admin/channels/{channel_id}BD\n" +
	"\x17com.ucloud.astraflow.v1P\x01Z!astraflow-api/api/astraflow/v1;v1\xa2\x02\x03AFAb\x06proto3"

var (
	file_astraflow_v1_channel_proto_rawDescOnce sync.Once
	file_astraflow_v1_channel_proto_rawDescData []byte
)

func file_astraflow_v1_channel_proto_rawDescGZIP() []byte {
	file_astraflow_v1_channel_proto_rawDescOnce.Do(func() {
		file_astraflow_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraflow_v1_channel_proto_rawDesc), len(file_astraflow_v1_channel_proto_rawDesc)))
	})
	return file_astraflow_v1_channel_proto_rawDescData
}

var file_astraflow_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_astraflow_v1_channel_proto_goTypes = []any{
	(*Channel)(nil),                         // 0: astraflow.v1.Channel
	(*ChannelRuntimeConfig)(nil),            // 1: astraflow.v1.ChannelRuntimeConfig
	(*ListChannelsRequest)(nil),             // 2: astraflow.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),            // 3: astraflow.v1.ListChannelsResponse
	(*GetChannelRequest)(nil),               // 4: astraflow.v1.GetChannelRequest
	(*CreateChannelRequest)(nil),            // 5: astraflow.v1.CreateChannelRequest
	(*UpdateChannelRequest)(nil),            // 6: astraflow.v1.UpdateChannelRequest
	(*DeleteChannelRequest)(nil),            // 7: astraflow.v1.DeleteChannelRequest
	(*GetChannelRuntimeConfigRequest)(nil),  // 8: astraflow.v1.GetChannelRuntimeConfigRequest
	(*StartChannelOAuthRequest)(nil),        // 9: astraflow.v1.StartChannelOAuthRequest
	(*StartChannelOAuthResponse)(nil),       // 10: astraflow.v1.StartChannelOAuthResponse
	(*ExchangeChannelOAuthCodeRequest)(nil), // 11: astraflow.v1.ExchangeChannelOAuthCodeRequest
	(*RefreshChannelOAuthTokenRequest)(nil), // 12: astraflow.v1.RefreshChannelOAuthTokenRequest
	(*ChannelOAuthTokens)(nil),              // 13: astraflow.v1.ChannelOAuthTokens
	(*timestamppb.Timestamp)(nil),           // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 15: google.protobuf.Empty
}
var file_astraflow_v1_channel_proto_depIdxs = []int32{
	14, // 0: astraflow.v1.Channel.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: astraflow.v1.Channel.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: astraflow.v1.ListChannelsResponse.channels:type_name -> astraflow.v1.Channel
	14, // 3: astraflow.v1.StartChannelOAuthResponse.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 4: astraflow.v1.ChannelService.GetChannelRuntimeConfig:input_type -> astraflow.v1.GetChannelRuntimeConfigRequest
	9,  // 5: astraflow.v1.ChannelService.StartChannelOAuth:input_type -> astraflow.v1.StartChannelOAuthRequest
	11, // 6: astraflow.v1.ChannelService.ExchangeChannelOAuthCode:input_type -> astraflow.v1.ExchangeChannelOAuthCodeRequest
	12, // 7: astraflow.v1.ChannelService.RefreshChannelOAuthToken:input_type -> astraflow.v1.RefreshChannelOAuthTokenRequest
	2,  // 8: astraflow.v1.ChannelService.ListChannels:input_type -> astraflow.v1.ListChannelsRequest
	4,  // 9: astraflow.v1.ChannelService.GetChannel:input_type -> astraflow.v1.GetChannelRequest
	5,  // 10: astraflow.v1.ChannelService.CreateChannel:input_type -> astraflow.v1.CreateChannelRequest
	6,  // 11: astraflow.v1.ChannelService.UpdateChannel:input_type -> astraflow.v1.UpdateChannelRequest
	7,  // 12: astraflow.v1.ChannelService.DeleteChannel:input_type -> astraflow.v1.DeleteChannelRequest
	1,  // 13: astraflow.v1.ChannelService.GetChannelRuntimeConfig:output_type -> astraflow.v1.ChannelRuntimeConfig
	10, // 14: astraflow.v1.ChannelService.StartChannelOAuth:output_type -> astraflow.v1.StartChannelOAuthResponse
	13, // 15: astraflow.v1.ChannelService.ExchangeChannelOAuthCode:output_type -> astraflow.v1.ChannelOAuthTokens
	13, // 16: astraflow.v1.ChannelService.RefreshChannelOAuthToken:output_type -> astraflow.v1.ChannelOAuthTokens
	3,  // 17: astraflow.v1.ChannelService.ListChannels:output_type -> astraflow.v1.ListChannelsResponse
	0,  // 18: astraflow.v1.ChannelService.GetChannel:output_type -> astraflow.v1.Channel
	0,  // 19: astraflow.v1.ChannelService.CreateChannel:output_type -> astraflow.v1.Channel
	0,  // 20: astraflow.v1.ChannelService.UpdateChannel:output_type -> astraflow.v1.Channel
	15, // 21: astraflow.v1.ChannelService.DeleteChannel:output_type -> google.protobuf.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_astraflow_v1_channel_proto_init() }
func file_astraflow_v1_channel_proto_init() {
	if File_astraflow_v1_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraflow_v1_channel_proto_rawDesc), len(file_astraflow_v1_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraflow_v1_channel_proto_goTypes,
		DependencyIndexes: file_astraflow_v1_channel_proto_depIdxs,
		MessageInfos:      file_astraflow_v1_channel_proto_msgTypes,
	}.Build()
	File_astraflow_v1_channel_proto = out.File
	file_astraflow_v1_channel_proto_goTypes = nil
	file_astraflow_v1_channel_proto_depIdxs = nil
}
