// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: astraflow/v1/channel.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationChannelServiceCreateChannel = "/astraflow.v1.ChannelService/CreateChannel"
const OperationChannelServiceDeleteChannel = "/astraflow.v1.ChannelService/DeleteChannel"
const OperationChannelServiceExchangeChannelOAuthCode = "/astraflow.v1.ChannelService/ExchangeChannelOAuthCode"
const OperationChannelServiceGetChannel = "/astraflow.v1.ChannelService/GetChannel"
const OperationChannelServiceGetChannelRuntimeConfig = "/astraflow.v1.ChannelService/GetChannelRuntimeConfig"
const OperationChannelServiceListChannels = "/astraflow.v1.ChannelService/ListChannels"
const OperationChannelServiceRefreshChannelOAuthToken = "/astraflow.v1.ChannelService/RefreshChannelOAuthToken"
const OperationChannelServiceStartChannelOAuth = "/astraflow.v1.ChannelService/StartChannelOAuth"
const OperationChannelServiceUpdateChannel = "/astraflow.v1.ChannelService/UpdateChannel"

type ChannelServiceHTTPServer interface {
	CreateChannel(context.Context, *CreateChannelRequest) (*Channel, error)
	DeleteChannel(context.Context, *DeleteChannelRequest) (*emptypb.Empty, error)
	ExchangeChannelOAuthCode(context.Context, *ExchangeChannelOAuthCodeRequest) (*ChannelOAuthTokens, error)
	GetChannel(context.Context, *GetChannelRequest) (*Channel, error)
	GetChannelRuntimeConfig(context.Context, *GetChannelRuntimeConfigRequest) (*ChannelRuntimeConfig, error)
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error)
	RefreshChannelOAuthToken(context.Context, *RefreshChannelOAuthTokenRequest) (*ChannelOAuthTokens, error)
	StartChannelOAuth(context.Context, *StartChannelOAuthRequest) (*StartChannelOAuthResponse, error)
	UpdateChannel(context.Context, *UpdateChannelRequest) (*Channel, error)
}

func RegisterChannelServiceHTTPServer(s *http.Server, srv ChannelServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/channels/{slug}/config", _ChannelService_GetChannelRuntimeConfig0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/channels/{slug}/oauth/start", _ChannelService_StartChannelOAuth0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/channels/{slug}/oauth/exchange", _ChannelService_ExchangeChannelOAuthCode0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/channels/{slug}/oauth/refresh", _ChannelService_RefreshChannelOAuthToken0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/channels", _ChannelService_ListChannels0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/channels/{channel_id}", _ChannelService_GetChannel0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/channels", _ChannelService_CreateChannel0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/channels/{channel_id}", _ChannelService_UpdateChannel0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/channels/{channel_id}", _ChannelService_DeleteChannel0_HTTP_Handler(srv))
}

func _ChannelService_GetChannelRuntimeConfig0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChannelRuntimeConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceGetChannelRuntimeConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChannelRuntimeConfig(ctx, req.(*GetChannelRuntimeConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelRuntimeConfig)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_StartChannelOAuth0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartChannelOAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceStartChannelOAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartChannelOAuth(ctx, req.(*StartChannelOAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartChannelOAuthResponse)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_ExchangeChannelOAuthCode0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExchangeChannelOAuthCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceExchangeChannelOAuthCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExchangeChannelOAuthCode(ctx, req.(*ExchangeChannelOAuthCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelOAuthTokens)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_RefreshChannelOAuthToken0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshChannelOAuthTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceRefreshChannelOAuthToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshChannelOAuthToken(ctx, req.(*RefreshChannelOAuthTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelOAuthTokens)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_ListChannels0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChannelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceListChannels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChannels(ctx, req.(*ListChannelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChannelsResponse)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_GetChannel0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChannelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceGetChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChannel(ctx, req.(*GetChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Channel)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_CreateChannel0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceCreateChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateChannel(ctx, req.(*CreateChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Channel)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_UpdateChannel0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceUpdateChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateChannel(ctx, req.(*UpdateChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Channel)
		return ctx.Result(200, reply)
	}
}

func _ChannelService_DeleteChannel0_HTTP_Handler(srv ChannelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteChannelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelServiceDeleteChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteChannel(ctx, req.(*DeleteChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ChannelServiceHTTPClient interface {
	CreateChannel(ctx context.Context, req *CreateChannelRequest, opts ...http.CallOption) (rsp *Channel, err error)
	DeleteChannel(ctx context.Context, req *DeleteChannelRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ExchangeChannelOAuthCode(ctx context.Context, req *ExchangeChannelOAuthCodeRequest, opts ...http.CallOption) (rsp *ChannelOAuthTokens, err error)
	GetChannel(ctx context.Context, req *GetChannelRequest, opts ...http.CallOption) (rsp *Channel, err error)
	GetChannelRuntimeConfig(ctx context.Context, req *GetChannelRuntimeConfigRequest, opts ...http.CallOption) (rsp *ChannelRuntimeConfig, err error)
	ListChannels(ctx context.Context, req *ListChannelsRequest, opts ...http.CallOption) (rsp *ListChannelsResponse, err error)
	RefreshChannelOAuthToken(ctx context.Context, req *RefreshChannelOAuthTokenRequest, opts ...http.CallOption) (rsp *ChannelOAuthTokens, err error)
	StartChannelOAuth(ctx context.Context, req *StartChannelOAuthRequest, opts ...http.CallOption) (rsp *StartChannelOAuthResponse, err error)
	UpdateChannel(ctx context.Context, req *UpdateChannelRequest, opts ...http.CallOption) (rsp *Channel, err error)
}

type ChannelServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewChannelServiceHTTPClient(client *http.Client) ChannelServiceHTTPClient {
	return &ChannelServiceHTTPClientImpl{client}
}

func (c *ChannelServiceHTTPClientImpl) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...http.CallOption) (*Channel, error) {
	var out Channel
	pattern := "/v1/admin/channels"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChannelServiceCreateChannel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/channels/{channel_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChannelServiceDeleteChannel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) ExchangeChannelOAuthCode(ctx context.Context, in *ExchangeChannelOAuthCodeRequest, opts ...http.CallOption) (*ChannelOAuthTokens, error) {
	var out ChannelOAuthTokens
	pattern := "/v1/channels/{slug}/oauth/exchange"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChannelServiceExchangeChannelOAuthCode),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) GetChannel(ctx context.Context, in *GetChannelRequest, opts ...http.CallOption) (*Channel, error) {
	var out Channel
	pattern := "/v1/admin/channels/{channel_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChannelServiceGetChannel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) GetChannelRuntimeConfig(ctx context.Context, in *GetChannelRuntimeConfigRequest, opts ...http.CallOption) (*ChannelRuntimeConfig, error) {
	var out ChannelRuntimeConfig
	pattern := "/v1/channels/{slug}/config"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChannelServiceGetChannelRuntimeConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...http.CallOption) (*ListChannelsResponse, error) {
	var out ListChannelsResponse
	pattern := "/v1/admin/channels"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChannelServiceListChannels),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) RefreshChannelOAuthToken(ctx context.Context, in *RefreshChannelOAuthTokenRequest, opts ...http.CallOption) (*ChannelOAuthTokens, error) {
	var out ChannelOAuthTokens
	pattern := "/v1/channels/{slug}/oauth/refresh"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChannelServiceRefreshChannelOAuthToken),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) StartChannelOAuth(ctx context.Context, in *StartChannelOAuthRequest, opts ...http.CallOption) (*StartChannelOAuthResponse, error) {
	var out StartChannelOAuthResponse
	pattern := "/v1/channels/{slug}/oauth/start"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChannelServiceStartChannelOAuth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChannelServiceHTTPClientImpl) UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...http.CallOption) (*Channel, error) {
	var out Channel
	pattern := "/v1/admin/channels/{channel_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChannelServiceUpdateChannel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
