// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: astraflow/v1/cross_device.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrossDeviceService_GetNativeOAuthConfig_FullMethodName        = "/astraflow.v1.CrossDeviceService/GetNativeOAuthConfig"
	CrossDeviceService_ExchangeNativeOAuthCode_FullMethodName     = "/astraflow.v1.CrossDeviceService/ExchangeNativeOAuthCode"
	CrossDeviceService_RefreshNativeOAuthToken_FullMethodName     = "/astraflow.v1.CrossDeviceService/RefreshNativeOAuthToken"
	CrossDeviceService_GetCurrentAccount_FullMethodName           = "/astraflow.v1.CrossDeviceService/GetCurrentAccount"
	CrossDeviceService_RegisterDevice_FullMethodName              = "/astraflow.v1.CrossDeviceService/RegisterDevice"
	CrossDeviceService_ListDevices_FullMethodName                 = "/astraflow.v1.CrossDeviceService/ListDevices"
	CrossDeviceService_RevokeDevice_FullMethodName                = "/astraflow.v1.CrossDeviceService/RevokeDevice"
	CrossDeviceService_CreateDeviceConnectionToken_FullMethodName = "/astraflow.v1.CrossDeviceService/CreateDeviceConnectionToken"
	CrossDeviceService_UpsertPushEndpoint_FullMethodName          = "/astraflow.v1.CrossDeviceService/UpsertPushEndpoint"
	CrossDeviceService_CreateWorkspace_FullMethodName             = "/astraflow.v1.CrossDeviceService/CreateWorkspace"
	CrossDeviceService_ListWorkspaces_FullMethodName              = "/astraflow.v1.CrossDeviceService/ListWorkspaces"
	CrossDeviceService_GetWorkspace_FullMethodName                = "/astraflow.v1.CrossDeviceService/GetWorkspace"
	CrossDeviceService_CreateSession_FullMethodName               = "/astraflow.v1.CrossDeviceService/CreateSession"
	CrossDeviceService_ListSessions_FullMethodName                = "/astraflow.v1.CrossDeviceService/ListSessions"
	CrossDeviceService_GetSession_FullMethodName                  = "/astraflow.v1.CrossDeviceService/GetSession"
	CrossDeviceService_UpdateSession_FullMethodName               = "/astraflow.v1.CrossDeviceService/UpdateSession"
	CrossDeviceService_CreateMessage_FullMethodName               = "/astraflow.v1.CrossDeviceService/CreateMessage"
	CrossDeviceService_ListMessages_FullMethodName                = "/astraflow.v1.CrossDeviceService/ListMessages"
	CrossDeviceService_CreateAgentRun_FullMethodName              = "/astraflow.v1.CrossDeviceService/CreateAgentRun"
	CrossDeviceService_GetAgentRun_FullMethodName                 = "/astraflow.v1.CrossDeviceService/GetAgentRun"
	CrossDeviceService_ListAgentRuns_FullMethodName               = "/astraflow.v1.CrossDeviceService/ListAgentRuns"
	CrossDeviceService_CancelAgentRun_FullMethodName              = "/astraflow.v1.CrossDeviceService/CancelAgentRun"
	CrossDeviceService_AppendAgentRunEvents_FullMethodName        = "/astraflow.v1.CrossDeviceService/AppendAgentRunEvents"
	CrossDeviceService_ListAgentRunEvents_FullMethodName          = "/astraflow.v1.CrossDeviceService/ListAgentRunEvents"
	CrossDeviceService_ResolveAgentAction_FullMethodName          = "/astraflow.v1.CrossDeviceService/ResolveAgentAction"
	CrossDeviceService_ListAgentActions_FullMethodName            = "/astraflow.v1.CrossDeviceService/ListAgentActions"
	CrossDeviceService_PullSyncEvents_FullMethodName              = "/astraflow.v1.CrossDeviceService/PullSyncEvents"
	CrossDeviceService_GetSyncSnapshot_FullMethodName             = "/astraflow.v1.CrossDeviceService/GetSyncSnapshot"
	CrossDeviceService_ApplySyncMutations_FullMethodName          = "/astraflow.v1.CrossDeviceService/ApplySyncMutations"
)

// CrossDeviceServiceClient is the client API for CrossDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrossDeviceService is the durable control-plane contract shared by Desktop,
// mobile clients, device relays, and cloud Agent workers.
type CrossDeviceServiceClient interface {
	GetNativeOAuthConfig(ctx context.Context, in *GetNativeOAuthConfigRequest, opts ...grpc.CallOption) (*NativeOAuthConfig, error)
	ExchangeNativeOAuthCode(ctx context.Context, in *ExchangeNativeOAuthCodeRequest, opts ...grpc.CallOption) (*NativeOAuthTokens, error)
	RefreshNativeOAuthToken(ctx context.Context, in *RefreshNativeOAuthTokenRequest, opts ...grpc.CallOption) (*NativeOAuthTokens, error)
	GetCurrentAccount(ctx context.Context, in *GetCurrentAccountRequest, opts ...grpc.CallOption) (*Account, error)
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	CreateDeviceConnectionToken(ctx context.Context, in *CreateDeviceConnectionTokenRequest, opts ...grpc.CallOption) (*DeviceConnectionToken, error)
	UpsertPushEndpoint(ctx context.Context, in *UpsertPushEndpointRequest, opts ...grpc.CallOption) (*PushEndpoint, error)
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error)
	GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error)
	ListAgentRuns(ctx context.Context, in *ListAgentRunsRequest, opts ...grpc.CallOption) (*ListAgentRunsResponse, error)
	CancelAgentRun(ctx context.Context, in *CancelAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error)
	AppendAgentRunEvents(ctx context.Context, in *AppendAgentRunEventsRequest, opts ...grpc.CallOption) (*AppendAgentRunEventsResponse, error)
	ListAgentRunEvents(ctx context.Context, in *ListAgentRunEventsRequest, opts ...grpc.CallOption) (*ListAgentRunEventsResponse, error)
	ResolveAgentAction(ctx context.Context, in *ResolveAgentActionRequest, opts ...grpc.CallOption) (*AgentAction, error)
	ListAgentActions(ctx context.Context, in *ListAgentActionsRequest, opts ...grpc.CallOption) (*ListAgentActionsResponse, error)
	PullSyncEvents(ctx context.Context, in *PullSyncEventsRequest, opts ...grpc.CallOption) (*PullSyncEventsResponse, error)
	GetSyncSnapshot(ctx context.Context, in *GetSyncSnapshotRequest, opts ...grpc.CallOption) (*GetSyncSnapshotResponse, error)
	ApplySyncMutations(ctx context.Context, in *ApplySyncMutationsRequest, opts ...grpc.CallOption) (*ApplySyncMutationsResponse, error)
}

type crossDeviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrossDeviceServiceClient(cc grpc.ClientConnInterface) CrossDeviceServiceClient {
	return &crossDeviceServiceClient{cc}
}

func (c *crossDeviceServiceClient) GetNativeOAuthConfig(ctx context.Context, in *GetNativeOAuthConfigRequest, opts ...grpc.CallOption) (*NativeOAuthConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NativeOAuthConfig)
	err := c.cc.Invoke(ctx, CrossDeviceService_GetNativeOAuthConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ExchangeNativeOAuthCode(ctx context.Context, in *ExchangeNativeOAuthCodeRequest, opts ...grpc.CallOption) (*NativeOAuthTokens, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NativeOAuthTokens)
	err := c.cc.Invoke(ctx, CrossDeviceService_ExchangeNativeOAuthCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) RefreshNativeOAuthToken(ctx context.Context, in *RefreshNativeOAuthTokenRequest, opts ...grpc.CallOption) (*NativeOAuthTokens, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NativeOAuthTokens)
	err := c.cc.Invoke(ctx, CrossDeviceService_RefreshNativeOAuthToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) GetCurrentAccount(ctx context.Context, in *GetCurrentAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, CrossDeviceService_GetCurrentAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, CrossDeviceService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, CrossDeviceService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) CreateDeviceConnectionToken(ctx context.Context, in *CreateDeviceConnectionTokenRequest, opts ...grpc.CallOption) (*DeviceConnectionToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceConnectionToken)
	err := c.cc.Invoke(ctx, CrossDeviceService_CreateDeviceConnectionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) UpsertPushEndpoint(ctx context.Context, in *UpsertPushEndpointRequest, opts ...grpc.CallOption) (*PushEndpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushEndpoint)
	err := c.cc.Invoke(ctx, CrossDeviceService_UpsertPushEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, CrossDeviceService_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, CrossDeviceService_GetWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, CrossDeviceService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, CrossDeviceService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, CrossDeviceService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, CrossDeviceService_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRun)
	err := c.cc.Invoke(ctx, CrossDeviceService_CreateAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRun)
	err := c.cc.Invoke(ctx, CrossDeviceService_GetAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListAgentRuns(ctx context.Context, in *ListAgentRunsRequest, opts ...grpc.CallOption) (*ListAgentRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentRunsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListAgentRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) CancelAgentRun(ctx context.Context, in *CancelAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRun)
	err := c.cc.Invoke(ctx, CrossDeviceService_CancelAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) AppendAgentRunEvents(ctx context.Context, in *AppendAgentRunEventsRequest, opts ...grpc.CallOption) (*AppendAgentRunEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendAgentRunEventsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_AppendAgentRunEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListAgentRunEvents(ctx context.Context, in *ListAgentRunEventsRequest, opts ...grpc.CallOption) (*ListAgentRunEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentRunEventsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListAgentRunEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ResolveAgentAction(ctx context.Context, in *ResolveAgentActionRequest, opts ...grpc.CallOption) (*AgentAction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentAction)
	err := c.cc.Invoke(ctx, CrossDeviceService_ResolveAgentAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ListAgentActions(ctx context.Context, in *ListAgentActionsRequest, opts ...grpc.CallOption) (*ListAgentActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentActionsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ListAgentActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) PullSyncEvents(ctx context.Context, in *PullSyncEventsRequest, opts ...grpc.CallOption) (*PullSyncEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullSyncEventsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_PullSyncEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) GetSyncSnapshot(ctx context.Context, in *GetSyncSnapshotRequest, opts ...grpc.CallOption) (*GetSyncSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncSnapshotResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_GetSyncSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDeviceServiceClient) ApplySyncMutations(ctx context.Context, in *ApplySyncMutationsRequest, opts ...grpc.CallOption) (*ApplySyncMutationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySyncMutationsResponse)
	err := c.cc.Invoke(ctx, CrossDeviceService_ApplySyncMutations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrossDeviceServiceServer is the server API for CrossDeviceService service.
// All implementations must embed UnimplementedCrossDeviceServiceServer
// for forward compatibility.
//
// CrossDeviceService is the durable control-plane contract shared by Desktop,
// mobile clients, device relays, and cloud Agent workers.
type CrossDeviceServiceServer interface {
	GetNativeOAuthConfig(context.Context, *GetNativeOAuthConfigRequest) (*NativeOAuthConfig, error)
	ExchangeNativeOAuthCode(context.Context, *ExchangeNativeOAuthCodeRequest) (*NativeOAuthTokens, error)
	RefreshNativeOAuthToken(context.Context, *RefreshNativeOAuthTokenRequest) (*NativeOAuthTokens, error)
	GetCurrentAccount(context.Context, *GetCurrentAccountRequest) (*Account, error)
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*Device, error)
	CreateDeviceConnectionToken(context.Context, *CreateDeviceConnectionTokenRequest) (*DeviceConnectionToken, error)
	UpsertPushEndpoint(context.Context, *UpsertPushEndpointRequest) (*PushEndpoint, error)
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	GetWorkspace(context.Context, *GetWorkspaceRequest) (*Workspace, error)
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	CreateAgentRun(context.Context, *CreateAgentRunRequest) (*AgentRun, error)
	GetAgentRun(context.Context, *GetAgentRunRequest) (*AgentRun, error)
	ListAgentRuns(context.Context, *ListAgentRunsRequest) (*ListAgentRunsResponse, error)
	CancelAgentRun(context.Context, *CancelAgentRunRequest) (*AgentRun, error)
	AppendAgentRunEvents(context.Context, *AppendAgentRunEventsRequest) (*AppendAgentRunEventsResponse, error)
	ListAgentRunEvents(context.Context, *ListAgentRunEventsRequest) (*ListAgentRunEventsResponse, error)
	ResolveAgentAction(context.Context, *ResolveAgentActionRequest) (*AgentAction, error)
	ListAgentActions(context.Context, *ListAgentActionsRequest) (*ListAgentActionsResponse, error)
	PullSyncEvents(context.Context, *PullSyncEventsRequest) (*PullSyncEventsResponse, error)
	GetSyncSnapshot(context.Context, *GetSyncSnapshotRequest) (*GetSyncSnapshotResponse, error)
	ApplySyncMutations(context.Context, *ApplySyncMutationsRequest) (*ApplySyncMutationsResponse, error)
	mustEmbedUnimplementedCrossDeviceServiceServer()
}

// UnimplementedCrossDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrossDeviceServiceServer struct{}

func (UnimplementedCrossDeviceServiceServer) GetNativeOAuthConfig(context.Context, *GetNativeOAuthConfigRequest) (*NativeOAuthConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNativeOAuthConfig not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ExchangeNativeOAuthCode(context.Context, *ExchangeNativeOAuthCodeRequest) (*NativeOAuthTokens, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeNativeOAuthCode not implemented")
}
func (UnimplementedCrossDeviceServiceServer) RefreshNativeOAuthToken(context.Context, *RefreshNativeOAuthTokenRequest) (*NativeOAuthTokens, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshNativeOAuthToken not implemented")
}
func (UnimplementedCrossDeviceServiceServer) GetCurrentAccount(context.Context, *GetCurrentAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentAccount not implemented")
}
func (UnimplementedCrossDeviceServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedCrossDeviceServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*Device, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedCrossDeviceServiceServer) CreateDeviceConnectionToken(context.Context, *CreateDeviceConnectionTokenRequest) (*DeviceConnectionToken, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeviceConnectionToken not implemented")
}
func (UnimplementedCrossDeviceServiceServer) UpsertPushEndpoint(context.Context, *UpsertPushEndpointRequest) (*PushEndpoint, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPushEndpoint not implemented")
}
func (UnimplementedCrossDeviceServiceServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedCrossDeviceServiceServer) GetWorkspace(context.Context, *GetWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedCrossDeviceServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedCrossDeviceServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedCrossDeviceServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedCrossDeviceServiceServer) CreateMessage(context.Context, *CreateMessageRequest) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedCrossDeviceServiceServer) CreateAgentRun(context.Context, *CreateAgentRunRequest) (*AgentRun, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentRun not implemented")
}
func (UnimplementedCrossDeviceServiceServer) GetAgentRun(context.Context, *GetAgentRunRequest) (*AgentRun, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentRun not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListAgentRuns(context.Context, *ListAgentRunsRequest) (*ListAgentRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentRuns not implemented")
}
func (UnimplementedCrossDeviceServiceServer) CancelAgentRun(context.Context, *CancelAgentRunRequest) (*AgentRun, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAgentRun not implemented")
}
func (UnimplementedCrossDeviceServiceServer) AppendAgentRunEvents(context.Context, *AppendAgentRunEventsRequest) (*AppendAgentRunEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendAgentRunEvents not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListAgentRunEvents(context.Context, *ListAgentRunEventsRequest) (*ListAgentRunEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentRunEvents not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ResolveAgentAction(context.Context, *ResolveAgentActionRequest) (*AgentAction, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAgentAction not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ListAgentActions(context.Context, *ListAgentActionsRequest) (*ListAgentActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentActions not implemented")
}
func (UnimplementedCrossDeviceServiceServer) PullSyncEvents(context.Context, *PullSyncEventsRequest) (*PullSyncEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullSyncEvents not implemented")
}
func (UnimplementedCrossDeviceServiceServer) GetSyncSnapshot(context.Context, *GetSyncSnapshotRequest) (*GetSyncSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncSnapshot not implemented")
}
func (UnimplementedCrossDeviceServiceServer) ApplySyncMutations(context.Context, *ApplySyncMutationsRequest) (*ApplySyncMutationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySyncMutations not implemented")
}
func (UnimplementedCrossDeviceServiceServer) mustEmbedUnimplementedCrossDeviceServiceServer() {}
func (UnimplementedCrossDeviceServiceServer) testEmbeddedByValue()                            {}

// UnsafeCrossDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrossDeviceServiceServer will
// result in compilation errors.
type UnsafeCrossDeviceServiceServer interface {
	mustEmbedUnimplementedCrossDeviceServiceServer()
}

func RegisterCrossDeviceServiceServer(s grpc.ServiceRegistrar, srv CrossDeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedCrossDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrossDeviceService_ServiceDesc, srv)
}

func _CrossDeviceService_GetNativeOAuthConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNativeOAuthConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).GetNativeOAuthConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_GetNativeOAuthConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).GetNativeOAuthConfig(ctx, req.(*GetNativeOAuthConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ExchangeNativeOAuthCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeNativeOAuthCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ExchangeNativeOAuthCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ExchangeNativeOAuthCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ExchangeNativeOAuthCode(ctx, req.(*ExchangeNativeOAuthCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_RefreshNativeOAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshNativeOAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).RefreshNativeOAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_RefreshNativeOAuthToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).RefreshNativeOAuthToken(ctx, req.(*RefreshNativeOAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_GetCurrentAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).GetCurrentAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_GetCurrentAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).GetCurrentAccount(ctx, req.(*GetCurrentAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_CreateDeviceConnectionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceConnectionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).CreateDeviceConnectionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_CreateDeviceConnectionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).CreateDeviceConnectionToken(ctx, req.(*CreateDeviceConnectionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_UpsertPushEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPushEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).UpsertPushEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_UpsertPushEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).UpsertPushEndpoint(ctx, req.(*UpsertPushEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_GetWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).GetWorkspace(ctx, req.(*GetWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_CreateAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).CreateAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_CreateAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).CreateAgentRun(ctx, req.(*CreateAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_GetAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).GetAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_GetAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).GetAgentRun(ctx, req.(*GetAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListAgentRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListAgentRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListAgentRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListAgentRuns(ctx, req.(*ListAgentRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_CancelAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).CancelAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_CancelAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).CancelAgentRun(ctx, req.(*CancelAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_AppendAgentRunEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendAgentRunEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).AppendAgentRunEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_AppendAgentRunEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).AppendAgentRunEvents(ctx, req.(*AppendAgentRunEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListAgentRunEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentRunEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListAgentRunEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListAgentRunEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListAgentRunEvents(ctx, req.(*ListAgentRunEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ResolveAgentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAgentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ResolveAgentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ResolveAgentAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ResolveAgentAction(ctx, req.(*ResolveAgentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ListAgentActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ListAgentActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ListAgentActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ListAgentActions(ctx, req.(*ListAgentActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_PullSyncEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullSyncEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).PullSyncEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_PullSyncEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).PullSyncEvents(ctx, req.(*PullSyncEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_GetSyncSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).GetSyncSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_GetSyncSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).GetSyncSnapshot(ctx, req.(*GetSyncSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDeviceService_ApplySyncMutations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySyncMutationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDeviceServiceServer).ApplySyncMutations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDeviceService_ApplySyncMutations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDeviceServiceServer).ApplySyncMutations(ctx, req.(*ApplySyncMutationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrossDeviceService_ServiceDesc is the grpc.ServiceDesc for CrossDeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrossDeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.CrossDeviceService",
	HandlerType: (*CrossDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNativeOAuthConfig",
			Handler:    _CrossDeviceService_GetNativeOAuthConfig_Handler,
		},
		{
			MethodName: "ExchangeNativeOAuthCode",
			Handler:    _CrossDeviceService_ExchangeNativeOAuthCode_Handler,
		},
		{
			MethodName: "RefreshNativeOAuthToken",
			Handler:    _CrossDeviceService_RefreshNativeOAuthToken_Handler,
		},
		{
			MethodName: "GetCurrentAccount",
			Handler:    _CrossDeviceService_GetCurrentAccount_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _CrossDeviceService_RegisterDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _CrossDeviceService_ListDevices_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _CrossDeviceService_RevokeDevice_Handler,
		},
		{
			MethodName: "CreateDeviceConnectionToken",
			Handler:    _CrossDeviceService_CreateDeviceConnectionToken_Handler,
		},
		{
			MethodName: "UpsertPushEndpoint",
			Handler:    _CrossDeviceService_UpsertPushEndpoint_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _CrossDeviceService_CreateWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _CrossDeviceService_ListWorkspaces_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _CrossDeviceService_GetWorkspace_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _CrossDeviceService_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _CrossDeviceService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _CrossDeviceService_GetSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _CrossDeviceService_UpdateSession_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _CrossDeviceService_CreateMessage_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _CrossDeviceService_ListMessages_Handler,
		},
		{
			MethodName: "CreateAgentRun",
			Handler:    _CrossDeviceService_CreateAgentRun_Handler,
		},
		{
			MethodName: "GetAgentRun",
			Handler:    _CrossDeviceService_GetAgentRun_Handler,
		},
		{
			MethodName: "ListAgentRuns",
			Handler:    _CrossDeviceService_ListAgentRuns_Handler,
		},
		{
			MethodName: "CancelAgentRun",
			Handler:    _CrossDeviceService_CancelAgentRun_Handler,
		},
		{
			MethodName: "AppendAgentRunEvents",
			Handler:    _CrossDeviceService_AppendAgentRunEvents_Handler,
		},
		{
			MethodName: "ListAgentRunEvents",
			Handler:    _CrossDeviceService_ListAgentRunEvents_Handler,
		},
		{
			MethodName: "ResolveAgentAction",
			Handler:    _CrossDeviceService_ResolveAgentAction_Handler,
		},
		{
			MethodName: "ListAgentActions",
			Handler:    _CrossDeviceService_ListAgentActions_Handler,
		},
		{
			MethodName: "PullSyncEvents",
			Handler:    _CrossDeviceService_PullSyncEvents_Handler,
		},
		{
			MethodName: "GetSyncSnapshot",
			Handler:    _CrossDeviceService_GetSyncSnapshot_Handler,
		},
		{
			MethodName: "ApplySyncMutations",
			Handler:    _CrossDeviceService_ApplySyncMutations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/cross_device.proto",
}

const (
	ModelCatalogService_ListModels_FullMethodName = "/astraflow.v1.ModelCatalogService/ListModels"
)

// ModelCatalogServiceClient is the client API for ModelCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelCatalogService proxies the account-scoped UCloud model catalog without
// exposing OAuth tokens or introducing an AccessKey credential path.
type ModelCatalogServiceClient interface {
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type modelCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelCatalogServiceClient(cc grpc.ClientConnInterface) ModelCatalogServiceClient {
	return &modelCatalogServiceClient{cc}
}

func (c *modelCatalogServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelCatalogService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelCatalogServiceServer is the server API for ModelCatalogService service.
// All implementations must embed UnimplementedModelCatalogServiceServer
// for forward compatibility.
//
// ModelCatalogService proxies the account-scoped UCloud model catalog without
// exposing OAuth tokens or introducing an AccessKey credential path.
type ModelCatalogServiceServer interface {
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedModelCatalogServiceServer()
}

// UnimplementedModelCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelCatalogServiceServer struct{}

func (UnimplementedModelCatalogServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelCatalogServiceServer) mustEmbedUnimplementedModelCatalogServiceServer() {}
func (UnimplementedModelCatalogServiceServer) testEmbeddedByValue()                             {}

// UnsafeModelCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelCatalogServiceServer will
// result in compilation errors.
type UnsafeModelCatalogServiceServer interface {
	mustEmbedUnimplementedModelCatalogServiceServer()
}

func RegisterModelCatalogServiceServer(s grpc.ServiceRegistrar, srv ModelCatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedModelCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelCatalogService_ServiceDesc, srv)
}

func _ModelCatalogService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelCatalogService_ServiceDesc is the grpc.ServiceDesc for ModelCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.ModelCatalogService",
	HandlerType: (*ModelCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _ModelCatalogService_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/cross_device.proto",
}

const (
	ArtifactService_CreateUpload_FullMethodName        = "/astraflow.v1.ArtifactService/CreateUpload"
	ArtifactService_CompleteUpload_FullMethodName      = "/astraflow.v1.ArtifactService/CompleteUpload"
	ArtifactService_ListArtifacts_FullMethodName       = "/astraflow.v1.ArtifactService/ListArtifacts"
	ArtifactService_GetArtifact_FullMethodName         = "/astraflow.v1.ArtifactService/GetArtifact"
	ArtifactService_CreateArtifactShare_FullMethodName = "/astraflow.v1.ArtifactService/CreateArtifactShare"
	ArtifactService_RevokeArtifactShare_FullMethodName = "/astraflow.v1.ArtifactService/RevokeArtifactShare"
	ArtifactService_GetSharedArtifact_FullMethodName   = "/astraflow.v1.ArtifactService/GetSharedArtifact"
)

// ArtifactServiceClient is the client API for ArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactServiceClient interface {
	CreateUpload(ctx context.Context, in *CreateArtifactUploadRequest, opts ...grpc.CallOption) (*ArtifactUpload, error)
	CompleteUpload(ctx context.Context, in *CompleteArtifactUploadRequest, opts ...grpc.CallOption) (*Artifact, error)
	ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error)
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*Artifact, error)
	CreateArtifactShare(ctx context.Context, in *CreateArtifactShareRequest, opts ...grpc.CallOption) (*ArtifactShare, error)
	RevokeArtifactShare(ctx context.Context, in *RevokeArtifactShareRequest, opts ...grpc.CallOption) (*ArtifactShare, error)
	GetSharedArtifact(ctx context.Context, in *GetSharedArtifactRequest, opts ...grpc.CallOption) (*Artifact, error)
}

type artifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactServiceClient(cc grpc.ClientConnInterface) ArtifactServiceClient {
	return &artifactServiceClient{cc}
}

func (c *artifactServiceClient) CreateUpload(ctx context.Context, in *CreateArtifactUploadRequest, opts ...grpc.CallOption) (*ArtifactUpload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactUpload)
	err := c.cc.Invoke(ctx, ArtifactService_CreateUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) CompleteUpload(ctx context.Context, in *CompleteArtifactUploadRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, ArtifactService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtifactsResponse)
	err := c.cc.Invoke(ctx, ArtifactService_ListArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, ArtifactService_GetArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) CreateArtifactShare(ctx context.Context, in *CreateArtifactShareRequest, opts ...grpc.CallOption) (*ArtifactShare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactShare)
	err := c.cc.Invoke(ctx, ArtifactService_CreateArtifactShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) RevokeArtifactShare(ctx context.Context, in *RevokeArtifactShareRequest, opts ...grpc.CallOption) (*ArtifactShare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactShare)
	err := c.cc.Invoke(ctx, ArtifactService_RevokeArtifactShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) GetSharedArtifact(ctx context.Context, in *GetSharedArtifactRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, ArtifactService_GetSharedArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactServiceServer is the server API for ArtifactService service.
// All implementations must embed UnimplementedArtifactServiceServer
// for forward compatibility.
type ArtifactServiceServer interface {
	CreateUpload(context.Context, *CreateArtifactUploadRequest) (*ArtifactUpload, error)
	CompleteUpload(context.Context, *CompleteArtifactUploadRequest) (*Artifact, error)
	ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*Artifact, error)
	CreateArtifactShare(context.Context, *CreateArtifactShareRequest) (*ArtifactShare, error)
	RevokeArtifactShare(context.Context, *RevokeArtifactShareRequest) (*ArtifactShare, error)
	GetSharedArtifact(context.Context, *GetSharedArtifactRequest) (*Artifact, error)
	mustEmbedUnimplementedArtifactServiceServer()
}

// UnimplementedArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactServiceServer struct{}

func (UnimplementedArtifactServiceServer) CreateUpload(context.Context, *CreateArtifactUploadRequest) (*ArtifactUpload, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUpload not implemented")
}
func (UnimplementedArtifactServiceServer) CompleteUpload(context.Context, *CompleteArtifactUploadRequest) (*Artifact, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedArtifactServiceServer) ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtifacts not implemented")
}
func (UnimplementedArtifactServiceServer) GetArtifact(context.Context, *GetArtifactRequest) (*Artifact, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) CreateArtifactShare(context.Context, *CreateArtifactShareRequest) (*ArtifactShare, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArtifactShare not implemented")
}
func (UnimplementedArtifactServiceServer) RevokeArtifactShare(context.Context, *RevokeArtifactShareRequest) (*ArtifactShare, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeArtifactShare not implemented")
}
func (UnimplementedArtifactServiceServer) GetSharedArtifact(context.Context, *GetSharedArtifactRequest) (*Artifact, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSharedArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) mustEmbedUnimplementedArtifactServiceServer() {}
func (UnimplementedArtifactServiceServer) testEmbeddedByValue()                         {}

// UnsafeArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactServiceServer will
// result in compilation errors.
type UnsafeArtifactServiceServer interface {
	mustEmbedUnimplementedArtifactServiceServer()
}

func RegisterArtifactServiceServer(s grpc.ServiceRegistrar, srv ArtifactServiceServer) {
	// If the following call panics, it indicates UnimplementedArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactService_ServiceDesc, srv)
}

func _ArtifactService_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_CreateUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).CreateUpload(ctx, req.(*CreateArtifactUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteArtifactUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).CompleteUpload(ctx, req.(*CompleteArtifactUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_ListArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).ListArtifacts(ctx, req.(*ListArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_GetArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_CreateArtifactShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).CreateArtifactShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_CreateArtifactShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).CreateArtifactShare(ctx, req.(*CreateArtifactShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_RevokeArtifactShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeArtifactShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).RevokeArtifactShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_RevokeArtifactShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).RevokeArtifactShare(ctx, req.(*RevokeArtifactShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_GetSharedArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharedArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).GetSharedArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_GetSharedArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).GetSharedArtifact(ctx, req.(*GetSharedArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactService_ServiceDesc is the grpc.ServiceDesc for ArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.ArtifactService",
	HandlerType: (*ArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUpload",
			Handler:    _ArtifactService_CreateUpload_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _ArtifactService_CompleteUpload_Handler,
		},
		{
			MethodName: "ListArtifacts",
			Handler:    _ArtifactService_ListArtifacts_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _ArtifactService_GetArtifact_Handler,
		},
		{
			MethodName: "CreateArtifactShare",
			Handler:    _ArtifactService_CreateArtifactShare_Handler,
		},
		{
			MethodName: "RevokeArtifactShare",
			Handler:    _ArtifactService_RevokeArtifactShare_Handler,
		},
		{
			MethodName: "GetSharedArtifact",
			Handler:    _ArtifactService_GetSharedArtifact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/cross_device.proto",
}

const (
	AutomationService_ListAutomations_FullMethodName      = "/astraflow.v1.AutomationService/ListAutomations"
	AutomationService_CreateAutomation_FullMethodName     = "/astraflow.v1.AutomationService/CreateAutomation"
	AutomationService_SetAutomationEnabled_FullMethodName = "/astraflow.v1.AutomationService/SetAutomationEnabled"
)

// AutomationServiceClient is the client API for AutomationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationServiceClient interface {
	ListAutomations(ctx context.Context, in *ListAutomationsRequest, opts ...grpc.CallOption) (*ListAutomationsResponse, error)
	CreateAutomation(ctx context.Context, in *CreateAutomationRequest, opts ...grpc.CallOption) (*CloudAutomation, error)
	SetAutomationEnabled(ctx context.Context, in *SetAutomationEnabledRequest, opts ...grpc.CallOption) (*CloudAutomation, error)
}

type automationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationServiceClient(cc grpc.ClientConnInterface) AutomationServiceClient {
	return &automationServiceClient{cc}
}

func (c *automationServiceClient) ListAutomations(ctx context.Context, in *ListAutomationsRequest, opts ...grpc.CallOption) (*ListAutomationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAutomationsResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListAutomations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) CreateAutomation(ctx context.Context, in *CreateAutomationRequest, opts ...grpc.CallOption) (*CloudAutomation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudAutomation)
	err := c.cc.Invoke(ctx, AutomationService_CreateAutomation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) SetAutomationEnabled(ctx context.Context, in *SetAutomationEnabledRequest, opts ...grpc.CallOption) (*CloudAutomation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudAutomation)
	err := c.cc.Invoke(ctx, AutomationService_SetAutomationEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationServiceServer is the server API for AutomationService service.
// All implementations must embed UnimplementedAutomationServiceServer
// for forward compatibility.
type AutomationServiceServer interface {
	ListAutomations(context.Context, *ListAutomationsRequest) (*ListAutomationsResponse, error)
	CreateAutomation(context.Context, *CreateAutomationRequest) (*CloudAutomation, error)
	SetAutomationEnabled(context.Context, *SetAutomationEnabledRequest) (*CloudAutomation, error)
	mustEmbedUnimplementedAutomationServiceServer()
}

// UnimplementedAutomationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationServiceServer struct{}

func (UnimplementedAutomationServiceServer) ListAutomations(context.Context, *ListAutomationsRequest) (*ListAutomationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAutomations not implemented")
}
func (UnimplementedAutomationServiceServer) CreateAutomation(context.Context, *CreateAutomationRequest) (*CloudAutomation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAutomation not implemented")
}
func (UnimplementedAutomationServiceServer) SetAutomationEnabled(context.Context, *SetAutomationEnabledRequest) (*CloudAutomation, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAutomationEnabled not implemented")
}
func (UnimplementedAutomationServiceServer) mustEmbedUnimplementedAutomationServiceServer() {}
func (UnimplementedAutomationServiceServer) testEmbeddedByValue()                           {}

// UnsafeAutomationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationServiceServer will
// result in compilation errors.
type UnsafeAutomationServiceServer interface {
	mustEmbedUnimplementedAutomationServiceServer()
}

func RegisterAutomationServiceServer(s grpc.ServiceRegistrar, srv AutomationServiceServer) {
	// If the following call panics, it indicates UnimplementedAutomationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationService_ServiceDesc, srv)
}

func _AutomationService_ListAutomations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAutomationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListAutomations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListAutomations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListAutomations(ctx, req.(*ListAutomationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_CreateAutomation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAutomationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).CreateAutomation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_CreateAutomation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).CreateAutomation(ctx, req.(*CreateAutomationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_SetAutomationEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutomationEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).SetAutomationEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_SetAutomationEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).SetAutomationEnabled(ctx, req.(*SetAutomationEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationService_ServiceDesc is the grpc.ServiceDesc for AutomationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.AutomationService",
	HandlerType: (*AutomationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAutomations",
			Handler:    _AutomationService_ListAutomations_Handler,
		},
		{
			MethodName: "CreateAutomation",
			Handler:    _AutomationService_CreateAutomation_Handler,
		},
		{
			MethodName: "SetAutomationEnabled",
			Handler:    _AutomationService_SetAutomationEnabled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/cross_device.proto",
}

const (
	CloudWorkerService_ClaimWorkspace_FullMethodName            = "/astraflow.v1.CloudWorkerService/ClaimWorkspace"
	CloudWorkerService_CompleteWorkspace_FullMethodName         = "/astraflow.v1.CloudWorkerService/CompleteWorkspace"
	CloudWorkerService_ClaimRun_FullMethodName                  = "/astraflow.v1.CloudWorkerService/ClaimRun"
	CloudWorkerService_RenewRun_FullMethodName                  = "/astraflow.v1.CloudWorkerService/RenewRun"
	CloudWorkerService_AppendRunEvents_FullMethodName           = "/astraflow.v1.CloudWorkerService/AppendRunEvents"
	CloudWorkerService_CreateRunArtifactUpload_FullMethodName   = "/astraflow.v1.CloudWorkerService/CreateRunArtifactUpload"
	CloudWorkerService_CompleteRunArtifactUpload_FullMethodName = "/astraflow.v1.CloudWorkerService/CompleteRunArtifactUpload"
)

// CloudWorkerServiceClient is the client API for CloudWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CloudWorkerService is an operator-only lease API. It uses the dedicated
// cloud-worker bearer token rather than end-user OAuth credentials.
type CloudWorkerServiceClient interface {
	ClaimWorkspace(ctx context.Context, in *ClaimCloudWorkspaceRequest, opts ...grpc.CallOption) (*CloudWorkspaceLease, error)
	CompleteWorkspace(ctx context.Context, in *CompleteCloudWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	ClaimRun(ctx context.Context, in *ClaimCloudRunRequest, opts ...grpc.CallOption) (*CloudRunLease, error)
	RenewRun(ctx context.Context, in *RenewCloudRunRequest, opts ...grpc.CallOption) (*CloudRunLeaseState, error)
	AppendRunEvents(ctx context.Context, in *AppendCloudRunEventsRequest, opts ...grpc.CallOption) (*AppendAgentRunEventsResponse, error)
	CreateRunArtifactUpload(ctx context.Context, in *CreateCloudRunArtifactUploadRequest, opts ...grpc.CallOption) (*ArtifactUpload, error)
	CompleteRunArtifactUpload(ctx context.Context, in *CompleteCloudRunArtifactUploadRequest, opts ...grpc.CallOption) (*Artifact, error)
}

type cloudWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudWorkerServiceClient(cc grpc.ClientConnInterface) CloudWorkerServiceClient {
	return &cloudWorkerServiceClient{cc}
}

func (c *cloudWorkerServiceClient) ClaimWorkspace(ctx context.Context, in *ClaimCloudWorkspaceRequest, opts ...grpc.CallOption) (*CloudWorkspaceLease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudWorkspaceLease)
	err := c.cc.Invoke(ctx, CloudWorkerService_ClaimWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWorkerServiceClient) CompleteWorkspace(ctx context.Context, in *CompleteCloudWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, CloudWorkerService_CompleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWorkerServiceClient) ClaimRun(ctx context.Context, in *ClaimCloudRunRequest, opts ...grpc.CallOption) (*CloudRunLease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudRunLease)
	err := c.cc.Invoke(ctx, CloudWorkerService_ClaimRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWorkerServiceClient) RenewRun(ctx context.Context, in *RenewCloudRunRequest, opts ...grpc.CallOption) (*CloudRunLeaseState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudRunLeaseState)
	err := c.cc.Invoke(ctx, CloudWorkerService_RenewRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWorkerServiceClient) AppendRunEvents(ctx context.Context, in *AppendCloudRunEventsRequest, opts ...grpc.CallOption) (*AppendAgentRunEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendAgentRunEventsResponse)
	err := c.cc.Invoke(ctx, CloudWorkerService_AppendRunEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWorkerServiceClient) CreateRunArtifactUpload(ctx context.Context, in *CreateCloudRunArtifactUploadRequest, opts ...grpc.CallOption) (*ArtifactUpload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactUpload)
	err := c.cc.Invoke(ctx, CloudWorkerService_CreateRunArtifactUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWorkerServiceClient) CompleteRunArtifactUpload(ctx context.Context, in *CompleteCloudRunArtifactUploadRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, CloudWorkerService_CompleteRunArtifactUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudWorkerServiceServer is the server API for CloudWorkerService service.
// All implementations must embed UnimplementedCloudWorkerServiceServer
// for forward compatibility.
//
// CloudWorkerService is an operator-only lease API. It uses the dedicated
// cloud-worker bearer token rather than end-user OAuth credentials.
type CloudWorkerServiceServer interface {
	ClaimWorkspace(context.Context, *ClaimCloudWorkspaceRequest) (*CloudWorkspaceLease, error)
	CompleteWorkspace(context.Context, *CompleteCloudWorkspaceRequest) (*Workspace, error)
	ClaimRun(context.Context, *ClaimCloudRunRequest) (*CloudRunLease, error)
	RenewRun(context.Context, *RenewCloudRunRequest) (*CloudRunLeaseState, error)
	AppendRunEvents(context.Context, *AppendCloudRunEventsRequest) (*AppendAgentRunEventsResponse, error)
	CreateRunArtifactUpload(context.Context, *CreateCloudRunArtifactUploadRequest) (*ArtifactUpload, error)
	CompleteRunArtifactUpload(context.Context, *CompleteCloudRunArtifactUploadRequest) (*Artifact, error)
	mustEmbedUnimplementedCloudWorkerServiceServer()
}

// UnimplementedCloudWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudWorkerServiceServer struct{}

func (UnimplementedCloudWorkerServiceServer) ClaimWorkspace(context.Context, *ClaimCloudWorkspaceRequest) (*CloudWorkspaceLease, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimWorkspace not implemented")
}
func (UnimplementedCloudWorkerServiceServer) CompleteWorkspace(context.Context, *CompleteCloudWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteWorkspace not implemented")
}
func (UnimplementedCloudWorkerServiceServer) ClaimRun(context.Context, *ClaimCloudRunRequest) (*CloudRunLease, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimRun not implemented")
}
func (UnimplementedCloudWorkerServiceServer) RenewRun(context.Context, *RenewCloudRunRequest) (*CloudRunLeaseState, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewRun not implemented")
}
func (UnimplementedCloudWorkerServiceServer) AppendRunEvents(context.Context, *AppendCloudRunEventsRequest) (*AppendAgentRunEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendRunEvents not implemented")
}
func (UnimplementedCloudWorkerServiceServer) CreateRunArtifactUpload(context.Context, *CreateCloudRunArtifactUploadRequest) (*ArtifactUpload, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRunArtifactUpload not implemented")
}
func (UnimplementedCloudWorkerServiceServer) CompleteRunArtifactUpload(context.Context, *CompleteCloudRunArtifactUploadRequest) (*Artifact, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteRunArtifactUpload not implemented")
}
func (UnimplementedCloudWorkerServiceServer) mustEmbedUnimplementedCloudWorkerServiceServer() {}
func (UnimplementedCloudWorkerServiceServer) testEmbeddedByValue()                            {}

// UnsafeCloudWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudWorkerServiceServer will
// result in compilation errors.
type UnsafeCloudWorkerServiceServer interface {
	mustEmbedUnimplementedCloudWorkerServiceServer()
}

func RegisterCloudWorkerServiceServer(s grpc.ServiceRegistrar, srv CloudWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudWorkerService_ServiceDesc, srv)
}

func _CloudWorkerService_ClaimWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCloudWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).ClaimWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_ClaimWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).ClaimWorkspace(ctx, req.(*ClaimCloudWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWorkerService_CompleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteCloudWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).CompleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_CompleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).CompleteWorkspace(ctx, req.(*CompleteCloudWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWorkerService_ClaimRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCloudRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).ClaimRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_ClaimRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).ClaimRun(ctx, req.(*ClaimCloudRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWorkerService_RenewRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCloudRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).RenewRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_RenewRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).RenewRun(ctx, req.(*RenewCloudRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWorkerService_AppendRunEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendCloudRunEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).AppendRunEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_AppendRunEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).AppendRunEvents(ctx, req.(*AppendCloudRunEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWorkerService_CreateRunArtifactUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCloudRunArtifactUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).CreateRunArtifactUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_CreateRunArtifactUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).CreateRunArtifactUpload(ctx, req.(*CreateCloudRunArtifactUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWorkerService_CompleteRunArtifactUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteCloudRunArtifactUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWorkerServiceServer).CompleteRunArtifactUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWorkerService_CompleteRunArtifactUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWorkerServiceServer).CompleteRunArtifactUpload(ctx, req.(*CompleteCloudRunArtifactUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudWorkerService_ServiceDesc is the grpc.ServiceDesc for CloudWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.CloudWorkerService",
	HandlerType: (*CloudWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimWorkspace",
			Handler:    _CloudWorkerService_ClaimWorkspace_Handler,
		},
		{
			MethodName: "CompleteWorkspace",
			Handler:    _CloudWorkerService_CompleteWorkspace_Handler,
		},
		{
			MethodName: "ClaimRun",
			Handler:    _CloudWorkerService_ClaimRun_Handler,
		},
		{
			MethodName: "RenewRun",
			Handler:    _CloudWorkerService_RenewRun_Handler,
		},
		{
			MethodName: "AppendRunEvents",
			Handler:    _CloudWorkerService_AppendRunEvents_Handler,
		},
		{
			MethodName: "CreateRunArtifactUpload",
			Handler:    _CloudWorkerService_CreateRunArtifactUpload_Handler,
		},
		{
			MethodName: "CompleteRunArtifactUpload",
			Handler:    _CloudWorkerService_CompleteRunArtifactUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/cross_device.proto",
}
