// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: astraflow/v1/cross_device.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCrossDeviceServiceAppendAgentRunEvents = "/astraflow.v1.CrossDeviceService/AppendAgentRunEvents"
const OperationCrossDeviceServiceApplySyncMutations = "/astraflow.v1.CrossDeviceService/ApplySyncMutations"
const OperationCrossDeviceServiceCancelAgentRun = "/astraflow.v1.CrossDeviceService/CancelAgentRun"
const OperationCrossDeviceServiceCreateAgentRun = "/astraflow.v1.CrossDeviceService/CreateAgentRun"
const OperationCrossDeviceServiceCreateDeviceConnectionToken = "/astraflow.v1.CrossDeviceService/CreateDeviceConnectionToken"
const OperationCrossDeviceServiceCreateMessage = "/astraflow.v1.CrossDeviceService/CreateMessage"
const OperationCrossDeviceServiceCreateSession = "/astraflow.v1.CrossDeviceService/CreateSession"
const OperationCrossDeviceServiceCreateWorkspace = "/astraflow.v1.CrossDeviceService/CreateWorkspace"
const OperationCrossDeviceServiceExchangeNativeOAuthCode = "/astraflow.v1.CrossDeviceService/ExchangeNativeOAuthCode"
const OperationCrossDeviceServiceGetAgentRun = "/astraflow.v1.CrossDeviceService/GetAgentRun"
const OperationCrossDeviceServiceGetCurrentAccount = "/astraflow.v1.CrossDeviceService/GetCurrentAccount"
const OperationCrossDeviceServiceGetNativeOAuthConfig = "/astraflow.v1.CrossDeviceService/GetNativeOAuthConfig"
const OperationCrossDeviceServiceGetSession = "/astraflow.v1.CrossDeviceService/GetSession"
const OperationCrossDeviceServiceGetSyncSnapshot = "/astraflow.v1.CrossDeviceService/GetSyncSnapshot"
const OperationCrossDeviceServiceGetWorkspace = "/astraflow.v1.CrossDeviceService/GetWorkspace"
const OperationCrossDeviceServiceListAgentActions = "/astraflow.v1.CrossDeviceService/ListAgentActions"
const OperationCrossDeviceServiceListAgentRunEvents = "/astraflow.v1.CrossDeviceService/ListAgentRunEvents"
const OperationCrossDeviceServiceListAgentRuns = "/astraflow.v1.CrossDeviceService/ListAgentRuns"
const OperationCrossDeviceServiceListDevices = "/astraflow.v1.CrossDeviceService/ListDevices"
const OperationCrossDeviceServiceListMessages = "/astraflow.v1.CrossDeviceService/ListMessages"
const OperationCrossDeviceServiceListSessions = "/astraflow.v1.CrossDeviceService/ListSessions"
const OperationCrossDeviceServiceListWorkspaces = "/astraflow.v1.CrossDeviceService/ListWorkspaces"
const OperationCrossDeviceServicePullSyncEvents = "/astraflow.v1.CrossDeviceService/PullSyncEvents"
const OperationCrossDeviceServiceRefreshNativeOAuthToken = "/astraflow.v1.CrossDeviceService/RefreshNativeOAuthToken"
const OperationCrossDeviceServiceRegisterDevice = "/astraflow.v1.CrossDeviceService/RegisterDevice"
const OperationCrossDeviceServiceResolveAgentAction = "/astraflow.v1.CrossDeviceService/ResolveAgentAction"
const OperationCrossDeviceServiceRevokeDevice = "/astraflow.v1.CrossDeviceService/RevokeDevice"
const OperationCrossDeviceServiceUpdateSession = "/astraflow.v1.CrossDeviceService/UpdateSession"
const OperationCrossDeviceServiceUpsertPushEndpoint = "/astraflow.v1.CrossDeviceService/UpsertPushEndpoint"

type CrossDeviceServiceHTTPServer interface {
	AppendAgentRunEvents(context.Context, *AppendAgentRunEventsRequest) (*AppendAgentRunEventsResponse, error)
	ApplySyncMutations(context.Context, *ApplySyncMutationsRequest) (*ApplySyncMutationsResponse, error)
	CancelAgentRun(context.Context, *CancelAgentRunRequest) (*AgentRun, error)
	CreateAgentRun(context.Context, *CreateAgentRunRequest) (*AgentRun, error)
	CreateDeviceConnectionToken(context.Context, *CreateDeviceConnectionTokenRequest) (*DeviceConnectionToken, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error)
	ExchangeNativeOAuthCode(context.Context, *ExchangeNativeOAuthCodeRequest) (*NativeOAuthTokens, error)
	GetAgentRun(context.Context, *GetAgentRunRequest) (*AgentRun, error)
	GetCurrentAccount(context.Context, *GetCurrentAccountRequest) (*Account, error)
	GetNativeOAuthConfig(context.Context, *GetNativeOAuthConfigRequest) (*NativeOAuthConfig, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	GetSyncSnapshot(context.Context, *GetSyncSnapshotRequest) (*GetSyncSnapshotResponse, error)
	GetWorkspace(context.Context, *GetWorkspaceRequest) (*Workspace, error)
	ListAgentActions(context.Context, *ListAgentActionsRequest) (*ListAgentActionsResponse, error)
	ListAgentRunEvents(context.Context, *ListAgentRunEventsRequest) (*ListAgentRunEventsResponse, error)
	ListAgentRuns(context.Context, *ListAgentRunsRequest) (*ListAgentRunsResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	PullSyncEvents(context.Context, *PullSyncEventsRequest) (*PullSyncEventsResponse, error)
	RefreshNativeOAuthToken(context.Context, *RefreshNativeOAuthTokenRequest) (*NativeOAuthTokens, error)
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error)
	ResolveAgentAction(context.Context, *ResolveAgentActionRequest) (*AgentAction, error)
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*Device, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error)
	UpsertPushEndpoint(context.Context, *UpsertPushEndpointRequest) (*PushEndpoint, error)
}

func RegisterCrossDeviceServiceHTTPServer(s *http.Server, srv CrossDeviceServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/auth/native/config", _CrossDeviceService_GetNativeOAuthConfig0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/native/exchange", _CrossDeviceService_ExchangeNativeOAuthCode0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/native/refresh", _CrossDeviceService_RefreshNativeOAuthToken0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/account", _CrossDeviceService_GetCurrentAccount0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/devices", _CrossDeviceService_RegisterDevice0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/devices", _CrossDeviceService_ListDevices0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/devices/{device_id}:revoke", _CrossDeviceService_RevokeDevice0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/devices/{device_id}/connection-token", _CrossDeviceService_CreateDeviceConnectionToken0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/push-endpoints", _CrossDeviceService_UpsertPushEndpoint0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/workspaces", _CrossDeviceService_CreateWorkspace0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/workspaces", _CrossDeviceService_ListWorkspaces0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/workspaces/{workspace_id}", _CrossDeviceService_GetWorkspace0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/sessions", _CrossDeviceService_CreateSession0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sessions", _CrossDeviceService_ListSessions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sessions/{session_id}", _CrossDeviceService_GetSession0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/sessions/{session_id}", _CrossDeviceService_UpdateSession0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/sessions/{session_id}/messages", _CrossDeviceService_CreateMessage0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sessions/{session_id}/messages", _CrossDeviceService_ListMessages0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/agent-runs", _CrossDeviceService_CreateAgentRun0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/agent-runs/{run_id}", _CrossDeviceService_GetAgentRun0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/agent-runs", _CrossDeviceService_ListAgentRuns0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/agent-runs/{run_id}:cancel", _CrossDeviceService_CancelAgentRun0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/agent-runs/{run_id}/events:batch", _CrossDeviceService_AppendAgentRunEvents0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/agent-runs/{run_id}/events", _CrossDeviceService_ListAgentRunEvents0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/agent-runs/{run_id}/actions/{action_id}:resolve", _CrossDeviceService_ResolveAgentAction0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/agent-runs/{run_id}/actions", _CrossDeviceService_ListAgentActions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sync/events", _CrossDeviceService_PullSyncEvents0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sync/snapshot", _CrossDeviceService_GetSyncSnapshot0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/sync/mutations:batch", _CrossDeviceService_ApplySyncMutations0_HTTP_Handler(srv))
}

func _CrossDeviceService_GetNativeOAuthConfig0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNativeOAuthConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceGetNativeOAuthConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNativeOAuthConfig(ctx, req.(*GetNativeOAuthConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NativeOAuthConfig)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ExchangeNativeOAuthCode0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExchangeNativeOAuthCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceExchangeNativeOAuthCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExchangeNativeOAuthCode(ctx, req.(*ExchangeNativeOAuthCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NativeOAuthTokens)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_RefreshNativeOAuthToken0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshNativeOAuthTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceRefreshNativeOAuthToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshNativeOAuthToken(ctx, req.(*RefreshNativeOAuthTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NativeOAuthTokens)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_GetCurrentAccount0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceGetCurrentAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentAccount(ctx, req.(*GetCurrentAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_RegisterDevice0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterDeviceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceRegisterDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterDevice(ctx, req.(*RegisterDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Device)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListDevices0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDevicesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListDevices)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDevices(ctx, req.(*ListDevicesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDevicesResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_RevokeDevice0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeDeviceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceRevokeDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeDevice(ctx, req.(*RevokeDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Device)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_CreateDeviceConnectionToken0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDeviceConnectionTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceCreateDeviceConnectionToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDeviceConnectionToken(ctx, req.(*CreateDeviceConnectionTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeviceConnectionToken)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_UpsertPushEndpoint0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertPushEndpointRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceUpsertPushEndpoint)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertPushEndpoint(ctx, req.(*UpsertPushEndpointRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PushEndpoint)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_CreateWorkspace0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWorkspaceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceCreateWorkspace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Workspace)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListWorkspaces0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListWorkspacesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListWorkspaces)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListWorkspacesResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_GetWorkspace0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWorkspaceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceGetWorkspace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWorkspace(ctx, req.(*GetWorkspaceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Workspace)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_CreateSession0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Session)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListSessions0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_GetSession0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceGetSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSession(ctx, req.(*GetSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Session)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_UpdateSession0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceUpdateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSession(ctx, req.(*UpdateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Session)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_CreateMessage0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceCreateMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMessage(ctx, req.(*CreateMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Message)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListMessages0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_CreateAgentRun0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAgentRunRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceCreateAgentRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAgentRun(ctx, req.(*CreateAgentRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentRun)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_GetAgentRun0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAgentRunRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceGetAgentRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAgentRun(ctx, req.(*GetAgentRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentRun)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListAgentRuns0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAgentRunsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListAgentRuns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgentRuns(ctx, req.(*ListAgentRunsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAgentRunsResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_CancelAgentRun0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelAgentRunRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceCancelAgentRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelAgentRun(ctx, req.(*CancelAgentRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentRun)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_AppendAgentRunEvents0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AppendAgentRunEventsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceAppendAgentRunEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AppendAgentRunEvents(ctx, req.(*AppendAgentRunEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppendAgentRunEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListAgentRunEvents0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAgentRunEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListAgentRunEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgentRunEvents(ctx, req.(*ListAgentRunEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAgentRunEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ResolveAgentAction0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveAgentActionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceResolveAgentAction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveAgentAction(ctx, req.(*ResolveAgentActionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentAction)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ListAgentActions0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAgentActionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceListAgentActions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgentActions(ctx, req.(*ListAgentActionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAgentActionsResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_PullSyncEvents0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PullSyncEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServicePullSyncEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PullSyncEvents(ctx, req.(*PullSyncEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PullSyncEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_GetSyncSnapshot0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSyncSnapshotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceGetSyncSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSyncSnapshot(ctx, req.(*GetSyncSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSyncSnapshotResponse)
		return ctx.Result(200, reply)
	}
}

func _CrossDeviceService_ApplySyncMutations0_HTTP_Handler(srv CrossDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplySyncMutationsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCrossDeviceServiceApplySyncMutations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplySyncMutations(ctx, req.(*ApplySyncMutationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplySyncMutationsResponse)
		return ctx.Result(200, reply)
	}
}

type CrossDeviceServiceHTTPClient interface {
	AppendAgentRunEvents(ctx context.Context, req *AppendAgentRunEventsRequest, opts ...http.CallOption) (rsp *AppendAgentRunEventsResponse, err error)
	ApplySyncMutations(ctx context.Context, req *ApplySyncMutationsRequest, opts ...http.CallOption) (rsp *ApplySyncMutationsResponse, err error)
	CancelAgentRun(ctx context.Context, req *CancelAgentRunRequest, opts ...http.CallOption) (rsp *AgentRun, err error)
	CreateAgentRun(ctx context.Context, req *CreateAgentRunRequest, opts ...http.CallOption) (rsp *AgentRun, err error)
	CreateDeviceConnectionToken(ctx context.Context, req *CreateDeviceConnectionTokenRequest, opts ...http.CallOption) (rsp *DeviceConnectionToken, err error)
	CreateMessage(ctx context.Context, req *CreateMessageRequest, opts ...http.CallOption) (rsp *Message, err error)
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...http.CallOption) (rsp *Session, err error)
	CreateWorkspace(ctx context.Context, req *CreateWorkspaceRequest, opts ...http.CallOption) (rsp *Workspace, err error)
	ExchangeNativeOAuthCode(ctx context.Context, req *ExchangeNativeOAuthCodeRequest, opts ...http.CallOption) (rsp *NativeOAuthTokens, err error)
	GetAgentRun(ctx context.Context, req *GetAgentRunRequest, opts ...http.CallOption) (rsp *AgentRun, err error)
	GetCurrentAccount(ctx context.Context, req *GetCurrentAccountRequest, opts ...http.CallOption) (rsp *Account, err error)
	GetNativeOAuthConfig(ctx context.Context, req *GetNativeOAuthConfigRequest, opts ...http.CallOption) (rsp *NativeOAuthConfig, err error)
	GetSession(ctx context.Context, req *GetSessionRequest, opts ...http.CallOption) (rsp *Session, err error)
	GetSyncSnapshot(ctx context.Context, req *GetSyncSnapshotRequest, opts ...http.CallOption) (rsp *GetSyncSnapshotResponse, err error)
	GetWorkspace(ctx context.Context, req *GetWorkspaceRequest, opts ...http.CallOption) (rsp *Workspace, err error)
	ListAgentActions(ctx context.Context, req *ListAgentActionsRequest, opts ...http.CallOption) (rsp *ListAgentActionsResponse, err error)
	ListAgentRunEvents(ctx context.Context, req *ListAgentRunEventsRequest, opts ...http.CallOption) (rsp *ListAgentRunEventsResponse, err error)
	ListAgentRuns(ctx context.Context, req *ListAgentRunsRequest, opts ...http.CallOption) (rsp *ListAgentRunsResponse, err error)
	ListDevices(ctx context.Context, req *ListDevicesRequest, opts ...http.CallOption) (rsp *ListDevicesResponse, err error)
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesResponse, err error)
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsResponse, err error)
	ListWorkspaces(ctx context.Context, req *ListWorkspacesRequest, opts ...http.CallOption) (rsp *ListWorkspacesResponse, err error)
	PullSyncEvents(ctx context.Context, req *PullSyncEventsRequest, opts ...http.CallOption) (rsp *PullSyncEventsResponse, err error)
	RefreshNativeOAuthToken(ctx context.Context, req *RefreshNativeOAuthTokenRequest, opts ...http.CallOption) (rsp *NativeOAuthTokens, err error)
	RegisterDevice(ctx context.Context, req *RegisterDeviceRequest, opts ...http.CallOption) (rsp *Device, err error)
	ResolveAgentAction(ctx context.Context, req *ResolveAgentActionRequest, opts ...http.CallOption) (rsp *AgentAction, err error)
	RevokeDevice(ctx context.Context, req *RevokeDeviceRequest, opts ...http.CallOption) (rsp *Device, err error)
	UpdateSession(ctx context.Context, req *UpdateSessionRequest, opts ...http.CallOption) (rsp *Session, err error)
	UpsertPushEndpoint(ctx context.Context, req *UpsertPushEndpointRequest, opts ...http.CallOption) (rsp *PushEndpoint, err error)
}

type CrossDeviceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCrossDeviceServiceHTTPClient(client *http.Client) CrossDeviceServiceHTTPClient {
	return &CrossDeviceServiceHTTPClientImpl{client}
}

func (c *CrossDeviceServiceHTTPClientImpl) AppendAgentRunEvents(ctx context.Context, in *AppendAgentRunEventsRequest, opts ...http.CallOption) (*AppendAgentRunEventsResponse, error) {
	var out AppendAgentRunEventsResponse
	pattern := "/v1/agent-runs/{run_id}/events:batch"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceAppendAgentRunEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ApplySyncMutations(ctx context.Context, in *ApplySyncMutationsRequest, opts ...http.CallOption) (*ApplySyncMutationsResponse, error) {
	var out ApplySyncMutationsResponse
	pattern := "/v1/sync/mutations:batch"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceApplySyncMutations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) CancelAgentRun(ctx context.Context, in *CancelAgentRunRequest, opts ...http.CallOption) (*AgentRun, error) {
	var out AgentRun
	pattern := "/v1/agent-runs/{run_id}:cancel"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceCancelAgentRun),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...http.CallOption) (*AgentRun, error) {
	var out AgentRun
	pattern := "/v1/agent-runs"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceCreateAgentRun),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) CreateDeviceConnectionToken(ctx context.Context, in *CreateDeviceConnectionTokenRequest, opts ...http.CallOption) (*DeviceConnectionToken, error) {
	var out DeviceConnectionToken
	pattern := "/v1/devices/{device_id}/connection-token"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceCreateDeviceConnectionToken),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...http.CallOption) (*Message, error) {
	var out Message
	pattern := "/v1/sessions/{session_id}/messages"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceCreateMessage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...http.CallOption) (*Session, error) {
	var out Session
	pattern := "/v1/sessions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceCreateSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...http.CallOption) (*Workspace, error) {
	var out Workspace
	pattern := "/v1/workspaces"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceCreateWorkspace),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ExchangeNativeOAuthCode(ctx context.Context, in *ExchangeNativeOAuthCodeRequest, opts ...http.CallOption) (*NativeOAuthTokens, error) {
	var out NativeOAuthTokens
	pattern := "/v1/auth/native/exchange"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceExchangeNativeOAuthCode),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...http.CallOption) (*AgentRun, error) {
	var out AgentRun
	pattern := "/v1/agent-runs/{run_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceGetAgentRun),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) GetCurrentAccount(ctx context.Context, in *GetCurrentAccountRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/v1/account"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceGetCurrentAccount),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) GetNativeOAuthConfig(ctx context.Context, in *GetNativeOAuthConfigRequest, opts ...http.CallOption) (*NativeOAuthConfig, error) {
	var out NativeOAuthConfig
	pattern := "/v1/auth/native/config"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceGetNativeOAuthConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) GetSession(ctx context.Context, in *GetSessionRequest, opts ...http.CallOption) (*Session, error) {
	var out Session
	pattern := "/v1/sessions/{session_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceGetSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) GetSyncSnapshot(ctx context.Context, in *GetSyncSnapshotRequest, opts ...http.CallOption) (*GetSyncSnapshotResponse, error) {
	var out GetSyncSnapshotResponse
	pattern := "/v1/sync/snapshot"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceGetSyncSnapshot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...http.CallOption) (*Workspace, error) {
	var out Workspace
	pattern := "/v1/workspaces/{workspace_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceGetWorkspace),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListAgentActions(ctx context.Context, in *ListAgentActionsRequest, opts ...http.CallOption) (*ListAgentActionsResponse, error) {
	var out ListAgentActionsResponse
	pattern := "/v1/agent-runs/{run_id}/actions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListAgentActions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListAgentRunEvents(ctx context.Context, in *ListAgentRunEventsRequest, opts ...http.CallOption) (*ListAgentRunEventsResponse, error) {
	var out ListAgentRunEventsResponse
	pattern := "/v1/agent-runs/{run_id}/events"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListAgentRunEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListAgentRuns(ctx context.Context, in *ListAgentRunsRequest, opts ...http.CallOption) (*ListAgentRunsResponse, error) {
	var out ListAgentRunsResponse
	pattern := "/v1/agent-runs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListAgentRuns),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...http.CallOption) (*ListDevicesResponse, error) {
	var out ListDevicesResponse
	pattern := "/v1/devices"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListDevices),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesResponse, error) {
	var out ListMessagesResponse
	pattern := "/v1/sessions/{session_id}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsResponse, error) {
	var out ListSessionsResponse
	pattern := "/v1/sessions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListSessions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...http.CallOption) (*ListWorkspacesResponse, error) {
	var out ListWorkspacesResponse
	pattern := "/v1/workspaces"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServiceListWorkspaces),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) PullSyncEvents(ctx context.Context, in *PullSyncEventsRequest, opts ...http.CallOption) (*PullSyncEventsResponse, error) {
	var out PullSyncEventsResponse
	pattern := "/v1/sync/events"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCrossDeviceServicePullSyncEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) RefreshNativeOAuthToken(ctx context.Context, in *RefreshNativeOAuthTokenRequest, opts ...http.CallOption) (*NativeOAuthTokens, error) {
	var out NativeOAuthTokens
	pattern := "/v1/auth/native/refresh"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceRefreshNativeOAuthToken),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...http.CallOption) (*Device, error) {
	var out Device
	pattern := "/v1/devices"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceRegisterDevice),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) ResolveAgentAction(ctx context.Context, in *ResolveAgentActionRequest, opts ...http.CallOption) (*AgentAction, error) {
	var out AgentAction
	pattern := "/v1/agent-runs/{run_id}/actions/{action_id}:resolve"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceResolveAgentAction),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...http.CallOption) (*Device, error) {
	var out Device
	pattern := "/v1/devices/{device_id}:revoke"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceRevokeDevice),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...http.CallOption) (*Session, error) {
	var out Session
	pattern := "/v1/sessions/{session_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceUpdateSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CrossDeviceServiceHTTPClientImpl) UpsertPushEndpoint(ctx context.Context, in *UpsertPushEndpointRequest, opts ...http.CallOption) (*PushEndpoint, error) {
	var out PushEndpoint
	pattern := "/v1/push-endpoints"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCrossDeviceServiceUpsertPushEndpoint),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationModelCatalogServiceListModels = "/astraflow.v1.ModelCatalogService/ListModels"

type ModelCatalogServiceHTTPServer interface {
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
}

func RegisterModelCatalogServiceHTTPServer(s *http.Server, srv ModelCatalogServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/models", _ModelCatalogService_ListModels0_HTTP_Handler(srv))
}

func _ModelCatalogService_ListModels0_HTTP_Handler(srv ModelCatalogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListModelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelCatalogServiceListModels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListModels(ctx, req.(*ListModelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListModelsResponse)
		return ctx.Result(200, reply)
	}
}

type ModelCatalogServiceHTTPClient interface {
	ListModels(ctx context.Context, req *ListModelsRequest, opts ...http.CallOption) (rsp *ListModelsResponse, err error)
}

type ModelCatalogServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewModelCatalogServiceHTTPClient(client *http.Client) ModelCatalogServiceHTTPClient {
	return &ModelCatalogServiceHTTPClientImpl{client}
}

func (c *ModelCatalogServiceHTTPClientImpl) ListModels(ctx context.Context, in *ListModelsRequest, opts ...http.CallOption) (*ListModelsResponse, error) {
	var out ListModelsResponse
	pattern := "/v1/models"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModelCatalogServiceListModels),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationArtifactServiceCompleteUpload = "/astraflow.v1.ArtifactService/CompleteUpload"
const OperationArtifactServiceCreateArtifactShare = "/astraflow.v1.ArtifactService/CreateArtifactShare"
const OperationArtifactServiceCreateUpload = "/astraflow.v1.ArtifactService/CreateUpload"
const OperationArtifactServiceGetArtifact = "/astraflow.v1.ArtifactService/GetArtifact"
const OperationArtifactServiceGetSharedArtifact = "/astraflow.v1.ArtifactService/GetSharedArtifact"
const OperationArtifactServiceListArtifacts = "/astraflow.v1.ArtifactService/ListArtifacts"
const OperationArtifactServiceRevokeArtifactShare = "/astraflow.v1.ArtifactService/RevokeArtifactShare"

type ArtifactServiceHTTPServer interface {
	CompleteUpload(context.Context, *CompleteArtifactUploadRequest) (*Artifact, error)
	CreateArtifactShare(context.Context, *CreateArtifactShareRequest) (*ArtifactShare, error)
	CreateUpload(context.Context, *CreateArtifactUploadRequest) (*ArtifactUpload, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*Artifact, error)
	GetSharedArtifact(context.Context, *GetSharedArtifactRequest) (*Artifact, error)
	ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error)
	RevokeArtifactShare(context.Context, *RevokeArtifactShareRequest) (*ArtifactShare, error)
}

func RegisterArtifactServiceHTTPServer(s *http.Server, srv ArtifactServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/uploads", _ArtifactService_CreateUpload0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/uploads/{upload_id}:complete", _ArtifactService_CompleteUpload0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/artifacts", _ArtifactService_ListArtifacts0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/artifacts/{artifact_id}", _ArtifactService_GetArtifact0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/artifacts/{artifact_id}:share", _ArtifactService_CreateArtifactShare0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/artifacts/{artifact_id}/shares/{share_id}", _ArtifactService_RevokeArtifactShare0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/public/artifacts/{share_token}", _ArtifactService_GetSharedArtifact0_HTTP_Handler(srv))
}

func _ArtifactService_CreateUpload0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateArtifactUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceCreateUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUpload(ctx, req.(*CreateArtifactUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArtifactUpload)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_CompleteUpload0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteArtifactUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceCompleteUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteUpload(ctx, req.(*CompleteArtifactUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Artifact)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_ListArtifacts0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListArtifactsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceListArtifacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListArtifacts(ctx, req.(*ListArtifactsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListArtifactsResponse)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_GetArtifact0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArtifactRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceGetArtifact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArtifact(ctx, req.(*GetArtifactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Artifact)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_CreateArtifactShare0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateArtifactShareRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceCreateArtifactShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateArtifactShare(ctx, req.(*CreateArtifactShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArtifactShare)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_RevokeArtifactShare0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeArtifactShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceRevokeArtifactShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeArtifactShare(ctx, req.(*RevokeArtifactShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArtifactShare)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_GetSharedArtifact0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSharedArtifactRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceGetSharedArtifact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSharedArtifact(ctx, req.(*GetSharedArtifactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Artifact)
		return ctx.Result(200, reply)
	}
}

type ArtifactServiceHTTPClient interface {
	CompleteUpload(ctx context.Context, req *CompleteArtifactUploadRequest, opts ...http.CallOption) (rsp *Artifact, err error)
	CreateArtifactShare(ctx context.Context, req *CreateArtifactShareRequest, opts ...http.CallOption) (rsp *ArtifactShare, err error)
	CreateUpload(ctx context.Context, req *CreateArtifactUploadRequest, opts ...http.CallOption) (rsp *ArtifactUpload, err error)
	GetArtifact(ctx context.Context, req *GetArtifactRequest, opts ...http.CallOption) (rsp *Artifact, err error)
	GetSharedArtifact(ctx context.Context, req *GetSharedArtifactRequest, opts ...http.CallOption) (rsp *Artifact, err error)
	ListArtifacts(ctx context.Context, req *ListArtifactsRequest, opts ...http.CallOption) (rsp *ListArtifactsResponse, err error)
	RevokeArtifactShare(ctx context.Context, req *RevokeArtifactShareRequest, opts ...http.CallOption) (rsp *ArtifactShare, err error)
}

type ArtifactServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArtifactServiceHTTPClient(client *http.Client) ArtifactServiceHTTPClient {
	return &ArtifactServiceHTTPClientImpl{client}
}

func (c *ArtifactServiceHTTPClientImpl) CompleteUpload(ctx context.Context, in *CompleteArtifactUploadRequest, opts ...http.CallOption) (*Artifact, error) {
	var out Artifact
	pattern := "/v1/uploads/{upload_id}:complete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationArtifactServiceCompleteUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) CreateArtifactShare(ctx context.Context, in *CreateArtifactShareRequest, opts ...http.CallOption) (*ArtifactShare, error) {
	var out ArtifactShare
	pattern := "/v1/artifacts/{artifact_id}:share"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationArtifactServiceCreateArtifactShare),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) CreateUpload(ctx context.Context, in *CreateArtifactUploadRequest, opts ...http.CallOption) (*ArtifactUpload, error) {
	var out ArtifactUpload
	pattern := "/v1/uploads"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationArtifactServiceCreateUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...http.CallOption) (*Artifact, error) {
	var out Artifact
	pattern := "/v1/artifacts/{artifact_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationArtifactServiceGetArtifact),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) GetSharedArtifact(ctx context.Context, in *GetSharedArtifactRequest, opts ...http.CallOption) (*Artifact, error) {
	var out Artifact
	pattern := "/v1/public/artifacts/{share_token}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationArtifactServiceGetSharedArtifact),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...http.CallOption) (*ListArtifactsResponse, error) {
	var out ListArtifactsResponse
	pattern := "/v1/artifacts"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationArtifactServiceListArtifacts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) RevokeArtifactShare(ctx context.Context, in *RevokeArtifactShareRequest, opts ...http.CallOption) (*ArtifactShare, error) {
	var out ArtifactShare
	pattern := "/v1/artifacts/{artifact_id}/shares/{share_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationArtifactServiceRevokeArtifactShare),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationAutomationServiceCreateAutomation = "/astraflow.v1.AutomationService/CreateAutomation"
const OperationAutomationServiceListAutomations = "/astraflow.v1.AutomationService/ListAutomations"
const OperationAutomationServiceSetAutomationEnabled = "/astraflow.v1.AutomationService/SetAutomationEnabled"

type AutomationServiceHTTPServer interface {
	CreateAutomation(context.Context, *CreateAutomationRequest) (*CloudAutomation, error)
	ListAutomations(context.Context, *ListAutomationsRequest) (*ListAutomationsResponse, error)
	SetAutomationEnabled(context.Context, *SetAutomationEnabledRequest) (*CloudAutomation, error)
}

func RegisterAutomationServiceHTTPServer(s *http.Server, srv AutomationServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/automations", _AutomationService_ListAutomations0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/automations", _AutomationService_CreateAutomation0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/automations/{automation_id}:enabled", _AutomationService_SetAutomationEnabled0_HTTP_Handler(srv))
}

func _AutomationService_ListAutomations0_HTTP_Handler(srv AutomationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAutomationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAutomationServiceListAutomations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAutomations(ctx, req.(*ListAutomationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAutomationsResponse)
		return ctx.Result(200, reply)
	}
}

func _AutomationService_CreateAutomation0_HTTP_Handler(srv AutomationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAutomationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAutomationServiceCreateAutomation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAutomation(ctx, req.(*CreateAutomationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloudAutomation)
		return ctx.Result(200, reply)
	}
}

func _AutomationService_SetAutomationEnabled0_HTTP_Handler(srv AutomationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetAutomationEnabledRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAutomationServiceSetAutomationEnabled)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetAutomationEnabled(ctx, req.(*SetAutomationEnabledRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloudAutomation)
		return ctx.Result(200, reply)
	}
}

type AutomationServiceHTTPClient interface {
	CreateAutomation(ctx context.Context, req *CreateAutomationRequest, opts ...http.CallOption) (rsp *CloudAutomation, err error)
	ListAutomations(ctx context.Context, req *ListAutomationsRequest, opts ...http.CallOption) (rsp *ListAutomationsResponse, err error)
	SetAutomationEnabled(ctx context.Context, req *SetAutomationEnabledRequest, opts ...http.CallOption) (rsp *CloudAutomation, err error)
}

type AutomationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAutomationServiceHTTPClient(client *http.Client) AutomationServiceHTTPClient {
	return &AutomationServiceHTTPClientImpl{client}
}

func (c *AutomationServiceHTTPClientImpl) CreateAutomation(ctx context.Context, in *CreateAutomationRequest, opts ...http.CallOption) (*CloudAutomation, error) {
	var out CloudAutomation
	pattern := "/v1/automations"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAutomationServiceCreateAutomation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AutomationServiceHTTPClientImpl) ListAutomations(ctx context.Context, in *ListAutomationsRequest, opts ...http.CallOption) (*ListAutomationsResponse, error) {
	var out ListAutomationsResponse
	pattern := "/v1/automations"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAutomationServiceListAutomations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AutomationServiceHTTPClientImpl) SetAutomationEnabled(ctx context.Context, in *SetAutomationEnabledRequest, opts ...http.CallOption) (*CloudAutomation, error) {
	var out CloudAutomation
	pattern := "/v1/automations/{automation_id}:enabled"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAutomationServiceSetAutomationEnabled),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationCloudWorkerServiceAppendRunEvents = "/astraflow.v1.CloudWorkerService/AppendRunEvents"
const OperationCloudWorkerServiceClaimRun = "/astraflow.v1.CloudWorkerService/ClaimRun"
const OperationCloudWorkerServiceClaimWorkspace = "/astraflow.v1.CloudWorkerService/ClaimWorkspace"
const OperationCloudWorkerServiceCompleteRunArtifactUpload = "/astraflow.v1.CloudWorkerService/CompleteRunArtifactUpload"
const OperationCloudWorkerServiceCompleteWorkspace = "/astraflow.v1.CloudWorkerService/CompleteWorkspace"
const OperationCloudWorkerServiceCreateRunArtifactUpload = "/astraflow.v1.CloudWorkerService/CreateRunArtifactUpload"
const OperationCloudWorkerServiceRenewRun = "/astraflow.v1.CloudWorkerService/RenewRun"

type CloudWorkerServiceHTTPServer interface {
	AppendRunEvents(context.Context, *AppendCloudRunEventsRequest) (*AppendAgentRunEventsResponse, error)
	ClaimRun(context.Context, *ClaimCloudRunRequest) (*CloudRunLease, error)
	ClaimWorkspace(context.Context, *ClaimCloudWorkspaceRequest) (*CloudWorkspaceLease, error)
	CompleteRunArtifactUpload(context.Context, *CompleteCloudRunArtifactUploadRequest) (*Artifact, error)
	CompleteWorkspace(context.Context, *CompleteCloudWorkspaceRequest) (*Workspace, error)
	CreateRunArtifactUpload(context.Context, *CreateCloudRunArtifactUploadRequest) (*ArtifactUpload, error)
	RenewRun(context.Context, *RenewCloudRunRequest) (*CloudRunLeaseState, error)
}

func RegisterCloudWorkerServiceHTTPServer(s *http.Server, srv CloudWorkerServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/internal/cloud-worker/workspaces:claim", _CloudWorkerService_ClaimWorkspace0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/internal/cloud-worker/workspaces/{workspace_id}:complete", _CloudWorkerService_CompleteWorkspace0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/internal/cloud-worker/runs:claim", _CloudWorkerService_ClaimRun0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/internal/cloud-worker/runs/{run_id}:renew", _CloudWorkerService_RenewRun0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/internal/cloud-worker/runs/{run_id}/events:batch", _CloudWorkerService_AppendRunEvents0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/internal/cloud-worker/runs/{run_id}/artifacts:upload", _CloudWorkerService_CreateRunArtifactUpload0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/internal/cloud-worker/runs/{run_id}/artifacts/{upload_id}:complete", _CloudWorkerService_CompleteRunArtifactUpload0_HTTP_Handler(srv))
}

func _CloudWorkerService_ClaimWorkspace0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimCloudWorkspaceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceClaimWorkspace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimWorkspace(ctx, req.(*ClaimCloudWorkspaceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloudWorkspaceLease)
		return ctx.Result(200, reply)
	}
}

func _CloudWorkerService_CompleteWorkspace0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteCloudWorkspaceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceCompleteWorkspace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteWorkspace(ctx, req.(*CompleteCloudWorkspaceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Workspace)
		return ctx.Result(200, reply)
	}
}

func _CloudWorkerService_ClaimRun0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimCloudRunRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceClaimRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimRun(ctx, req.(*ClaimCloudRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloudRunLease)
		return ctx.Result(200, reply)
	}
}

func _CloudWorkerService_RenewRun0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RenewCloudRunRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceRenewRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RenewRun(ctx, req.(*RenewCloudRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloudRunLeaseState)
		return ctx.Result(200, reply)
	}
}

func _CloudWorkerService_AppendRunEvents0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AppendCloudRunEventsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceAppendRunEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AppendRunEvents(ctx, req.(*AppendCloudRunEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppendAgentRunEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _CloudWorkerService_CreateRunArtifactUpload0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCloudRunArtifactUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceCreateRunArtifactUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRunArtifactUpload(ctx, req.(*CreateCloudRunArtifactUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArtifactUpload)
		return ctx.Result(200, reply)
	}
}

func _CloudWorkerService_CompleteRunArtifactUpload0_HTTP_Handler(srv CloudWorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteCloudRunArtifactUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudWorkerServiceCompleteRunArtifactUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteRunArtifactUpload(ctx, req.(*CompleteCloudRunArtifactUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Artifact)
		return ctx.Result(200, reply)
	}
}

type CloudWorkerServiceHTTPClient interface {
	AppendRunEvents(ctx context.Context, req *AppendCloudRunEventsRequest, opts ...http.CallOption) (rsp *AppendAgentRunEventsResponse, err error)
	ClaimRun(ctx context.Context, req *ClaimCloudRunRequest, opts ...http.CallOption) (rsp *CloudRunLease, err error)
	ClaimWorkspace(ctx context.Context, req *ClaimCloudWorkspaceRequest, opts ...http.CallOption) (rsp *CloudWorkspaceLease, err error)
	CompleteRunArtifactUpload(ctx context.Context, req *CompleteCloudRunArtifactUploadRequest, opts ...http.CallOption) (rsp *Artifact, err error)
	CompleteWorkspace(ctx context.Context, req *CompleteCloudWorkspaceRequest, opts ...http.CallOption) (rsp *Workspace, err error)
	CreateRunArtifactUpload(ctx context.Context, req *CreateCloudRunArtifactUploadRequest, opts ...http.CallOption) (rsp *ArtifactUpload, err error)
	RenewRun(ctx context.Context, req *RenewCloudRunRequest, opts ...http.CallOption) (rsp *CloudRunLeaseState, err error)
}

type CloudWorkerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCloudWorkerServiceHTTPClient(client *http.Client) CloudWorkerServiceHTTPClient {
	return &CloudWorkerServiceHTTPClientImpl{client}
}

func (c *CloudWorkerServiceHTTPClientImpl) AppendRunEvents(ctx context.Context, in *AppendCloudRunEventsRequest, opts ...http.CallOption) (*AppendAgentRunEventsResponse, error) {
	var out AppendAgentRunEventsResponse
	pattern := "/v1/internal/cloud-worker/runs/{run_id}/events:batch"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceAppendRunEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CloudWorkerServiceHTTPClientImpl) ClaimRun(ctx context.Context, in *ClaimCloudRunRequest, opts ...http.CallOption) (*CloudRunLease, error) {
	var out CloudRunLease
	pattern := "/v1/internal/cloud-worker/runs:claim"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceClaimRun),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CloudWorkerServiceHTTPClientImpl) ClaimWorkspace(ctx context.Context, in *ClaimCloudWorkspaceRequest, opts ...http.CallOption) (*CloudWorkspaceLease, error) {
	var out CloudWorkspaceLease
	pattern := "/v1/internal/cloud-worker/workspaces:claim"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceClaimWorkspace),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CloudWorkerServiceHTTPClientImpl) CompleteRunArtifactUpload(ctx context.Context, in *CompleteCloudRunArtifactUploadRequest, opts ...http.CallOption) (*Artifact, error) {
	var out Artifact
	pattern := "/v1/internal/cloud-worker/runs/{run_id}/artifacts/{upload_id}:complete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceCompleteRunArtifactUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CloudWorkerServiceHTTPClientImpl) CompleteWorkspace(ctx context.Context, in *CompleteCloudWorkspaceRequest, opts ...http.CallOption) (*Workspace, error) {
	var out Workspace
	pattern := "/v1/internal/cloud-worker/workspaces/{workspace_id}:complete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceCompleteWorkspace),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CloudWorkerServiceHTTPClientImpl) CreateRunArtifactUpload(ctx context.Context, in *CreateCloudRunArtifactUploadRequest, opts ...http.CallOption) (*ArtifactUpload, error) {
	var out ArtifactUpload
	pattern := "/v1/internal/cloud-worker/runs/{run_id}/artifacts:upload"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceCreateRunArtifactUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CloudWorkerServiceHTTPClientImpl) RenewRun(ctx context.Context, in *RenewCloudRunRequest, opts ...http.CallOption) (*CloudRunLeaseState, error) {
	var out CloudRunLeaseState
	pattern := "/v1/internal/cloud-worker/runs/{run_id}:renew"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCloudWorkerServiceRenewRun),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
