// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: astraflow/v1/expert.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExpertService_ListExpertCategories_FullMethodName = "/astraflow.v1.ExpertService/ListExpertCategories"
	ExpertService_ListExperts_FullMethodName          = "/astraflow.v1.ExpertService/ListExperts"
	ExpertService_GetExpert_FullMethodName            = "/astraflow.v1.ExpertService/GetExpert"
	ExpertService_GetExpertRuntime_FullMethodName     = "/astraflow.v1.ExpertService/GetExpertRuntime"
)

// ExpertServiceClient is the client API for ExpertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExpertServiceClient interface {
	ListExpertCategories(ctx context.Context, in *ListExpertCategoriesRequest, opts ...grpc.CallOption) (*ListExpertCategoriesResponse, error)
	ListExperts(ctx context.Context, in *ListExpertsRequest, opts ...grpc.CallOption) (*ListExpertsResponse, error)
	GetExpert(ctx context.Context, in *GetExpertRequest, opts ...grpc.CallOption) (*GetExpertResponse, error)
	GetExpertRuntime(ctx context.Context, in *GetExpertRuntimeRequest, opts ...grpc.CallOption) (*GetExpertRuntimeResponse, error)
}

type expertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExpertServiceClient(cc grpc.ClientConnInterface) ExpertServiceClient {
	return &expertServiceClient{cc}
}

func (c *expertServiceClient) ListExpertCategories(ctx context.Context, in *ListExpertCategoriesRequest, opts ...grpc.CallOption) (*ListExpertCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExpertCategoriesResponse)
	err := c.cc.Invoke(ctx, ExpertService_ListExpertCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expertServiceClient) ListExperts(ctx context.Context, in *ListExpertsRequest, opts ...grpc.CallOption) (*ListExpertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExpertsResponse)
	err := c.cc.Invoke(ctx, ExpertService_ListExperts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expertServiceClient) GetExpert(ctx context.Context, in *GetExpertRequest, opts ...grpc.CallOption) (*GetExpertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpertResponse)
	err := c.cc.Invoke(ctx, ExpertService_GetExpert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expertServiceClient) GetExpertRuntime(ctx context.Context, in *GetExpertRuntimeRequest, opts ...grpc.CallOption) (*GetExpertRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpertRuntimeResponse)
	err := c.cc.Invoke(ctx, ExpertService_GetExpertRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpertServiceServer is the server API for ExpertService service.
// All implementations must embed UnimplementedExpertServiceServer
// for forward compatibility.
type ExpertServiceServer interface {
	ListExpertCategories(context.Context, *ListExpertCategoriesRequest) (*ListExpertCategoriesResponse, error)
	ListExperts(context.Context, *ListExpertsRequest) (*ListExpertsResponse, error)
	GetExpert(context.Context, *GetExpertRequest) (*GetExpertResponse, error)
	GetExpertRuntime(context.Context, *GetExpertRuntimeRequest) (*GetExpertRuntimeResponse, error)
	mustEmbedUnimplementedExpertServiceServer()
}

// UnimplementedExpertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExpertServiceServer struct{}

func (UnimplementedExpertServiceServer) ListExpertCategories(context.Context, *ListExpertCategoriesRequest) (*ListExpertCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExpertCategories not implemented")
}
func (UnimplementedExpertServiceServer) ListExperts(context.Context, *ListExpertsRequest) (*ListExpertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExperts not implemented")
}
func (UnimplementedExpertServiceServer) GetExpert(context.Context, *GetExpertRequest) (*GetExpertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpert not implemented")
}
func (UnimplementedExpertServiceServer) GetExpertRuntime(context.Context, *GetExpertRuntimeRequest) (*GetExpertRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpertRuntime not implemented")
}
func (UnimplementedExpertServiceServer) mustEmbedUnimplementedExpertServiceServer() {}
func (UnimplementedExpertServiceServer) testEmbeddedByValue()                       {}

// UnsafeExpertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpertServiceServer will
// result in compilation errors.
type UnsafeExpertServiceServer interface {
	mustEmbedUnimplementedExpertServiceServer()
}

func RegisterExpertServiceServer(s grpc.ServiceRegistrar, srv ExpertServiceServer) {
	// If the following call panics, it indicates UnimplementedExpertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExpertService_ServiceDesc, srv)
}

func _ExpertService_ListExpertCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExpertCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpertServiceServer).ListExpertCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpertService_ListExpertCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpertServiceServer).ListExpertCategories(ctx, req.(*ListExpertCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpertService_ListExperts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExpertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpertServiceServer).ListExperts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpertService_ListExperts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpertServiceServer).ListExperts(ctx, req.(*ListExpertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpertService_GetExpert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpertServiceServer).GetExpert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpertService_GetExpert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpertServiceServer).GetExpert(ctx, req.(*GetExpertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpertService_GetExpertRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpertRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpertServiceServer).GetExpertRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpertService_GetExpertRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpertServiceServer).GetExpertRuntime(ctx, req.(*GetExpertRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExpertService_ServiceDesc is the grpc.ServiceDesc for ExpertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExpertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.ExpertService",
	HandlerType: (*ExpertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExpertCategories",
			Handler:    _ExpertService_ListExpertCategories_Handler,
		},
		{
			MethodName: "ListExperts",
			Handler:    _ExpertService_ListExperts_Handler,
		},
		{
			MethodName: "GetExpert",
			Handler:    _ExpertService_GetExpert_Handler,
		},
		{
			MethodName: "GetExpertRuntime",
			Handler:    _ExpertService_GetExpertRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/expert.proto",
}
