// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astraflow/v1/feedback.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFeedbackRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetMessageId string                 `protobuf:"bytes,2,opt,name=target_message_id,json=targetMessageId,proto3" json:"target_message_id,omitempty"`
	EntryPoint      string                 `protobuf:"bytes,3,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MessagesJson    string                 `protobuf:"bytes,5,opt,name=messages_json,json=messagesJson,proto3" json:"messages_json,omitempty"`
	Images          []*FeedbackImage       `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	ReporterEmail   string                 `protobuf:"bytes,7,opt,name=reporter_email,json=reporterEmail,proto3" json:"reporter_email,omitempty"`
	ClientVersion   string                 `protobuf:"bytes,8,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Platform        string                 `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`
	Locale          string                 `protobuf:"bytes,10,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	mi := &file_astraflow_v1_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeedbackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetTargetMessageId() string {
	if x != nil {
		return x.TargetMessageId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *CreateFeedbackRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFeedbackRequest) GetMessagesJson() string {
	if x != nil {
		return x.MessagesJson
	}
	return ""
}

func (x *CreateFeedbackRequest) GetImages() []*FeedbackImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateFeedbackRequest) GetReporterEmail() string {
	if x != nil {
		return x.ReporterEmail
	}
	return ""
}

func (x *CreateFeedbackRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *CreateFeedbackRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateFeedbackRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type FeedbackImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackImage) Reset() {
	*x = FeedbackImage{}
	mi := &file_astraflow_v1_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackImage) ProtoMessage() {}

func (x *FeedbackImage) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackImage.ProtoReflect.Descriptor instead.
func (*FeedbackImage) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *FeedbackImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedbackImage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FeedbackImage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackResponse) Reset() {
	*x = CreateFeedbackResponse{}
	mi := &file_astraflow_v1_feedback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackResponse) ProtoMessage() {}

func (x *CreateFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_feedback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFeedbackResponse) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *CreateFeedbackResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_astraflow_v1_feedback_proto protoreflect.FileDescriptor

const file_astraflow_v1_feedback_proto_rawDesc = "" +
	"\n" +
	"\x1bastraflow/v1/feedback.proto\x12\fastraflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\x15CreateFeedbackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11target_message_id\x18\x02 \x01(\tR\x0ftargetMessageId\x12\x1f\n" +
	"\ventry_point\x18\x03 \x01(\tR\n" +
	"entryPoint\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rmessages_json\x18\x05 \x01(\tR\fmessagesJson\x123\n" +
	"\x06images\x18\x06 \x03(\v2\x1b.astraflow.v1.FeedbackImageR\x06images\x12%\n" +
	"\x0ereporter_email\x18\a \x01(\tR\rreporterEmail\x12%\n" +
	"\x0eclient_version\x18\b \x01(\tR\rclientVersion\x12\x1a\n" +
	"\bplatform\x18\t \x01(\tR\bplatform\x12\x16\n" +
	"\x06locale\x18\n" +
	" \x01(\tR\x06locale\"Z\n" +
	"\rFeedbackImage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"t\n" +
	"\x16CreateFeedbackResponse\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x88\x01\n" +
	"\x0fFeedbackService\x12u\n" +
	"\x0eCreateFeedback\x12#.astraflow.v1.CreateFeedbackRequest\x1a$.astraflow.v1.CreateFeedbackResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/feedbacksBD\n" +
	"\x17com.ucloud.astraflow.v1P\x01Z!astraflow-api/api/astraflow/v1;v1\xa2\x02\x03AFAb\x06proto3"

var (
	file_astraflow_v1_feedback_proto_rawDescOnce sync.Once
	file_astraflow_v1_feedback_proto_rawDescData []byte
)

func file_astraflow_v1_feedback_proto_rawDescGZIP() []byte {
	file_astraflow_v1_feedback_proto_rawDescOnce.Do(func() {
		file_astraflow_v1_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraflow_v1_feedback_proto_rawDesc), len(file_astraflow_v1_feedback_proto_rawDesc)))
	})
	return file_astraflow_v1_feedback_proto_rawDescData
}

var file_astraflow_v1_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_astraflow_v1_feedback_proto_goTypes = []any{
	(*CreateFeedbackRequest)(nil),  // 0: astraflow.v1.CreateFeedbackRequest
	(*FeedbackImage)(nil),          // 1: astraflow.v1.FeedbackImage
	(*CreateFeedbackResponse)(nil), // 2: astraflow.v1.CreateFeedbackResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_astraflow_v1_feedback_proto_depIdxs = []int32{
	1, // 0: astraflow.v1.CreateFeedbackRequest.images:type_name -> astraflow.v1.FeedbackImage
	3, // 1: astraflow.v1.CreateFeedbackResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: astraflow.v1.FeedbackService.CreateFeedback:input_type -> astraflow.v1.CreateFeedbackRequest
	2, // 3: astraflow.v1.FeedbackService.CreateFeedback:output_type -> astraflow.v1.CreateFeedbackResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_astraflow_v1_feedback_proto_init() }
func file_astraflow_v1_feedback_proto_init() {
	if File_astraflow_v1_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraflow_v1_feedback_proto_rawDesc), len(file_astraflow_v1_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraflow_v1_feedback_proto_goTypes,
		DependencyIndexes: file_astraflow_v1_feedback_proto_depIdxs,
		MessageInfos:      file_astraflow_v1_feedback_proto_msgTypes,
	}.Build()
	File_astraflow_v1_feedback_proto = out.File
	file_astraflow_v1_feedback_proto_goTypes = nil
	file_astraflow_v1_feedback_proto_depIdxs = nil
}
