// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astraflow/v1/marketplace.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMcpMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	OrderBy       string                 `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMcpMarketRequest) Reset() {
	*x = ListMcpMarketRequest{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMcpMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMcpMarketRequest) ProtoMessage() {}

func (x *ListMcpMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMcpMarketRequest.ProtoReflect.Descriptor instead.
func (*ListMcpMarketRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *ListMcpMarketRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListMcpMarketRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListMcpMarketRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMcpMarketRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type McpRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Subfolder     string                 `protobuf:"bytes,3,opt,name=subfolder,proto3" json:"subfolder,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpRepository) Reset() {
	*x = McpRepository{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpRepository) ProtoMessage() {}

func (x *McpRepository) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpRepository.ProtoReflect.Descriptor instead.
func (*McpRepository) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *McpRepository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *McpRepository) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *McpRepository) GetSubfolder() string {
	if x != nil {
		return x.Subfolder
	}
	return ""
}

func (x *McpRepository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type McpMarketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	WebsiteUrl    string                 `protobuf:"bytes,5,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	Repository    *McpRepository         `protobuf:"bytes,6,opt,name=repository,proto3" json:"repository,omitempty"`
	IconUrl       string                 `protobuf:"bytes,7,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	RegistryTypes []string               `protobuf:"bytes,8,rep,name=registry_types,json=registryTypes,proto3" json:"registry_types,omitempty"`
	Transports    []string               `protobuf:"bytes,9,rep,name=transports,proto3" json:"transports,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,11,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsLatest      bool                   `protobuf:"varint,13,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	ServerJsonUrl string                 `protobuf:"bytes,14,opt,name=server_json_url,json=serverJsonUrl,proto3" json:"server_json_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpMarketItem) Reset() {
	*x = McpMarketItem{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpMarketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpMarketItem) ProtoMessage() {}

func (x *McpMarketItem) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpMarketItem.ProtoReflect.Descriptor instead.
func (*McpMarketItem) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{2}
}

func (x *McpMarketItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *McpMarketItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *McpMarketItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *McpMarketItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *McpMarketItem) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *McpMarketItem) GetRepository() *McpRepository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *McpMarketItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *McpMarketItem) GetRegistryTypes() []string {
	if x != nil {
		return x.RegistryTypes
	}
	return nil
}

func (x *McpMarketItem) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *McpMarketItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *McpMarketItem) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *McpMarketItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *McpMarketItem) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

func (x *McpMarketItem) GetServerJsonUrl() string {
	if x != nil {
		return x.ServerJsonUrl
	}
	return ""
}

type ListMcpMarketResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalCount       int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Mcps             []*McpMarketItem       `protobuf:"bytes,2,rep,name=mcps,proto3" json:"mcps,omitempty"`
	AllRegistryTypes []string               `protobuf:"bytes,3,rep,name=all_registry_types,json=allRegistryTypes,proto3" json:"all_registry_types,omitempty"`
	AllTransports    []string               `protobuf:"bytes,4,rep,name=all_transports,json=allTransports,proto3" json:"all_transports,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListMcpMarketResponse) Reset() {
	*x = ListMcpMarketResponse{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMcpMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMcpMarketResponse) ProtoMessage() {}

func (x *ListMcpMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMcpMarketResponse.ProtoReflect.Descriptor instead.
func (*ListMcpMarketResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{3}
}

func (x *ListMcpMarketResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMcpMarketResponse) GetMcps() []*McpMarketItem {
	if x != nil {
		return x.Mcps
	}
	return nil
}

func (x *ListMcpMarketResponse) GetAllRegistryTypes() []string {
	if x != nil {
		return x.AllRegistryTypes
	}
	return nil
}

func (x *ListMcpMarketResponse) GetAllTransports() []string {
	if x != nil {
		return x.AllTransports
	}
	return nil
}

type GetMcpDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpDetailRequest) Reset() {
	*x = GetMcpDetailRequest{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpDetailRequest) ProtoMessage() {}

func (x *GetMcpDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpDetailRequest.ProtoReflect.Descriptor instead.
func (*GetMcpDetailRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{4}
}

func (x *GetMcpDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMcpDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcp           *McpMarketItem         `protobuf:"bytes,1,opt,name=mcp,proto3" json:"mcp,omitempty"`
	ServerJson    string                 `protobuf:"bytes,2,opt,name=server_json,json=serverJson,proto3" json:"server_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpDetailResponse) Reset() {
	*x = GetMcpDetailResponse{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpDetailResponse) ProtoMessage() {}

func (x *GetMcpDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpDetailResponse.ProtoReflect.Descriptor instead.
func (*GetMcpDetailResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{5}
}

func (x *GetMcpDetailResponse) GetMcp() *McpMarketItem {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *GetMcpDetailResponse) GetServerJson() string {
	if x != nil {
		return x.ServerJson
	}
	return ""
}

type ListSkillMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillMarketRequest) Reset() {
	*x = ListSkillMarketRequest{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillMarketRequest) ProtoMessage() {}

func (x *ListSkillMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillMarketRequest.ProtoReflect.Descriptor instead.
func (*ListSkillMarketRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{6}
}

func (x *ListSkillMarketRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListSkillMarketRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListSkillMarketRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListSkillMarketRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSkillMarketRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SkillMarketItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Slug              string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Author            string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DescriptionZh     string                 `protobuf:"bytes,6,opt,name=description_zh,json=descriptionZh,proto3" json:"description_zh,omitempty"`
	Category          string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	License           string                 `protobuf:"bytes,8,opt,name=license,proto3" json:"license,omitempty"`
	Downloads         int64                  `protobuf:"varint,9,opt,name=downloads,proto3" json:"downloads,omitempty"`
	FileCount         int32                  `protobuf:"varint,10,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,11,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ArchiveUrl        string                 `protobuf:"bytes,12,opt,name=archive_url,json=archiveUrl,proto3" json:"archive_url,omitempty"`
	UpstreamUrl       string                 `protobuf:"bytes,13,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	UpstreamUpdatedAt int64                  `protobuf:"varint,14,opt,name=upstream_updated_at,json=upstreamUpdatedAt,proto3" json:"upstream_updated_at,omitempty"`
	FilesJson         string                 `protobuf:"bytes,15,opt,name=files_json,json=filesJson,proto3" json:"files_json,omitempty"`
	SkillMdUrl        string                 `protobuf:"bytes,16,opt,name=skill_md_url,json=skillMdUrl,proto3" json:"skill_md_url,omitempty"`
	Upstream          string                 `protobuf:"bytes,17,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Latest            bool                   `protobuf:"varint,18,opt,name=latest,proto3" json:"latest,omitempty"`
	IconUrl           string                 `protobuf:"bytes,19,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SkillMarketItem) Reset() {
	*x = SkillMarketItem{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillMarketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillMarketItem) ProtoMessage() {}

func (x *SkillMarketItem) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillMarketItem.ProtoReflect.Descriptor instead.
func (*SkillMarketItem) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{7}
}

func (x *SkillMarketItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SkillMarketItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillMarketItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillMarketItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SkillMarketItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillMarketItem) GetDescriptionZh() string {
	if x != nil {
		return x.DescriptionZh
	}
	return ""
}

func (x *SkillMarketItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SkillMarketItem) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *SkillMarketItem) GetDownloads() int64 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *SkillMarketItem) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *SkillMarketItem) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SkillMarketItem) GetArchiveUrl() string {
	if x != nil {
		return x.ArchiveUrl
	}
	return ""
}

func (x *SkillMarketItem) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *SkillMarketItem) GetUpstreamUpdatedAt() int64 {
	if x != nil {
		return x.UpstreamUpdatedAt
	}
	return 0
}

func (x *SkillMarketItem) GetFilesJson() string {
	if x != nil {
		return x.FilesJson
	}
	return ""
}

func (x *SkillMarketItem) GetSkillMdUrl() string {
	if x != nil {
		return x.SkillMdUrl
	}
	return ""
}

func (x *SkillMarketItem) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *SkillMarketItem) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

func (x *SkillMarketItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type ListSkillMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Skills        []*SkillMarketItem     `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	AllCategories []string               `protobuf:"bytes,3,rep,name=all_categories,json=allCategories,proto3" json:"all_categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillMarketResponse) Reset() {
	*x = ListSkillMarketResponse{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillMarketResponse) ProtoMessage() {}

func (x *ListSkillMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillMarketResponse.ProtoReflect.Descriptor instead.
func (*ListSkillMarketResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{8}
}

func (x *ListSkillMarketResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListSkillMarketResponse) GetSkills() []*SkillMarketItem {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillMarketResponse) GetAllCategories() []string {
	if x != nil {
		return x.AllCategories
	}
	return nil
}

type GetSkillDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailRequest) Reset() {
	*x = GetSkillDetailRequest{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailRequest) ProtoMessage() {}

func (x *GetSkillDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailRequest.ProtoReflect.Descriptor instead.
func (*GetSkillDetailRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{9}
}

func (x *GetSkillDetailRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetSkillDetailRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetSkillDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *SkillMarketItem       `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	SkillMd       string                 `protobuf:"bytes,2,opt,name=skill_md,json=skillMd,proto3" json:"skill_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailResponse) Reset() {
	*x = GetSkillDetailResponse{}
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailResponse) ProtoMessage() {}

func (x *GetSkillDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_marketplace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailResponse.ProtoReflect.Descriptor instead.
func (*GetSkillDetailResponse) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_marketplace_proto_rawDescGZIP(), []int{10}
}

func (x *GetSkillDetailResponse) GetSkill() *SkillMarketItem {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *GetSkillDetailResponse) GetSkillMd() string {
	if x != nil {
		return x.SkillMd
	}
	return ""
}

var File_astraflow_v1_marketplace_proto protoreflect.FileDescriptor

const file_astraflow_v1_marketplace_proto_rawDesc = "" +
	"\n" +
	"\x1eastraflow/v1/marketplace.proto\x12\fastraflow.v1\x1a\x1cgoogle/api/annotations.proto\"y\n" +
	"\x14ListMcpMarketRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\border_by\x18\x02 \x01(\tR\aorderBy\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"g\n" +
	"\rMcpRepository\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1c\n" +
	"\tsubfolder\x18\x03 \x01(\tR\tsubfolder\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\xd4\x03\n" +
	"\rMcpMarketItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vwebsite_url\x18\x05 \x01(\tR\n" +
	"websiteUrl\x12;\n" +
	"\n" +
	"repository\x18\x06 \x01(\v2\x1b.astraflow.v1.McpRepositoryR\n" +
	"repository\x12\x19\n" +
	"\bicon_url\x18\a \x01(\tR\aiconUrl\x12%\n" +
	"\x0eregistry_types\x18\b \x03(\tR\rregistryTypes\x12\x1e\n" +
	"\n" +
	"transports\x18\t \x03(\tR\n" +
	"transports\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\fpublished_at\x18\v \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tis_latest\x18\r \x01(\bR\bisLatest\x12&\n" +
	"\x0fserver_json_url\x18\x0e \x01(\tR\rserverJsonUrl\"\xbe\x01\n" +
	"\x15ListMcpMarketResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12/\n" +
	"\x04mcps\x18\x02 \x03(\v2\x1b.astraflow.v1.McpMarketItemR\x04mcps\x12,\n" +
	"\x12all_registry_types\x18\x03 \x03(\tR\x10allRegistryTypes\x12%\n" +
	"\x0eall_transports\x18\x04 \x03(\tR\rallTransports\")\n" +
	"\x13GetMcpDetailRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"f\n" +
	"\x14GetMcpDetailResponse\x12-\n" +
	"\x03mcp\x18\x01 \x01(\v2\x1b.astraflow.v1.McpMarketItemR\x03mcp\x12\x1f\n" +
	"\vserver_json\x18\x02 \x01(\tR\n" +
	"serverJson\"\x97\x01\n" +
	"\x16ListSkillMarketRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xca\x04\n" +
	"\x0fSkillMarketItem\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12%\n" +
	"\x0edescription_zh\x18\x06 \x01(\tR\rdescriptionZh\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x18\n" +
	"\alicense\x18\b \x01(\tR\alicense\x12\x1c\n" +
	"\tdownloads\x18\t \x01(\x03R\tdownloads\x12\x1d\n" +
	"\n" +
	"file_count\x18\n" +
	" \x01(\x05R\tfileCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\v \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\varchive_url\x18\f \x01(\tR\n" +
	"archiveUrl\x12!\n" +
	"\fupstream_url\x18\r \x01(\tR\vupstreamUrl\x12.\n" +
	"\x13upstream_updated_at\x18\x0e \x01(\x03R\x11upstreamUpdatedAt\x12\x1d\n" +
	"\n" +
	"files_json\x18\x0f \x01(\tR\tfilesJson\x12 \n" +
	"\fskill_md_url\x18\x10 \x01(\tR\n" +
	"skillMdUrl\x12\x1a\n" +
	"\bupstream\x18\x11 \x01(\tR\bupstream\x12\x16\n" +
	"\x06latest\x18\x12 \x01(\bR\x06latest\x12\x19\n" +
	"\bicon_url\x18\x13 \x01(\tR\aiconUrl\"\x98\x01\n" +
	"\x17ListSkillMarketResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x125\n" +
	"\x06skills\x18\x02 \x03(\v2\x1d.astraflow.v1.SkillMarketItemR\x06skills\x12%\n" +
	"\x0eall_categories\x18\x03 \x03(\tR\rallCategories\"E\n" +
	"\x15GetSkillDetailRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"h\n" +
	"\x16GetSkillDetailResponse\x123\n" +
	"\x05skill\x18\x01 \x01(\v2\x1d.astraflow.v1.SkillMarketItemR\x05skill\x12\x19\n" +
	"\bskill_md\x18\x02 \x01(\tR\askillMd2\x8c\x04\n" +
	"\x12MarketplaceService\x12v\n" +
	"\rListMcpMarket\x12\".astraflow.v1.ListMcpMarketRequest\x1a#.astraflow.v1.ListMcpMarketResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/marketplace/mcps\x12y\n" +
	"\fGetMcpDetail\x12!.astraflow.v1.GetMcpDetailRequest\x1a\".astraflow.v1.GetMcpDetailResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/marketplace/mcp-detail\x12~\n" +
	"\x0fListSkillMarket\x12$.astraflow.v1.ListSkillMarketRequest\x1a%.astraflow.v1.ListSkillMarketResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/marketplace/skills\x12\x82\x01\n" +
	"\x0eGetSkillDetail\x12#.astraflow.v1.GetSkillDetailRequest\x1a$.astraflow.v1.GetSkillDetailResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/marketplace/skills/{slug}BD\n" +
	"\x17com.ucloud.astraflow.v1P\x01Z!astraflow-api/api/astraflow/v1;v1\xa2\x02\x03AFAb\x06proto3"

var (
	file_astraflow_v1_marketplace_proto_rawDescOnce sync.Once
	file_astraflow_v1_marketplace_proto_rawDescData []byte
)

func file_astraflow_v1_marketplace_proto_rawDescGZIP() []byte {
	file_astraflow_v1_marketplace_proto_rawDescOnce.Do(func() {
		file_astraflow_v1_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraflow_v1_marketplace_proto_rawDesc), len(file_astraflow_v1_marketplace_proto_rawDesc)))
	})
	return file_astraflow_v1_marketplace_proto_rawDescData
}

var file_astraflow_v1_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_astraflow_v1_marketplace_proto_goTypes = []any{
	(*ListMcpMarketRequest)(nil),    // 0: astraflow.v1.ListMcpMarketRequest
	(*McpRepository)(nil),           // 1: astraflow.v1.McpRepository
	(*McpMarketItem)(nil),           // 2: astraflow.v1.McpMarketItem
	(*ListMcpMarketResponse)(nil),   // 3: astraflow.v1.ListMcpMarketResponse
	(*GetMcpDetailRequest)(nil),     // 4: astraflow.v1.GetMcpDetailRequest
	(*GetMcpDetailResponse)(nil),    // 5: astraflow.v1.GetMcpDetailResponse
	(*ListSkillMarketRequest)(nil),  // 6: astraflow.v1.ListSkillMarketRequest
	(*SkillMarketItem)(nil),         // 7: astraflow.v1.SkillMarketItem
	(*ListSkillMarketResponse)(nil), // 8: astraflow.v1.ListSkillMarketResponse
	(*GetSkillDetailRequest)(nil),   // 9: astraflow.v1.GetSkillDetailRequest
	(*GetSkillDetailResponse)(nil),  // 10: astraflow.v1.GetSkillDetailResponse
}
var file_astraflow_v1_marketplace_proto_depIdxs = []int32{
	1,  // 0: astraflow.v1.McpMarketItem.repository:type_name -> astraflow.v1.McpRepository
	2,  // 1: astraflow.v1.ListMcpMarketResponse.mcps:type_name -> astraflow.v1.McpMarketItem
	2,  // 2: astraflow.v1.GetMcpDetailResponse.mcp:type_name -> astraflow.v1.McpMarketItem
	7,  // 3: astraflow.v1.ListSkillMarketResponse.skills:type_name -> astraflow.v1.SkillMarketItem
	7,  // 4: astraflow.v1.GetSkillDetailResponse.skill:type_name -> astraflow.v1.SkillMarketItem
	0,  // 5: astraflow.v1.MarketplaceService.ListMcpMarket:input_type -> astraflow.v1.ListMcpMarketRequest
	4,  // 6: astraflow.v1.MarketplaceService.GetMcpDetail:input_type -> astraflow.v1.GetMcpDetailRequest
	6,  // 7: astraflow.v1.MarketplaceService.ListSkillMarket:input_type -> astraflow.v1.ListSkillMarketRequest
	9,  // 8: astraflow.v1.MarketplaceService.GetSkillDetail:input_type -> astraflow.v1.GetSkillDetailRequest
	3,  // 9: astraflow.v1.MarketplaceService.ListMcpMarket:output_type -> astraflow.v1.ListMcpMarketResponse
	5,  // 10: astraflow.v1.MarketplaceService.GetMcpDetail:output_type -> astraflow.v1.GetMcpDetailResponse
	8,  // 11: astraflow.v1.MarketplaceService.ListSkillMarket:output_type -> astraflow.v1.ListSkillMarketResponse
	10, // 12: astraflow.v1.MarketplaceService.GetSkillDetail:output_type -> astraflow.v1.GetSkillDetailResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_astraflow_v1_marketplace_proto_init() }
func file_astraflow_v1_marketplace_proto_init() {
	if File_astraflow_v1_marketplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraflow_v1_marketplace_proto_rawDesc), len(file_astraflow_v1_marketplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraflow_v1_marketplace_proto_goTypes,
		DependencyIndexes: file_astraflow_v1_marketplace_proto_depIdxs,
		MessageInfos:      file_astraflow_v1_marketplace_proto_msgTypes,
	}.Build()
	File_astraflow_v1_marketplace_proto = out.File
	file_astraflow_v1_marketplace_proto_goTypes = nil
	file_astraflow_v1_marketplace_proto_depIdxs = nil
}
