// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: astraflow/v1/speech.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeechService_Transcribe_FullMethodName    = "/astraflow.v1.SpeechService/Transcribe"
	SpeechService_GenerateTitle_FullMethodName = "/astraflow.v1.SpeechService/GenerateTitle"
	SpeechService_Process_FullMethodName       = "/astraflow.v1.SpeechService/Process"
)

// SpeechServiceClient is the client API for SpeechService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpeechService exposes speech transcription and concise title generation.
// For long recordings, audio_uri avoids base64 expansion at the HTTP boundary.
type SpeechServiceClient interface {
	Transcribe(ctx context.Context, in *TranscribeSpeechRequest, opts ...grpc.CallOption) (*TranscribeSpeechReply, error)
	GenerateTitle(ctx context.Context, in *GenerateSpeechTitleRequest, opts ...grpc.CallOption) (*GenerateSpeechTitleReply, error)
	Process(ctx context.Context, in *ProcessSpeechRequest, opts ...grpc.CallOption) (*ProcessSpeechReply, error)
}

type speechServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechServiceClient(cc grpc.ClientConnInterface) SpeechServiceClient {
	return &speechServiceClient{cc}
}

func (c *speechServiceClient) Transcribe(ctx context.Context, in *TranscribeSpeechRequest, opts ...grpc.CallOption) (*TranscribeSpeechReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeSpeechReply)
	err := c.cc.Invoke(ctx, SpeechService_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speechServiceClient) GenerateTitle(ctx context.Context, in *GenerateSpeechTitleRequest, opts ...grpc.CallOption) (*GenerateSpeechTitleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSpeechTitleReply)
	err := c.cc.Invoke(ctx, SpeechService_GenerateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speechServiceClient) Process(ctx context.Context, in *ProcessSpeechRequest, opts ...grpc.CallOption) (*ProcessSpeechReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessSpeechReply)
	err := c.cc.Invoke(ctx, SpeechService_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeechServiceServer is the server API for SpeechService service.
// All implementations must embed UnimplementedSpeechServiceServer
// for forward compatibility.
//
// SpeechService exposes speech transcription and concise title generation.
// For long recordings, audio_uri avoids base64 expansion at the HTTP boundary.
type SpeechServiceServer interface {
	Transcribe(context.Context, *TranscribeSpeechRequest) (*TranscribeSpeechReply, error)
	GenerateTitle(context.Context, *GenerateSpeechTitleRequest) (*GenerateSpeechTitleReply, error)
	Process(context.Context, *ProcessSpeechRequest) (*ProcessSpeechReply, error)
	mustEmbedUnimplementedSpeechServiceServer()
}

// UnimplementedSpeechServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeechServiceServer struct{}

func (UnimplementedSpeechServiceServer) Transcribe(context.Context, *TranscribeSpeechRequest) (*TranscribeSpeechReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedSpeechServiceServer) GenerateTitle(context.Context, *GenerateSpeechTitleRequest) (*GenerateSpeechTitleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTitle not implemented")
}
func (UnimplementedSpeechServiceServer) Process(context.Context, *ProcessSpeechRequest) (*ProcessSpeechReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedSpeechServiceServer) mustEmbedUnimplementedSpeechServiceServer() {}
func (UnimplementedSpeechServiceServer) testEmbeddedByValue()                       {}

// UnsafeSpeechServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechServiceServer will
// result in compilation errors.
type UnsafeSpeechServiceServer interface {
	mustEmbedUnimplementedSpeechServiceServer()
}

func RegisterSpeechServiceServer(s grpc.ServiceRegistrar, srv SpeechServiceServer) {
	// If the following call panics, it indicates UnimplementedSpeechServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeechService_ServiceDesc, srv)
}

func _SpeechService_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechServiceServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeechService_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechServiceServer).Transcribe(ctx, req.(*TranscribeSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeechService_GenerateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSpeechTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechServiceServer).GenerateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeechService_GenerateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechServiceServer).GenerateTitle(ctx, req.(*GenerateSpeechTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeechService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeechService_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechServiceServer).Process(ctx, req.(*ProcessSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeechService_ServiceDesc is the grpc.ServiceDesc for SpeechService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astraflow.v1.SpeechService",
	HandlerType: (*SpeechServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _SpeechService_Transcribe_Handler,
		},
		{
			MethodName: "GenerateTitle",
			Handler:    _SpeechService_GenerateTitle_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _SpeechService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "astraflow/v1/speech.proto",
}
