// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: astraflow/v1/speech.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSpeechServiceGenerateTitle = "/astraflow.v1.SpeechService/GenerateTitle"
const OperationSpeechServiceProcess = "/astraflow.v1.SpeechService/Process"
const OperationSpeechServiceTranscribe = "/astraflow.v1.SpeechService/Transcribe"

type SpeechServiceHTTPServer interface {
	GenerateTitle(context.Context, *GenerateSpeechTitleRequest) (*GenerateSpeechTitleReply, error)
	Process(context.Context, *ProcessSpeechRequest) (*ProcessSpeechReply, error)
	Transcribe(context.Context, *TranscribeSpeechRequest) (*TranscribeSpeechReply, error)
}

func RegisterSpeechServiceHTTPServer(s *http.Server, srv SpeechServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/speech:transcribe", _SpeechService_Transcribe0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/speech:generateTitle", _SpeechService_GenerateTitle0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/speech:process", _SpeechService_Process0_HTTP_Handler(srv))
}

func _SpeechService_Transcribe0_HTTP_Handler(srv SpeechServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TranscribeSpeechRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpeechServiceTranscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Transcribe(ctx, req.(*TranscribeSpeechRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TranscribeSpeechReply)
		return ctx.Result(200, reply)
	}
}

func _SpeechService_GenerateTitle0_HTTP_Handler(srv SpeechServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateSpeechTitleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpeechServiceGenerateTitle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateTitle(ctx, req.(*GenerateSpeechTitleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateSpeechTitleReply)
		return ctx.Result(200, reply)
	}
}

func _SpeechService_Process0_HTTP_Handler(srv SpeechServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProcessSpeechRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpeechServiceProcess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Process(ctx, req.(*ProcessSpeechRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProcessSpeechReply)
		return ctx.Result(200, reply)
	}
}

type SpeechServiceHTTPClient interface {
	GenerateTitle(ctx context.Context, req *GenerateSpeechTitleRequest, opts ...http.CallOption) (rsp *GenerateSpeechTitleReply, err error)
	Process(ctx context.Context, req *ProcessSpeechRequest, opts ...http.CallOption) (rsp *ProcessSpeechReply, err error)
	Transcribe(ctx context.Context, req *TranscribeSpeechRequest, opts ...http.CallOption) (rsp *TranscribeSpeechReply, err error)
}

type SpeechServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSpeechServiceHTTPClient(client *http.Client) SpeechServiceHTTPClient {
	return &SpeechServiceHTTPClientImpl{client}
}

func (c *SpeechServiceHTTPClientImpl) GenerateTitle(ctx context.Context, in *GenerateSpeechTitleRequest, opts ...http.CallOption) (*GenerateSpeechTitleReply, error) {
	var out GenerateSpeechTitleReply
	pattern := "/v1/speech:generateTitle"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSpeechServiceGenerateTitle),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpeechServiceHTTPClientImpl) Process(ctx context.Context, in *ProcessSpeechRequest, opts ...http.CallOption) (*ProcessSpeechReply, error) {
	var out ProcessSpeechReply
	pattern := "/v1/speech:process"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSpeechServiceProcess),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpeechServiceHTTPClientImpl) Transcribe(ctx context.Context, in *TranscribeSpeechRequest, opts ...http.CallOption) (*TranscribeSpeechReply, error) {
	var out TranscribeSpeechReply
	pattern := "/v1/speech:transcribe"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSpeechServiceTranscribe),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
