export function getStudioRightPanelLabels(locale: string) {
  if (locale === "zh") {
    return {
      add: "添加",
      allowBrowser: "启用后可在 AstraFlow 内直接浏览网站",
      alwaysAsk: "始终询问",
      alwaysInclude: "始终包含",
      browser: "浏览器",
      browserDataCleared: "浏览数据已清除",
      browserDataFailed: "清除浏览数据失败",
      browserDisabled: "内置浏览器已关闭",
      browserDisabledDescription: "请在浏览器设置中启用后再打开网站。",
      browserMenu: "浏览器菜单",
      browserSettings: "浏览器设置",
      browserStart: "开始浏览",
      browserStartDescription: "输入 URL 以打开页面",
      browserTitle: "浏览器",
      browsingData: "浏览数据",
      browsingDataHelp:
        "清除内置浏览器中的 Cookie、网站数据和缓存",
      clearAllBrowsingData: "清除所有浏览数据",
      clearBrowsingData: "清除浏览数据",
      closeFind: "关闭查找",
      closePanel: "关闭",
      closeOtherTabs: "关闭其他标签",
      closeTabsToRight: "关闭右侧标签",
      desktopUnavailable: "仅桌面应用可用",
      emptyFolder: "这个文件夹为空",
      files: "文件",
      fileTargetUnavailable: "找不到该文件，可能已被移动或删除。",
      filesShortcut: "⌘P",
      filterFiles: "筛选文件...",
      findInPage: "在页面中查找",
      findPlaceholder: "查找网页内容",
      focusWorkspace: "聚焦工作区",
      forceReload: "强制重新加载",
      general: "常规",
      hideDeviceToolbar: "隐藏设备工具栏",
      localTargetApp: "AstraFlow",
      localUrlHelp: "本地开发站点默认打开位置",
      localUrlTarget: "本地 URL 打开目标位置",
      mobileViewport: "手机 390",
      newTab: "新选项卡",
      nextMatch: "下一个匹配项",
      noPreview: "无法预览这个文件",
      noPreviewDescription: "此文件类型暂不支持预览，可以用系统默认应用打开。",
      noWebsitePermissions: "尚无网站专属权限",
      open: "打开",
      openWithSystemApp: "用系统应用打开",
      openExternalFailed: "无法使用系统浏览器打开此地址",
      revealInFolder: "在文件夹中显示",
      permissions: "权限",
      permissionsHelp: "选择是否让 AstraFlow 在打开网站前先请求批准。",
      previousMatch: "上一个匹配项",
      refresh: "刷新",
      responsiveViewport: "自适应",
      envEnvironmentInfo: "环境信息",
      envAddSource: "添加来源",
      envPlan: "计划",
      envSubagents: "子智能体",
      envStatusRunning: "进行中",
      envStatusComplete: "已完成",
      envStatusFailed: "失败",
      envStatusCancelled: "已取消",
      envChanges: "变更",
      envRemote: "远程",
      envNoRemote: "暂无远程仓库",
      envBranches: "分支",
      envCommitOrPush: "提交或推送",
      envCommitMessagePlaceholder: "提交信息",
      envCommitAction: "提交",
      envPushAction: "推送",
      envCommitAndPushAction: "提交并推送",
      envGitActionSucceeded: "Git 操作已完成",
      envGitActionFailed: "Git 操作失败",
      envLoadChangesFailed: "加载变更失败",
      envUncommittedChanges: "未提交变更",
      envSessionChanges: "会话变更",
      envSources: "来源",
      envNoSources: "暂无来源",
      review: "审查",
      reviewCollapseAll: "折叠全部",
      reviewExpandAll: "展开全部",
      reviewFiles: "文件",
      reviewFilter: "筛选",
      reviewFilterCreated: "新增",
      reviewFilterEdited: "修改",
      reviewFilterDeleted: "删除",
      reviewIncludeFile: "包含此文件",
      reviewNoChanges: "暂无可审查的变更",
      reviewNoMatches: "没有匹配的文件",
      reviewOpenFile: "打开文件",
      reviewSearch: "搜索",
      reviewSearchPlaceholder: "搜索文件...",
      reviewScopeLastTurn: "本轮变更",
      reviewTruncated: "变更较多，仅显示前 50 个文件。",
      reviewUnmodifiedLines: (count: number) => `${count} 行未修改`,
      reviewViewOptions: "查看选项",
      reviewViewToggle: "切换视图",
      screenshotHelp:
        "截图可帮助 AstraFlow 更好地理解并处理评论，但会增加套餐用量",
      screenshotMode: "批注截图",
      settingsDescription: "管理内置浏览器和本地开发地址的打开方式。",
      showDeviceToolbar: "显示设备工具栏",
      deviceViewport: "设备视口",
      sideChat: "侧边聊天",
      sideChatGreeting: "在侧边聊天里记录临时想法，不影响主对话。",
      sideChatPlaceholder: "写一条侧边消息...",
      sideChatShortcut: "⌥⌘S",
      terminal: "终端",
      toggleFileList: "显示/隐藏文件列表",
      toggleRightPanel: "显示/隐藏侧边栏",
      systemBrowser: "系统默认浏览器",
      tabletViewport: "平板 768",
      truncated: "文件较大，已截断预览",
      websitePermissions: "网站权限",
      websitePermissionsHelp: "为特定网站覆盖上述默认设置",
      zoom: "缩放",
    }
  }

  return {
    add: "Add",
    allowBrowser: "Browse websites directly inside AstraFlow when enabled",
    alwaysAsk: "Always ask",
    alwaysInclude: "Always include",
    browser: "Browser",
    browserDataCleared: "Browsing data cleared",
    browserDataFailed: "Failed to clear browsing data",
    browserDisabled: "In-app browser is off",
    browserDisabledDescription: "Enable it in Browser settings to open websites.",
    browserMenu: "Browser menu",
    browserSettings: "Browser settings",
    browserStart: "Start browsing",
    browserStartDescription: "Enter a URL to open a page",
    browserTitle: "Browser",
    browsingData: "Browsing data",
    browsingDataHelp:
      "Clear cookies, site data, and cache from the in-app browser",
    clearAllBrowsingData: "Clear all browsing data",
    clearBrowsingData: "Clear browsing data",
    closeFind: "Close find",
    closePanel: "Close",
    closeOtherTabs: "Close other tabs",
    closeTabsToRight: "Close tabs to the right",
    desktopUnavailable: "Only available in the desktop app",
    emptyFolder: "This folder is empty",
    files: "Files",
    fileTargetUnavailable: "The file could not be found. It may have been moved or deleted.",
    filesShortcut: "⌘P",
    filterFiles: "Filter files...",
    findInPage: "Find in page",
    findPlaceholder: "Find on this page",
    focusWorkspace: "Focus workspace",
    forceReload: "Force reload",
    general: "General",
    hideDeviceToolbar: "Hide device toolbar",
    localTargetApp: "AstraFlow",
    localUrlHelp: "Default open location for local development sites",
    localUrlTarget: "Local URL target",
    mobileViewport: "Mobile 390",
    newTab: "New tab",
    nextMatch: "Next match",
    noPreview: "This file cannot be previewed",
    noPreviewDescription:
      "Previews are not supported for this file type. You can open it with the system default app.",
    noWebsitePermissions: "No website-specific permissions",
    open: "Open",
    openWithSystemApp: "Open with system app",
    openExternalFailed: "Could not open this address in the system browser",
    revealInFolder: "Reveal in folder",
    permissions: "Permissions",
    permissionsHelp:
      "Choose whether AstraFlow should ask before opening websites.",
    previousMatch: "Previous match",
    refresh: "Refresh",
    responsiveViewport: "Responsive",
    envEnvironmentInfo: "Environment",
    envAddSource: "Add source",
    envPlan: "Plan",
    envSubagents: "Subagents",
    envStatusRunning: "Running",
    envStatusComplete: "Complete",
    envStatusFailed: "Failed",
    envStatusCancelled: "Cancelled",
    envChanges: "Changes",
    envRemote: "Remote",
    envNoRemote: "No remote",
    envBranches: "Branches",
    envCommitOrPush: "Commit or push",
    envCommitMessagePlaceholder: "Commit message",
    envCommitAction: "Commit",
    envPushAction: "Push",
    envCommitAndPushAction: "Commit & push",
    envGitActionSucceeded: "Git action completed",
    envGitActionFailed: "Git action failed",
    envLoadChangesFailed: "Failed to load changes",
    envUncommittedChanges: "Uncommitted changes",
    envSessionChanges: "Session changes",
    envSources: "Sources",
    envNoSources: "No sources yet",
    review: "Review",
    reviewCollapseAll: "Collapse all",
    reviewExpandAll: "Expand all",
    reviewFiles: "Files",
    reviewFilter: "Filter",
    reviewFilterCreated: "Added",
    reviewFilterEdited: "Modified",
    reviewFilterDeleted: "Deleted",
    reviewIncludeFile: "Include file",
    reviewNoChanges: "No changes to review",
    reviewNoMatches: "No matching files",
    reviewOpenFile: "Open file",
    reviewSearch: "Search",
    reviewSearchPlaceholder: "Search files...",
    reviewScopeLastTurn: "Last turn",
    reviewTruncated: "Many changes detected; showing the first 50 files.",
    reviewUnmodifiedLines: (count: number) => `${count} unmodified lines`,
    reviewViewOptions: "View options",
    reviewViewToggle: "Toggle view",
    screenshotHelp:
      "Screenshots help AstraFlow understand and handle comments, but use more quota",
    screenshotMode: "Comment screenshots",
    settingsDescription:
      "Manage the in-app browser and where local development URLs open.",
    showDeviceToolbar: "Show device toolbar",
    deviceViewport: "Device viewport",
    sideChat: "Side chat",
    sideChatGreeting:
      "Capture temporary notes here without changing the main thread.",
    sideChatPlaceholder: "Write a side message...",
    sideChatShortcut: "⌥⌘S",
    terminal: "Terminal",
    toggleFileList: "Show/hide file list",
    toggleRightPanel: "Show/hide side panel",
    systemBrowser: "System default browser",
    tabletViewport: "Tablet 768",
    truncated: "Large file truncated for preview",
    websitePermissions: "Website permissions",
    websitePermissionsHelp: "Override defaults for specific websites",
    zoom: "Zoom",
  }
}

export type StudioRightPanelLabels = ReturnType<
  typeof getStudioRightPanelLabels
>
