export function getStudioRightPanelLabels(locale: string) {
  if (locale === "zh") {
    return {
      add: "添加",
      allowBrowser: "允许 AstraFlow 控制内置浏览器",
      alwaysAsk: "始终询问",
      alwaysInclude: "始终包含",
      browser: "浏览器",
      browserDataCleared: "浏览数据已清除",
      browserDataFailed: "清除浏览数据失败",
      browserMenu: "浏览器菜单",
      browserSettings: "Browser settings",
      browserStart: "开始浏览",
      browserStartDescription: "输入 URL 以打开页面",
      browserTitle: "浏览器",
      browsingData: "浏览数据",
      browsingDataHelp:
        "清除应用内浏览器中的历史记录、网站数据、缓存和下载历史记录",
      clearAllBrowsingData: "清除所有浏览数据",
      clearBrowsingData: "Clear browsing data",
      closePanel: "关闭",
      desktopUnavailable: "仅桌面应用可用",
      emptyFolder: "这个文件夹为空",
      files: "文件",
      filesShortcut: "⌘P",
      filterFiles: "筛选文件...",
      findInPage: "在页面中查找",
      focusWorkspace: "聚焦工作区",
      forceReload: "强制重新加载",
      localTargetApp: "AstraFlow",
      localUrlHelp: "本地开发站点默认打开位置",
      localUrlTarget: "本地 URL 打开目标位置",
      newTab: "新选项卡",
      noPreview: "无法预览这个文件",
      noWebsitePermissions: "尚无网站专属权限",
      open: "打开",
      permissions: "权限",
      permissionsHelp: "选择是否让 AstraFlow 在打开网站前先请求批准。",
      envEnvironmentInfo: "环境信息",
      envAddSource: "添加来源",
      envGoal: "目标",
      envProgress: "进度",
      envStatusRunning: "进行中",
      envStatusComplete: "已完成",
      envChanges: "变更",
      envRemote: "远程",
      envNoRemote: "暂无远程仓库",
      envBranches: "分支",
      envCommitOrPush: "提交或推送",
      envCommitMessagePlaceholder: "提交信息",
      envCommitAction: "提交",
      envPushAction: "推送",
      envCommitAndPushAction: "提交并推送",
      envGitActionSucceeded: "Git 操作已完成",
      envGitActionFailed: "Git 操作失败",
      envLoadChangesFailed: "加载变更失败",
      envUncommittedChanges: "未提交变更",
      envSources: "来源",
      envNoSources: "暂无来源",
      review: "审查",
      reviewNoChanges: "暂无可审查的变更",
      reviewOpenFile: "打开文件",
      reviewScopeLastTurn: "本轮变更",
      reviewUnmodifiedLines: (count: number) => `${count} 行未修改`,
      screenshotHelp:
        "截图可帮助 AstraFlow 更好地理解并处理评论，但会增加套餐用量",
      screenshotMode: "批注截图",
      settingsDescription:
        "管理 AstraFlow 的浏览器。可在计算机使用设置中设置 Google Chrome",
      showDeviceToolbar: "显示设备工具栏",
      sideChat: "侧边聊天",
      sideChatGreeting: "在侧边聊天里记录临时想法，不影响主对话。",
      sideChatPlaceholder: "写一条侧边消息...",
      sideChatShortcut: "⌥⌘S",
      terminal: "终端",
      toggleFileList: "显示/隐藏文件列表",
      toggleRightPanel: "显示/隐藏侧边栏",
      truncated: "文件较大，已截断预览",
      websitePermissions: "网站权限",
      websitePermissionsHelp: "为特定网站覆盖上述默认设置",
      zoom: "缩放",
    }
  }

  return {
    add: "Add",
    allowBrowser: "Allow AstraFlow to control the in-app browser",
    alwaysAsk: "Always ask",
    alwaysInclude: "Always include",
    browser: "Browser",
    browserDataCleared: "Browsing data cleared",
    browserDataFailed: "Failed to clear browsing data",
    browserMenu: "Browser menu",
    browserSettings: "Browser settings",
    browserStart: "Start browsing",
    browserStartDescription: "Enter a URL to open a page",
    browserTitle: "Browser",
    browsingData: "Browsing data",
    browsingDataHelp:
      "Clear history, website data, cache, and download history from the in-app browser",
    clearAllBrowsingData: "Clear all browsing data",
    clearBrowsingData: "Clear browsing data",
    closePanel: "Close",
    desktopUnavailable: "Only available in the desktop app",
    emptyFolder: "This folder is empty",
    files: "Files",
    filesShortcut: "⌘P",
    filterFiles: "Filter files...",
    findInPage: "Find in page",
    focusWorkspace: "Focus workspace",
    forceReload: "Force reload",
    localTargetApp: "AstraFlow",
    localUrlHelp: "Default open location for local development sites",
    localUrlTarget: "Local URL target",
    newTab: "New tab",
    noPreview: "This file cannot be previewed",
    noWebsitePermissions: "No website-specific permissions",
    open: "Open",
    permissions: "Permissions",
    permissionsHelp:
      "Choose whether AstraFlow should ask before opening websites.",
    envEnvironmentInfo: "Environment",
    envAddSource: "Add source",
    envGoal: "Goal",
    envProgress: "Progress",
    envStatusRunning: "Running",
    envStatusComplete: "Complete",
    envChanges: "Changes",
    envRemote: "Remote",
    envNoRemote: "No remote",
    envBranches: "Branches",
    envCommitOrPush: "Commit or push",
    envCommitMessagePlaceholder: "Commit message",
    envCommitAction: "Commit",
    envPushAction: "Push",
    envCommitAndPushAction: "Commit & push",
    envGitActionSucceeded: "Git action completed",
    envGitActionFailed: "Git action failed",
    envLoadChangesFailed: "Failed to load changes",
    envUncommittedChanges: "Uncommitted changes",
    envSources: "Sources",
    envNoSources: "No sources yet",
    review: "Review",
    reviewNoChanges: "No changes to review",
    reviewOpenFile: "Open file",
    reviewScopeLastTurn: "Last turn",
    reviewUnmodifiedLines: (count: number) => `${count} unmodified lines`,
    screenshotHelp:
      "Screenshots help AstraFlow understand and handle comments, but use more quota",
    screenshotMode: "Comment screenshots",
    settingsDescription:
      "Manage AstraFlow's browser. Set Google Chrome in computer use settings",
    showDeviceToolbar: "Show device toolbar",
    sideChat: "Side chat",
    sideChatGreeting:
      "Capture temporary notes here without changing the main thread.",
    sideChatPlaceholder: "Write a side message...",
    sideChatShortcut: "⌥⌘S",
    terminal: "Terminal",
    toggleFileList: "Show/hide file list",
    toggleRightPanel: "Show/hide side panel",
    truncated: "Large file truncated for preview",
    websitePermissions: "Website permissions",
    websitePermissionsHelp: "Override defaults for specific websites",
    zoom: "Zoom",
  }
}

export type StudioRightPanelLabels = ReturnType<
  typeof getStudioRightPanelLabels
>
