{{- if .Values.gpuInference.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gpuInference.models.asr.name }}
  labels:
    {{- include "astraflow-api.inferenceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.gpuInference.models.asr.name }}
  ports:
    - name: http
      port: 8001
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gpuInference.models.title.name }}
  labels:
    {{- include "astraflow-api.inferenceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.gpuInference.models.title.name }}
  ports:
    - name: http
      port: 8002
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gpuInference.gateway.name }}
  labels:
    {{- include "astraflow-api.inferenceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.gpuInference.gateway.name }}
  ports:
    - name: grpc
      port: {{ .Values.gpuInference.gateway.port }}
      targetPort: grpc
{{- end }}
