apiVersion: v1
kind: Service
metadata:
  name: {{ include "astraflow-api-service.fullname" . }}
  labels:
    {{- include "astraflow-api-service.labels" . | nindent 4 }}
  {{- if or .Values.service.resourcePolicy .Values.service.annotations }}
  annotations:
    {{- with .Values.service.resourcePolicy }}
    "helm.sh/resource-policy": {{ . | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.target.name | quote }}
    app.kubernetes.io/instance: {{ .Values.target.instance | quote }}
    {{- with .Values.selectorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
