*

!landing-page/
landing-page/*
!landing-page/Dockerfile
!landing-page/nginx.conf
!landing-page/package.json
!landing-page/bun.lock
!landing-page/index.html
!landing-page/postcss.config.js
!landing-page/tailwind.config.js
!landing-page/tsconfig.app.json
!landing-page/tsconfig.json
!landing-page/tsconfig.node.json
!landing-page/vite.config.ts
!landing-page/src/
!landing-page/src/**

!public/
!public/**
