// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"astraflow-api/internal/biz"
	"astraflow-api/internal/conf"
	"astraflow-api/internal/data"
	"astraflow-api/internal/server"
	"astraflow-api/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	healthRepo := data.NewHealthRepo(dataData)
	healthUsecase := biz.NewHealthUsecase(healthRepo)
	healthService := service.NewHealthService(healthUsecase)
	expertRepo := data.NewExpertRepo(dataData)
	expertUsecase := biz.NewExpertUsecase(expertRepo)
	expertService := service.NewExpertService(expertUsecase)
	feedbackRepo := data.NewFeedbackRepo(dataData)
	oAuthVerifier := data.NewUCloudOAuthVerifier()
	adminVerifier := data.NewAdminVerifier()
	feedbackUsecase := biz.NewFeedbackUsecase(feedbackRepo, oAuthVerifier, adminVerifier)
	feedbackService := service.NewFeedbackService(feedbackUsecase)
	channelRepo := data.NewChannelRepo(dataData)
	channelOAuthClient := data.NewChannelOAuthClient()
	channelUsecase := biz.NewChannelUsecase(channelRepo, adminVerifier, channelOAuthClient)
	channelService := service.NewChannelService(channelUsecase)
	marketplaceRepo := data.NewMarketplaceRepo(dataData)
	marketplaceUsecase := biz.NewMarketplaceUsecase(marketplaceRepo)
	marketplaceService := service.NewMarketplaceService(marketplaceUsecase)
	analyticsRepo := data.NewAnalyticsRepo(dataData)
	analyticsUsecase := biz.NewAnalyticsUsecase(analyticsRepo, oAuthVerifier, adminVerifier)
	analyticsService := service.NewAnalyticsService(analyticsUsecase)
	crossDeviceRepo := data.NewCrossDeviceRepo(dataData)
	identityResolver := data.NewUCloudIdentityResolver(dataData)
	nativeOAuthClient := data.NewNativeOAuthClient()
	crossDeviceUsecase := biz.NewCrossDeviceUsecase(crossDeviceRepo, identityResolver, nativeOAuthClient)
	crossDeviceService := service.NewCrossDeviceService(crossDeviceUsecase)
	modelCatalogClient := data.NewModelCatalogClient(dataData)
	modelCatalogUsecase := biz.NewModelCatalogUsecase(crossDeviceUsecase, modelCatalogClient)
	modelCatalogService := service.NewModelCatalogService(modelCatalogUsecase)
	artifactRepo := data.NewArtifactRepo(dataData)
	artifactObjectStore, err := data.NewArtifactObjectStore()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	artifactUsecase := biz.NewArtifactUsecase(crossDeviceUsecase, artifactRepo, artifactObjectStore)
	artifactService := service.NewArtifactService(artifactUsecase)
	cloudWorkerAuthenticator := data.NewCloudWorkerAuthenticator()
	cloudWorkerRepo := data.NewCloudWorkerRepo(dataData)
	cloudWorkerUsecase := biz.NewCloudWorkerUsecase(cloudWorkerAuthenticator, cloudWorkerRepo, artifactRepo, artifactObjectStore)
	cloudWorkerService := service.NewCloudWorkerService(cloudWorkerUsecase)
	automationRepo := data.NewAutomationRepo(dataData)
	automationUsecase := biz.NewAutomationUsecase(crossDeviceUsecase, automationRepo)
	automationService := service.NewAutomationService(automationUsecase)
	grpcServer := server.NewGRPCServer(confServer, logger, healthService, expertService, feedbackService, channelService, marketplaceService, analyticsService, crossDeviceService, modelCatalogService, artifactService, cloudWorkerService, automationService)
	deviceRelayHandler := server.NewDeviceRelayHandler(logger, crossDeviceUsecase)
	syncStreamHandler := server.NewSyncStreamHandler(crossDeviceService)
	httpServer := server.NewHTTPServer(confServer, logger, healthService, expertService, feedbackService, channelService, marketplaceService, analyticsService, crossDeviceService, modelCatalogService, artifactService, cloudWorkerService, automationService, deviceRelayHandler, syncStreamHandler)
	pushDeliveryRepo := data.NewPushDeliveryRepo(dataData)
	pushDispatcher, err := server.NewPushDispatcher(logger, pushDeliveryRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	automationScheduler := server.NewAutomationScheduler(logger, automationUsecase)
	app := newApp(logger, grpcServer, httpServer, pushDispatcher, automationScheduler)
	return app, func() {
		cleanup()
	}, nil
}
