// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"astraflow-api/internal/biz"
	"astraflow-api/internal/conf"
	"astraflow-api/internal/data"
	"astraflow-api/internal/server"
	"astraflow-api/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	healthRepo := data.NewHealthRepo(dataData)
	healthUsecase := biz.NewHealthUsecase(healthRepo)
	healthService := service.NewHealthService(healthUsecase)
	expertRepo := data.NewExpertRepo(dataData)
	expertUsecase := biz.NewExpertUsecase(expertRepo)
	expertService := service.NewExpertService(expertUsecase)
	grpcServer := server.NewGRPCServer(confServer, healthService, expertService)
	httpServer := server.NewHTTPServer(confServer, healthService, expertService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
