const en = {
  title: "Automations",
  current: "Current",
  details: "Details",
  status: "Status",
  lastRun: "Last ran",
  previousRuns: "Previous runs",
  pause: "Pause",
  resume: "Resume",
  searchPlaceholder: "Search tasks",
  allTypes: "All types",
  aiTasks: "AI tasks",
  commandTasks: "Command tasks",
  allStatuses: "All statuses",
  enabled: "Enabled",
  paused: "Paused",
  addTask: "New task",
  editTask: "Edit task",
  createTask: "Create task",
  saveChanges: "Save changes",
  cancel: "Cancel",
  back: "Back to tasks",
  delete: "Delete",
  edit: "Edit",
  runNow: "Run now",
  task: "Task",
  type: "Type",
  schedule: "Schedule",
  nextRun: "Next run",
  lastResult: "Last result",
  state: "State",
  actions: "Actions",
  ai: "AI",
  command: "Command",
  never: "Never",
  completed: "Completed",
  noTasks: "No scheduled tasks",
  noTasksDescription:
    "Create an AI or command task to run while CompShare is active.",
  noMatches: "No matching tasks",
  noMatchesDescription: "Adjust the search or filters to see more tasks.",
  loadFailed: "Scheduled tasks could not be loaded.",
  optionsLoadFailed: "Task configuration options could not be loaded.",
  createSucceeded: "Scheduled task created.",
  updateSucceeded: "Scheduled task updated.",
  deleteSucceeded: "Scheduled task deleted.",
  runQueued: "Task queued to run.",
  cancelSucceeded: "Run cancelled.",
  taskName: "Name",
  taskNamePlaceholder: "Daily project review",
  taskType: "Task type",
  taskTypeDescription:
    "AI tasks open an isolated Studio session. Command tasks run in a local workspace.",
  execution: "Execution",
  prompt: "Prompt",
  promptPlaceholder: "Review the workspace and summarize important changes.",
  workspace: "Workspace",
  noWorkspace: "No workspace",
  localWorkspaceRequired: "Select a local workspace",
  runtime: "Agent runtime",
  model: "Model",
  reasoning: "Reasoning effort",
  defaultReasoning: "Model default",
  permission: "Permission mode",
  readonly: "Read only",
  auto: "Auto",
  fullAccess: "Full access",
  shellCommand: "Command or script",
  shellCommandPlaceholder: "bun run lint",
  workingDirectory: "Relative working directory",
  workingDirectoryPlaceholder: ".",
  maxLogSize: "Maximum log size (MB)",
  timing: "Timing",
  scheduleType: "Schedule type",
  once: "Once",
  interval: "Interval",
  daily: "Daily",
  weekly: "Weekly",
  cron: "Cron",
  dateAndTime: "Date and time",
  every: "Every",
  minutes: "Minutes",
  hours: "Hours",
  days: "Days",
  startAt: "Start at",
  time: "Time",
  weekdays: "Weekdays",
  cronExpression: "Cron expression",
  cronPlaceholder: "0 9 * * 1-5",
  cronDescription: "Five fields: minute, hour, day of month, month, weekday.",
  timeZone: "Time zone",
  reliability: "Reliability",
  timeout: "Timeout (seconds)",
  concurrency: "When a previous run is active",
  skip: "Skip this run",
  queue: "Queue this run",
  misfire: "When a schedule was missed",
  runOnce: "Run the latest once",
  skipMissed: "Skip missed run",
  maxRetries: "Maximum retries",
  retryDelay: "Retry delay (seconds)",
  enabledAtSave: "Enable task",
  formInvalid: "Complete the required task settings.",
  configuration: "Configuration",
  runHistory: "Run history",
  noSelection: "Select a task",
  noSelectionDescription: "Choose a row to inspect its configuration and runs.",
  noRuns: "No runs yet",
  noRunsDescription: "Run the task now or wait for its next schedule.",
  trigger: "Trigger",
  started: "Started",
  duration: "Duration",
  result: "Result",
  output: "Output",
  openSession: "Open Studio session",
  cancelRun: "Cancel run",
  queued: "Queued",
  running: "Running",
  succeeded: "Succeeded",
  failed: "Failed",
  cancelled: "Cancelled",
  skipped: "Skipped",
  manual: "Manual",
  scheduled: "Schedule",
  catchUp: "Catch up",
  retry: "Retry",
  deleteTitle: "Delete scheduled task?",
  deleteDescription:
    "Its run history and generated AI sessions will also be removed.",
  deleteConfirm: "Delete task",
  activeSummary: "active",
  totalSummary: "total",
  monday: "Mon",
  tuesday: "Tue",
  wednesday: "Wed",
  thursday: "Thu",
  friday: "Fri",
  saturday: "Sat",
  sunday: "Sun",
  attempt: "Attempt",
  exitCode: "Exit code",
  error: "Error",
  downloadLog: "Download full log",
  refresh: "Refresh",
  loading: "Loading",
  backgroundSettings: "Background settings",
  keepRunning: "Keep running after closing windows",
  openAtLogin: "Open CompShare at login",
  desktopNotifications: "Task completion notifications",
} as const

export type AutomationCopy = Record<keyof typeof en, string>

const zh = {
  title: "自动化",
  current: "当前",
  details: "详细信息",
  status: "状态",
  lastRun: "上次运行",
  previousRuns: "历史运行",
  pause: "暂停",
  resume: "恢复",
  searchPlaceholder: "搜索任务",
  allTypes: "全部类型",
  aiTasks: "AI 任务",
  commandTasks: "命令任务",
  allStatuses: "全部状态",
  enabled: "已启用",
  paused: "已暂停",
  addTask: "新建任务",
  editTask: "编辑任务",
  createTask: "创建任务",
  saveChanges: "保存更改",
  cancel: "取消",
  back: "返回任务列表",
  delete: "删除",
  edit: "编辑",
  runNow: "立即运行",
  task: "任务",
  type: "类型",
  schedule: "执行计划",
  nextRun: "下次运行",
  lastResult: "最近结果",
  state: "状态",
  actions: "操作",
  ai: "AI",
  command: "命令",
  never: "从未运行",
  completed: "已完成",
  noTasks: "还没有定时任务",
  noTasksDescription: "创建 AI 或命令任务，在 CompShare 运行时自动执行。",
  noMatches: "没有匹配的任务",
  noMatchesDescription: "调整搜索或筛选条件后再试。",
  loadFailed: "无法加载定时任务。",
  optionsLoadFailed: "无法加载任务配置选项。",
  createSucceeded: "定时任务已创建。",
  updateSucceeded: "定时任务已更新。",
  deleteSucceeded: "定时任务已删除。",
  runQueued: "任务已加入运行队列。",
  cancelSucceeded: "运行已取消。",
  taskName: "名称",
  taskNamePlaceholder: "每日项目巡检",
  taskType: "任务类型",
  taskTypeDescription:
    "AI 任务会创建独立 Studio 会话；命令任务在本地工作区执行。",
  execution: "执行内容",
  prompt: "Prompt",
  promptPlaceholder: "检查工作区并总结需要关注的变更。",
  workspace: "工作区",
  noWorkspace: "不使用工作区",
  localWorkspaceRequired: "选择本地工作区",
  runtime: "Agent Runtime",
  model: "模型",
  reasoning: "思考强度",
  defaultReasoning: "使用模型默认值",
  permission: "权限模式",
  readonly: "只读",
  auto: "自动",
  fullAccess: "完全权限",
  shellCommand: "命令或脚本",
  shellCommandPlaceholder: "bun run lint",
  workingDirectory: "相对工作目录",
  workingDirectoryPlaceholder: ".",
  maxLogSize: "最大日志大小（MB）",
  timing: "执行时间",
  scheduleType: "计划类型",
  once: "仅一次",
  interval: "固定间隔",
  daily: "每天",
  weekly: "每周",
  cron: "Cron",
  dateAndTime: "日期和时间",
  every: "每隔",
  minutes: "分钟",
  hours: "小时",
  days: "天",
  startAt: "起算时间",
  time: "时间",
  weekdays: "星期",
  cronExpression: "Cron 表达式",
  cronPlaceholder: "0 9 * * 1-5",
  cronDescription: "五段格式：分、时、日、月、星期。",
  timeZone: "时区",
  reliability: "可靠性",
  timeout: "超时（秒）",
  concurrency: "上一次仍在运行时",
  skip: "跳过本次",
  queue: "加入队列",
  misfire: "错过计划时间时",
  runOnce: "只补跑最近一次",
  skipMissed: "跳过错过的运行",
  maxRetries: "最大重试次数",
  retryDelay: "重试延迟（秒）",
  enabledAtSave: "启用任务",
  formInvalid: "请完成必填的任务配置。",
  configuration: "任务配置",
  runHistory: "运行历史",
  noSelection: "选择一个任务",
  noSelectionDescription: "点击表格行查看任务配置和运行记录。",
  noRuns: "还没有运行记录",
  noRunsDescription: "立即运行任务，或等待下一个计划时间。",
  trigger: "触发方式",
  started: "开始时间",
  duration: "耗时",
  result: "结果",
  output: "输出",
  openSession: "打开 Studio 会话",
  cancelRun: "取消运行",
  queued: "排队中",
  running: "运行中",
  succeeded: "成功",
  failed: "失败",
  cancelled: "已取消",
  skipped: "已跳过",
  manual: "手动",
  scheduled: "计划",
  catchUp: "补跑",
  retry: "重试",
  deleteTitle: "删除定时任务？",
  deleteDescription: "运行历史和自动生成的 AI 会话也会一并删除。",
  deleteConfirm: "删除任务",
  activeSummary: "启用",
  totalSummary: "总计",
  monday: "周一",
  tuesday: "周二",
  wednesday: "周三",
  thursday: "周四",
  friday: "周五",
  saturday: "周六",
  sunday: "周日",
  attempt: "尝试次数",
  exitCode: "退出码",
  error: "错误",
  downloadLog: "下载完整日志",
  refresh: "刷新",
  loading: "加载中",
  backgroundSettings: "后台设置",
  keepRunning: "关闭窗口后继续运行",
  openAtLogin: "开机时自动启动 CompShare",
  desktopNotifications: "任务完成时发送通知",
} satisfies AutomationCopy

export function getAutomationCopy(locale: string): AutomationCopy {
  return locale === "zh" ? zh : en
}
