// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astraflow/inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*TranscribeRequest_Audio
	//	*TranscribeRequest_AudioUri
	Source        isTranscribeRequest_Source `protobuf_oneof:"source"`
	MimeType      string                     `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	LanguageHint  string                     `protobuf:"bytes,4,opt,name=language_hint,json=languageHint,proto3" json:"language_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetSource() isTranscribeRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TranscribeRequest) GetAudio() []byte {
	if x != nil {
		if x, ok := x.Source.(*TranscribeRequest_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *TranscribeRequest) GetAudioUri() string {
	if x != nil {
		if x, ok := x.Source.(*TranscribeRequest_AudioUri); ok {
			return x.AudioUri
		}
	}
	return ""
}

func (x *TranscribeRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *TranscribeRequest) GetLanguageHint() string {
	if x != nil {
		return x.LanguageHint
	}
	return ""
}

type isTranscribeRequest_Source interface {
	isTranscribeRequest_Source()
}

type TranscribeRequest_Audio struct {
	Audio []byte `protobuf:"bytes,1,opt,name=audio,proto3,oneof"`
}

type TranscribeRequest_AudioUri struct {
	AudioUri string `protobuf:"bytes,2,opt,name=audio_uri,json=audioUri,proto3,oneof"`
}

func (*TranscribeRequest_Audio) isTranscribeRequest_Source() {}

func (*TranscribeRequest_AudioUri) isTranscribeRequest_Source() {}

type TranscribeReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Transcript       string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	DetectedLanguage string                 `protobuf:"bytes,2,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	DurationMs       int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TranscribeReply) Reset() {
	*x = TranscribeReply{}
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeReply) ProtoMessage() {}

func (x *TranscribeReply) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeReply.ProtoReflect.Descriptor instead.
func (*TranscribeReply) Descriptor() ([]byte, []int) {
	return file_astraflow_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeReply) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *TranscribeReply) GetDetectedLanguage() string {
	if x != nil {
		return x.DetectedLanguage
	}
	return ""
}

func (x *TranscribeReply) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TranscribeReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GenerateTitleRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Transcript string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Language   string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Optional caller-selected limit. Zero means no character limit.
	MaxCharacters uint32 `protobuf:"varint,3,opt,name=max_characters,json=maxCharacters,proto3" json:"max_characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTitleRequest) Reset() {
	*x = GenerateTitleRequest{}
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTitleRequest) ProtoMessage() {}

func (x *GenerateTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTitleRequest.ProtoReflect.Descriptor instead.
func (*GenerateTitleRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateTitleRequest) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *GenerateTitleRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GenerateTitleRequest) GetMaxCharacters() uint32 {
	if x != nil {
		return x.MaxCharacters
	}
	return 0
}

type GenerateTitleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTitleReply) Reset() {
	*x = GenerateTitleReply{}
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTitleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTitleReply) ProtoMessage() {}

func (x *GenerateTitleReply) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTitleReply.ProtoReflect.Descriptor instead.
func (*GenerateTitleReply) Descriptor() ([]byte, []int) {
	return file_astraflow_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateTitleReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateTitleReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_astraflow_inference_v1_inference_proto protoreflect.FileDescriptor

const file_astraflow_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"&astraflow/inference/v1/inference.proto\x12\x16astraflow.inference.v1\"\x96\x01\n" +
	"\x11TranscribeRequest\x12\x16\n" +
	"\x05audio\x18\x01 \x01(\fH\x00R\x05audio\x12\x1d\n" +
	"\taudio_uri\x18\x02 \x01(\tH\x00R\baudioUri\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12#\n" +
	"\rlanguage_hint\x18\x04 \x01(\tR\flanguageHintB\b\n" +
	"\x06source\"\x95\x01\n" +
	"\x0fTranscribeReply\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12+\n" +
	"\x11detected_language\x18\x02 \x01(\tR\x10detectedLanguage\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"y\n" +
	"\x14GenerateTitleRequest\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12%\n" +
	"\x0emax_characters\x18\x03 \x01(\rR\rmaxCharacters\"@\n" +
	"\x12GenerateTitleReply\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model2\xdf\x01\n" +
	"\x10InferenceService\x12`\n" +
	"\n" +
	"Transcribe\x12).astraflow.inference.v1.TranscribeRequest\x1a'.astraflow.inference.v1.TranscribeReply\x12i\n" +
	"\rGenerateTitle\x12,.astraflow.inference.v1.GenerateTitleRequest\x1a*.astraflow.inference.v1.GenerateTitleReplyB6Z4astraflow-api/api/astraflow/inference/v1;inferencev1b\x06proto3"

var (
	file_astraflow_inference_v1_inference_proto_rawDescOnce sync.Once
	file_astraflow_inference_v1_inference_proto_rawDescData []byte
)

func file_astraflow_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_astraflow_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_astraflow_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraflow_inference_v1_inference_proto_rawDesc), len(file_astraflow_inference_v1_inference_proto_rawDesc)))
	})
	return file_astraflow_inference_v1_inference_proto_rawDescData
}

var file_astraflow_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_astraflow_inference_v1_inference_proto_goTypes = []any{
	(*TranscribeRequest)(nil),    // 0: astraflow.inference.v1.TranscribeRequest
	(*TranscribeReply)(nil),      // 1: astraflow.inference.v1.TranscribeReply
	(*GenerateTitleRequest)(nil), // 2: astraflow.inference.v1.GenerateTitleRequest
	(*GenerateTitleReply)(nil),   // 3: astraflow.inference.v1.GenerateTitleReply
}
var file_astraflow_inference_v1_inference_proto_depIdxs = []int32{
	0, // 0: astraflow.inference.v1.InferenceService.Transcribe:input_type -> astraflow.inference.v1.TranscribeRequest
	2, // 1: astraflow.inference.v1.InferenceService.GenerateTitle:input_type -> astraflow.inference.v1.GenerateTitleRequest
	1, // 2: astraflow.inference.v1.InferenceService.Transcribe:output_type -> astraflow.inference.v1.TranscribeReply
	3, // 3: astraflow.inference.v1.InferenceService.GenerateTitle:output_type -> astraflow.inference.v1.GenerateTitleReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_astraflow_inference_v1_inference_proto_init() }
func file_astraflow_inference_v1_inference_proto_init() {
	if File_astraflow_inference_v1_inference_proto != nil {
		return
	}
	file_astraflow_inference_v1_inference_proto_msgTypes[0].OneofWrappers = []any{
		(*TranscribeRequest_Audio)(nil),
		(*TranscribeRequest_AudioUri)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraflow_inference_v1_inference_proto_rawDesc), len(file_astraflow_inference_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraflow_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_astraflow_inference_v1_inference_proto_depIdxs,
		MessageInfos:      file_astraflow_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_astraflow_inference_v1_inference_proto = out.File
	file_astraflow_inference_v1_inference_proto_goTypes = nil
	file_astraflow_inference_v1_inference_proto_depIdxs = nil
}
